### ISSUE TITLE
COLOR_0 attribute in glTF models causes crash in Model.js

### ISSUE THREAD

**Issue by alinen** [AnalyticalGraphicsInc/cesium#5061] opened 2017-03-01 22:12 UTC
Dear Cesium Team,

Tested in Cesium 1.3.

The crash is due to missing keyword for COLOR_0 in gltfSemanticUniforms. I currently work around the issue with the following change:

Model.js LINE 2859 
 if (parameter.semantic !== 'JOINTMATRIX' && gltfSemanticUniforms[parameter.semantic] != undefined) {

A model which demonstrates the problem can be found here: 
https://github.com/AnalyticalGraphicsInc/agi-cesium-arcade-game/tree/new-drone-model/Models/Drone_Shell/drone.gltf

**Comment by hpinkos** [comment] 2017-03-02 14:09
@alinen did you mean Cesium 1.3 or 1.30?

**Comment by lilleyse** [comment] 2017-03-02 14:54
It looks like the problem is the technique is referencing the color as a uniform when it should be as an attribute. I attached the fixed model - it loads in Cesium now but doesn't show colors, the shader needs to support them still.
[drone.gltf.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/814133/drone.gltf.txt)

**Comment by pjcozzi** [comment] 2017-03-06 16:28
@alinen how did you generate the glTF?  It would be worth submitting a bug there.

> it loads in Cesium now but doesn't show colors, the shader needs to support them still.

@lilleyse I'm not following; is this a Cesium issue?

**Comment by lilleyse** [comment] 2017-03-06 17:04
It's a problem with the glTF, not Cesium.

**Comment by alinen** [comment] 2017-03-06 17:20
Dear all, 

First, I really appreciate everyone's input on this!

@pjcozzi I created the glTF from FBX using code based on https://github.com/cyrillef/FBX-glTF.  It appears to not be actively maintained but I am able to fix/workaround problems in my own forked copy, so I'm not worried about it. I can mention that the color should be exported as an attribute.

@lilleyse  With a modified model, it indeed works fine! It's also not important to support colors in the shader for this model.

In my opinion, Cesium should check for valid gltfSemanticUniforms to avoid an exception on an unsupported feature and /or bad model.  But that's up to you.  I added the check in our version of Cesium for convenience.

**Comment by pjcozzi** [comment] 2017-03-07 23:51
As glTF 2.0 stabilizes, you'll be able to check if a glTF model is valid with the validator, https://github.com/KhronosGroup/glTF-Validator.

Generally, runtime engines will not include validation to keep them small and light.

Closing since this is a data fix.  Glad you guys got to the bottom of this.

**Closed by pjcozzi** 2017-03-07 23:51 UTC
