### ISSUE TITLE
When the map is enlarged, it looks blurry

### ISSUE THREAD

**Issue by giantss** [AnalyticalGraphicsInc/cesium#7644] opened 2019-03-13 11:24 UTC
Hello everyone : 
   I have a problem that is a headache. After zooming in on the map to a certain level, The font display is blurry and looks a bit like a picture distortion. Why is this happening?

The comparison effect of 4 pictures is as follows:

### OpenStreetMap official
![image](https://user-images.githubusercontent.com/13778798/54266248-f5fc6e80-45b1-11e9-9a6c-a9ce2b084228.png)

### cesium in PC Chrome browser
![OpenStreetMap official](https://user-images.githubusercontent.com/13778798/54266543-8c309480-45b2-11e9-90bb-641d1ef32f11.png)

### cesium in iPhone mobile Safari browser
![image](https://user-images.githubusercontent.com/13778798/54274626-80999980-45c3-11e9-8d6b-22e30060757a.png)

###  react native to display in WebView
![image](https://user-images.githubusercontent.com/13778798/54266450-60151380-45b2-11e9-8745-d62032594443.png)

**Comment by hpinkos** [comment] 2019-03-13 14:22
Hello @giantss, I believe this is a duplicate of this issue: #3279
I've made a comment on that issue and we will notify you when it gets resolved.  In the meantime, I believe there are suggested workarounds in #3279

**Closed by hpinkos** 2019-03-13 14:22 UTC
