### ISSUE TITLE
Geocoder flights should take into account terrain

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1670] opened 2014-05-01 13:12 UTC
For example:
* Run Cesium Viewer
* Use the base layer picker to turn on STK World Terrain
* Use the geocoder to zoom to Mount Everest

The viewer ends up under terrain.

**Comment by tlpinney** [comment] 2015-02-10 20:48
I tested this issue using 9f5fa6a2337b854caae08a8b45c9a5045d4b43c2 on OSX Yosemite using the following browsers.

Chrome: Version 40.0.2214.111 (64-bit)
Firefox: 35.0.1 

I am not able to reproduce the issue.

**Comment by AnandDhoot** [comment] 2015-03-07 03:51
I tested this bug on Linux Ubuntu as well as Windows 8.1 on the following browsers -

Ubuntu -
Chrome: Version 41.0.2272.76 (64-bit)
Firefox: 35.0.1

Windows - 
Chrome: Version 41.0.2272.76 (64-bit)
Firefox: 35.0.1
Internet Explorer: 11.0.9600.17631

I am unable to reproduce the issue. Am I missing something?

**Comment by pjcozzi** [comment] 2015-03-07 13:30
Did you include this step?

> Use the base layer picker to turn on STK World Terrain

The UI is in the upper-right corner of Cesium Viewer.

**Comment by AnandDhoot** [comment] 2015-03-07 15:50
Yeah. I have set `Terrain` to `STK World Terrain meshes`

**Comment by pjcozzi** [comment] 2015-03-07 16:40
I agree this does not seem to be a problem any more, most likely because Bing is now returning a larger rectangle so the camera is zoomed out more.  I suspect if we zoom to a specific address with a high altitude, we could reproduce this problem, but my tests did not prove this.

I still think we should "fix" this by sampling our terrain - at least to provide a minimal view distance, but given that this is hard to reproduce, this should be a low priority for now.

**Comment by AnandDhoot** [comment] 2015-03-07 17:00
Okay. Request you to guide me with some other bug I can take up..

**Comment by pjcozzi** [comment] 2015-03-07 17:04
@AnandDhoot what project are you interested in from our Ideas List?  For most projects, it will be a more valuable experience for you to go through the Cesium [tutorials](http://cesiumjs.org/tutorials.html) and write a small demo than to fix a bug.

**Comment by mramato** [comment] 2015-03-16 02:30
@pjcozzi I actually think the terrain intersection detection that @bagnell added to the camera ends up fixing this.  So I'm not sure if we need to do anything more.  @bagnell can you chime in here and close this if you agree?

**Comment by bagnell** [comment] 2015-03-16 15:42
The camera does get pushed above the terrain if the destination is below it. Closing.

**Closed by bagnell** 2015-03-16 15:42 UTC
Labels: beginner, enhancement
