### ISSUE TITLE
DeveloperError When remove a primitive from PrimitiveCollection

### ISSUE THREAD

**Issue by micromiss** [AnalyticalGraphicsInc/cesium#5577] opened 2017-07-02 13:40 UTC
I have wrote a function that will caused specific primitive removed from a PrimitiveCollection when the camera moved. But It will cause a strange error  sometimes(seems this error always happens when I zoom in or zoom out the camera...).

This is how a use the remove function of PrimitiveCollection:
```
   var a = primitives.get(i);
   primitives.remove(a);
```
And I've tried to ignore the error by "try ... catch ..." but it doesn't work. And I also tried to prevent repetitive destroy by the sentence below(but it doesn't work as well):
  ```
  if(a.hasOwnProperty("isDestroyed"))
    {
        continue;
    }

```

I' m using Cesium 1.30 and here is the strange error:
```
An error occurred while rendering. Rendering has stopped.
DeveloperError: This object was destroyed, i.e., destroy() was called.
Error
    at new DeveloperError (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:605:19)
    at Model.throwOnDestroyed (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:30221:31)
    at PrimitiveCollection.update (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:185696:27)
    at updatePrimitives (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:194356:27)
    at executeCommandsInViewport (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:194222:13)
    at updateAndExecuteCommands (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:194085:17)
    at render (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:194575:9)
    at Scene.render (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:194613:13)
    at CesiumWidget.render (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:208408:25)
    at render (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:207804:32)
```

**Comment by hpinkos** [comment] 2017-07-05 16:06
Hello @micromiss, can you please provide a more complete code sample that reproduces the crash in [Sandcastle](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html)?  Thanks

**Comment by micromiss** [comment] 2017-07-07 15:33
Thanks for your reply !
Um... I'm not quite sure that you can reproduce the crash in Sandcastle since that there is a complicated logic to control the creation and destroy of the primitives in my project. Um... So I'm try to show some important part here.
This function will be executed when users move their cameras. It will remove any primitives (from .gltf)  which are too far away from the camera.
`               var primitives = viewer.scene.primitives;
                // Remove all the models which should not be rendered.
                for(var i=0;i<primitives.length;i++){
                    var id = primitives.get(i).id;
                    if(typeof (id)=="undefined" || typeof(id)!="string" ||id.indexOf('ignore')==0 )continue;
                    // If this primitive should not be rendered, then remove it.
                    var isfound = models_priority.find(id,maxRenderNum);
                    if (isfound == false) {
                        primitives.remove(primitives.get(i));
                    }
                }`

**Comment by hpinkos** [comment] 2019-09-19 18:05
Closing this since we haven't gotten a good test case to reproduce the crash. @micromiss if you're still experiencing this issue feel free to reopen

**Closed by hpinkos** 2019-09-19 18:05 UTC
Labels: category - graphics, type - bug

**Comment by Soni-pro** [comment] 2024-02-16 06:04
> I have wrote a function that will caused specific primitive removed from a PrimitiveCollection when the camera moved. But It will cause a strange error sometimes(seems this error always happens when I zoom in or zoom out the camera...).
> 
> This is how a use the remove function of PrimitiveCollection:
> 
> ```
>    var a = primitives.get(i);
>    primitives.remove(a);
> ```
> 
> And I've tried to ignore the error by "try ... catch ..." but it doesn't work. And I also tried to prevent repetitive destroy by the sentence below(but it doesn't work as well):
> 
> ```
> if(a.hasOwnProperty("isDestroyed"))
>   {
>       continue;
>   }
> ```
> 
> I' m using Cesium 1.30 and here is the strange error:
> 
> ```
> An error occurred while rendering. Rendering has stopped.
> DeveloperError: This object was destroyed, i.e., destroy() was called.
> Error
>     at new DeveloperError (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:605:19)
>     at Model.throwOnDestroyed (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:30221:31)
>     at PrimitiveCollection.update (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:185696:27)
>     at updatePrimitives (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:194356:27)
>     at executeCommandsInViewport (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:194222:13)
>     at updateAndExecuteCommands (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:194085:17)
>     at render (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:194575:9)
>     at Scene.render (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:194613:13)
>     at CesiumWidget.render (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:208408:25)
>     at render (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:207804:32)
> ```

getting same error in cesium version 1.113. can anyone suggest how to resolve this
