### ISSUE TITLE
Clustering renders additional pointprimitives (unset) to the screen. 

### ISSUE THREAD

**Issue by cpt-chewieeee** [AnalyticalGraphicsInc/cesium#7045] opened 2018-09-17 20:13 UTC
[Cluster Example](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Clustering.html
)

In the above example, when you zoom-in the globe, a white PointPrimitive would appear in the center of the screen. This would only happen when the "Enabled" checkbox is set. When you zoom-out far enough, eventually the PointPrimitive would disappear on the globe. 
![cesium-bug](https://user-images.githubusercontent.com/5933818/45645484-6ac47500-ba75-11e8-96b1-e74ee4df9e59.png)

Im not sure why this white PointPrimitive is being rendering to the screen. 

----

In my cesium app, 
1) I also see this white PointPrimitive in the center as I zoom-in. 
2) When I click on this white PointPrimitive in the center, it would reset the location of the PointPrimitive to its cluster. 
![my-cesium-bug](https://user-images.githubusercontent.com/5933818/45646554-8aa96800-ba78-11e8-91ab-cc74aff28c5e.png)

3) Then I zoom-out far enough so the PointPrimitive does not appear on my globe, next time when I zoom-in, the PointPrimitives would be reset to the center on my screen instead of appearing to its cluster. 

Is there a work-around/quick fix to stop this random PointPrimitive to be rendered on the screen?

**Comment by hpinkos** [comment] 2018-09-18 16:09
@cpt-chewieeee sorry, I could not reproduce the problem you are seeing.  What browser and OS are you using?  Can you try the sandcastle example reported in #7031 to see if it's the same problem?

**Comment by cpt-chewieeee** [comment] 2018-09-18 19:37
Im using:
- OS: Linux x86_64/Ubuntu 18.04.1 LTS
- Processor: Intel Xeon
- GPU: quadro m4000
- Browser: Chrome v69.0.3497.92, Firefox Quantum v62.0
- Cesium versions: v1.42.1 and v1.49.0
*This issue does not appear on window10 and iOS
----
I do also see the phantom pointPrimitive in #7031. These two issues seems related. The only major difference is that I encounter the phantom pointPrimitive only for a set of clusters. 

In my above image (2nd picture), if my view does not contain any clusters and only entities, then the phantom PointPrimitives goes away and would not reappear anywhere after that. It would reappear (and reset to the center) when the cluster icon appear in the screen. I never encountered this issue using entity in own cesium apps. 

Besides that, the behavior of this phantom pointprimitive that I've experienced is similar to #7031. such that:
- no id
- cant find it anywhere in cesium
- cant be removed
- disappear/reappear depending on the camera position (height)

**Comment by hpinkos** [comment] 2018-09-18 19:46
Thanks for the extra info @cpt-chewieeee!  This seems to be a linux only problem.  We've looked into it a little bit and haven't been able to track it down yet, but will make it a higher priority since it's been reported by a few different users.

I'm going to close this issue as a duplicate of #7031, but I'll make a comment there with your example so we can make sure both cases are fixed and notify you when that gets merged in.

**Closed by hpinkos** 2018-09-18 19:46 UTC

**Comment by cpt-chewieeee** [comment] 2018-09-18 19:51
I just tested on another computer with ubuntu 16.04.5 LTS (Chrome v69.0.3497.92) , and the phantom PointPrimitive does not appear.

**Comment by mramato** [comment] 2018-09-18 19:51
I wouldn't say this is Linux only, since plenty of Linux machines work.  It's more likely something graphics driver specific.

@cpt-chewieeee Can you visit http://webglreport.com/ on Chrome 69 on the offending machine and paste the results of the WebGL 1 report (just select all/copy and GitHub will make a pretty table when you paste it).

**Comment by cpt-chewieeee** [comment] 2018-09-18 19:53
Platform: | Linux x86_64
-- | --
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
webgl
WebGL 1.0 (OpenGL ES 2.0 Chromium)
WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
WebKit
WebKit WebGL
NVIDIA Corporation
Quadro M4000/PCIe/SSE2
Available
No
No
Vertex ShaderMax Vertex Attributes:16Max Vertex Uniform Vectors:1024Max Vertex Texture Image Units:32Max Varying Vectors:31Best float precision:[-2127, 2127] (23)Transform FeedbackComing in WebGL 2RasterizerAliased Line Width Range:[1, 10]Aliased Point Size Range:[1, 189.875]Fragment ShaderMax Fragment Uniform Vectors:1024Max Texture Image Units:32float/int precision:highp/highpBest float precision:[-2127, 2127] (23)FramebufferMax Color Buffers:8RGBA Bits:[8, 8, 8, 8]Depth / Stencil Bits:[24, 8]Max Render Buffer Size:16384Max Viewport Dimensions:[16384, 16384]TexturesMax Texture Size:16384Max Cube Map Texture Size:16384Max Combined Texture Image Units:192Max Anisotropy:16Uniform BuffersComing in WebGL 2 | 16 | 1024 | 32 | 31 | [-2127, 2127] (23) | [1, 10] | [1, 189.875] | 1024 | 32 | highp/highp | [-2127, 2127] (23) | 8 | [8, 8, 8, 8] | [24, 8] | 16384 | [16384, 16384] | 16384 | 16384 | 192 | 16
16
1024
32
31
[-2127, 2127] (23)
[1, 10]
[1, 189.875]
1024
32
highp/highp
[-2127, 2127] (23)
8
[8, 8, 8, 8]
[24, 8]
16384
[16384, 16384]
16384
16384
192
16

  | ANGLE_instanced_arrays
  | EXT_blend_minmax
  | EXT_color_buffer_half_float
  | EXT_frag_depth
  | EXT_shader_texture_lod
  | EXT_texture_filter_anisotropic
  | WEBKIT_EXT_texture_filter_anisotropic
  | EXT_sRGB
  | OES_element_index_uint
  | OES_standard_derivatives
  | OES_texture_float
  | OES_texture_float_linear
  | OES_texture_half_float
  | OES_texture_half_float_linear
  | OES_vertex_array_object
  | WEBGL_color_buffer_float
  | WEBGL_compressed_texture_s3tc
  | WEBKIT_WEBGL_compressed_texture_s3tc
  | WEBGL_compressed_texture_s3tc_srgb
  | WEBGL_debug_renderer_info
  | WEBGL_debug_shaders
  | WEBGL_depth_texture
  | WEBKIT_WEBGL_depth_texture
  | WEBGL_draw_buffers
  | WEBGL_lose_context
  | WEBKIT_WEBGL_lose_context
To see draft extensions in Chrome, browse to about:flags, enable the "Enable WebGL Draft Extensions" option, and relaunch.
