### ISSUE TITLE
PolygonGraphics doesn't play well with depthTestAgainstTerrain

### ISSUE THREAD

**Issue by alexander-entin** [AnalyticalGraphicsInc/cesium#2568] opened 2015-03-10 15:26 UTC
run below code and zoom in/out
````
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.scene.globe.depthTestAgainstTerrain = true

var redPolygon = viewer.entities.add({
    name : 'Red polygon on surface',
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArray([-115.0, 37.0,
                                                        -115.0, 32.0,
                                                        -107.0, 33.0,
                                                        -102.0, 31.0,
                                                        -102.0, 35.0]),
        material : Cesium.Color.RED
        , height: 1
        , granularity: 0.001
    }
});

var bluePolygon = viewer.entities.add({
    name : 'Blue polygon with holes and outline',
    polygon : {
        hierarchy : {
            positions : Cesium.Cartesian3.fromDegreesArray([-99.0, 30.0,
                                                            -85.0, 30.0,
                                                            -85.0, 40.0,
                                                            -99.0, 40.0]),
            holes : [{
                positions : Cesium.Cartesian3.fromDegreesArray([
                    -97.0, 31.0,
                    -97.0, 39.0,
                    -87.0, 39.0,
                    -87.0, 31.0
                ]),
                holes : [{
                    positions : Cesium.Cartesian3.fromDegreesArray([
                        -95.0, 33.0,
                        -89.0, 33.0,
                        -89.0, 37.0,
                        -95.0, 37.0
                    ]),
                    holes : [{
                        positions : Cesium.Cartesian3.fromDegreesArray([
                            -93.0, 34.0,
                            -91.0, 34.0,
                            -91.0, 36.0,
                            -93.0, 36.0
                        ])
                    }]
                }]
            }]
        },
        material : Cesium.Color.BLUE,
        outline : true,
        outlineColor : Cesium.Color.BLACK
    }
});

viewer.zoomTo(viewer.entities);
````

**Comment by pjcozzi** [comment] 2015-03-10 17:47
This is a duplicate of #2172 (which perhaps should be called "vector data on ground").  We are working on this in the [ground-primitive](https://github.com/AnalyticalGraphicsInc/cesium/tree/ground-primitive) branch.  In the meantime, you could apply a small height to your polygon.

**Closed by pjcozzi** 2015-03-10 17:47 UTC
