### ISSUE TITLE
Labels should render above Polygons and Polylines regardless of order added

### ISSUE THREAD

**Issue by jktaylor** [AnalyticalGraphicsInc/cesium#53] opened 2012-05-31 22:43 UTC
No matter what altitude I put my label at, it always gets rendered beneath a polygon or polyline when the primitive is added after the labelcollection.  To see what I mean, try In the Sandbox to paste the label code example into the polygon example and move the label's position so it intersects with the polygon. 

I can use sendtoback in compositeprimitive to keep the ordering correct, but I was just thinking that maybe this should be done always in the compositeprimitive class without my intervention.

**Comment by drakej** [comment] 2016-02-18 16:46
This would be nice although any form of draw ordering control is welcome.

**Comment by hpinkos** [comment] 2016-12-07 15:13
duplicate of #4108

**Closed by hpinkos** 2016-12-07 15:13 UTC
Labels: enhancement
