### ISSUE TITLE
GroundPolylineGeometry glitches on mobile (and others clamp to ground geometries doesn't display at all)

### ISSUE THREAD

**Issue by Spec1alFx** [AnalyticalGraphicsInc/cesium#7377] opened 2018-12-04 03:04 UTC
[Original forum post with screenshot here](https://cesiumjs.org/forum/#!msg/cesium-dev/7IMNjtSxKIU/bWZR54R0AAAJ).

I encountered graphical glitches with GroundPolylineGeometry on mobile when camera is quite near / far of this kind of polyline;
the problem it's consistent on every modern smartphone I tried on (Galaxy Note 9, Huawei P9 Lite, Wikio UFeel; iPhone 6), meanwhile on a Note 3 polyline is drawn under the terrain - but it's an old device, I don't think it's a big concern (*).

I'm able to reproduce the problem on every Sandcastle demo I tried;
with this one:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Clamp%20to%20Terrain.html

I encountered another problem: a lot of geometries are not displayed at all on modern mobile devices. But there is already an open issue (https://github.com/AnalyticalGraphicsInc/cesium/issues/7273).

_Please consider this two bugs related_ because today I can't use corridors as fallback on mobile.

*: I suppose that with a flag like Cesium.Entity.supportsPolylinesOnTerrain I can make things work also on older device switching to corridors if GroundPolylineGeometry are not supported;
it's a paradox but on my old Note 3 corridors are correctly rendered!

Thank you!

**Comment by Spec1alFx** [comment] 2018-12-05 10:33
Thank to you, Hannah.

I have attached screenshot for both WebGL 1 / WebGL 2;
sorry but with plain text copy / paste the result is terrible.

Browsers: Chrome on Android smartphones, Safari on iPhone. I'm a traditionalist. :)

![screenshot_20181205-112545_chrome](https://user-images.githubusercontent.com/16166464/49507609-1ca75c80-f881-11e8-81a8-ab3f871529e7.jpg)
![screenshot_20181205-112556_chrome](https://user-images.githubusercontent.com/16166464/49507611-1ca75c80-f881-11e8-8d6c-fa111d507d18.jpg)
![screenshot_20181205-112600_chrome](https://user-images.githubusercontent.com/16166464/49507612-1d3ff300-f881-11e8-9f57-3358789d618d.jpg)
![screenshot_20181205-112533_chrome](https://user-images.githubusercontent.com/16166464/49507613-1d3ff300-f881-11e8-873c-4ea082919d9a.jpg)

**Comment by likangning93** [comment] 2018-12-05 14:35
Related: https://github.com/AnalyticalGraphicsInc/cesium/issues/6739 and #6735

**Comment by Spec1alFx** [comment] 2018-12-07 04:47
D'oh! Sorry for opening a issue clone;
I made some searches but I miss them.

**Comment by hpinkos** [comment] 2018-12-07 15:09
@Spec1alFx no worries!  We have a hard time finding the right open issue sometimes too =)

I'm going to close this as a duplicate of #6735

**Closed by hpinkos** 2018-12-07 15:09 UTC
Labels: category - graphics, category - polyline, type - bug
