### ISSUE TITLE
iOS Safari cesium main demo crashes

### ISSUE THREAD

**Issue by drewpotter** [AnalyticalGraphicsInc/cesium#4279] opened 2016-09-03 17:07 UTC
Hello everyone,

Cesium rocks. I bought the book on virtual globes and now I'm going to use cesium in a web app I am making.

However I noticed that on the iPad Pro 9.7 inch the cesium main demo actually crashes out in Safari.

I haven't tried using chrome on my my iPad yet. However I just thought I'd inform you about this issue in case it can be fixed somehow. Perhaps I should rather file this bug on the Apple bug reports.

Thanks,

Andrew

**Comment by hpinkos** [comment] 2016-09-06 21:04
Thanks @drewpotter! What version of Safari is on your iPad?
Which demo was crashing, the one on the [Cesiumjs.org](http://cesiumjs.org/) home page?
Where there any error messages that popped up on screen?

Thanks!

**Comment by drewpotter** [comment] 2016-09-07 18:34
Hi,

Sorry for taking so long to write back! My iPad is running Safari 9 on iOS 9.3.5.

The demo that crashes is when you click on the link "Tap to interact" the main demo in the middle of the page.

I get the message: A problem occurred with this web page, so it was reloaded. Safari does not elaborate on what the issue was.

Also, when I run the same demo on Safari on my MacBook Pro using El Capitan 10.11.6 I get nothing happening at all. It seems like Safari has some real issues with this!

**Comment by hpinkos** [comment] 2016-09-07 18:55
Thanks @drewpotter!  We'll see if we can reproduce the problem

**Comment by pjcozzi** [comment] 2016-09-07 21:28
@drewpotter we have been testing other Cesium apps successfully with the 12.9 inch iPad Pro.  @lilleyse can you take a quick look to see if the cesiumjs.org demo crashes it?

**Comment by drewpotter** [comment] 2016-09-08 16:48
Thanks @pjcozzi for that info. I can't imagine why it only affects the 9.7 inch iPad Pro.

Maybe something is different?

**Comment by shunter** [comment] 2016-09-08 17:13
I tested a bit on my iPad Air 2 and I was able to get the homepage demo to crash the tab reliably after zooming and panning a bit.  Unfortunately the error "A problem occurred with this web page, so it was reloaded." indicates an internal programming error inside Safari itself and not really anything we can debug from Cesium.  We generally push WebGL to its limits, and very commonly we run into bad code in browsers, and historically, Apple hasn't seemed to put much effort into WebGL reliability.  See previous issue #1805 from last year about mobile Safari.

**Comment by mramato** [comment] 2016-09-08 17:13
> I haven't tried using chrome on my my iPad yet. However I just thought I'd inform you about this issue in case it can be fixed somehow.

Just an FYI, all browsers on iOS (even Chrome) are actually really Safari in the background with a custom user interface on top of it.  So if something is broken on Safari it will certainly almost always be broken in Chrome.  Unfortunately Safari just isn't a very good browser when it comes to WebGL and complex JavaScript apps.  That being said, we definitely want to make Safari work as well for Cesium as other browsers do, so thanks for bringing this to our attention.

I may be able to get a hold of a `iPad Pro 9.7` to try this on and see if it crashes.

Just to rule out other potential issues, is this a standard US model running in english?  It's possible (though unlikely) that there are slight differences depending on regional settings.  Do you have any adblockers or enhanced browser security enabled?

**Comment by mramato** [comment] 2016-09-08 17:17
@shunter I think that problem can also occur if we run out of video (or system) memory.  It's possible that the large retina display causes issues because we don't honor the DPI settings (because Safari doesn't support `'image-rendering: pixelated;'`  We can confirm this by forcing Cesium to honor the DPI settings and see if it still crashes.  I'm really hoping Safari 10 on iOS adds improved support for both `image-rendering` and WebGL/JavaScript in general.

**Comment by lilleyse** [comment] 2016-09-08 17:23
I've been testing a custom demo (no globe) on the iPad Pro 12.9" that runs fine, at least if the GPU memory doesn't hit 1GB or more. I can also run the main demo page ok.

**Comment by drewpotter** [comment] 2016-09-10 13:38
Thanks everyone for the feedback. I have submitted the bug to Apple directly. They have requested the actual log files from the iPad which I have submitted to them.

**Comment by chriseyhorn** [comment] 2016-09-13 15:56
@drewpotter Can you post the top part of the crash report?  We are also currently experiencing the same issue and want to see if it is the same exception.

**Comment by drewpotter** [comment] 2016-09-14 19:11
Hi sorry for the late response. I have been overwhelmed with work.

@chriseyhorn I will post the top part of the crash report which I think is the correct one, I hope this is correct. Only the iPad only crashed on the cesium demo on the same day and there weren't any other crashes.

GitHub won't allow me to attach the file, so here is the pasted text; If you like I can email you the log file; exception is 0x8badf00d;

{"timestamp":"2016-09-04 01:31:40.40 +0100","bug_type":"288","os_version":"iPhone OS 9.3.5 (13G36)"}
{
  "build" : "iPhone OS 9.3.5 (13G36)",
  "product" : "iPad6,4",
  "kernel" : "Darwin Kernel Version 15.6.0: Fri Aug 19 10:37:53 PDT 2016; root:xnu-3248.61.1~1\/RELEASE_ARM64_S8001",
  "tuning" : {

  },
  "incident" : "78A37D23-4900-4D2B-92A3-D73800ED3FBD",
  "crashReporterKey" : "d4cde4fd6f29676b448be194dc1ba43d3ca6fe2f",
  "date" : "2016-09-04 01:31:40.40 +0100",
  "reason" : "com.apple.mobilesafari failed to scene-update after 10.00s\n\nElapsed total CPU time (seconds): 11.060 (user 11.060, system 0.000), 55% CPU \nElapsed application CPU time (seconds): 9.866, 49% CPU\n",
  "frontmostPids" : [
    2614,
    58
  ],
  "exception" : "0x8badf00d",
  "absoluteTime" : 4022534464967,

**Comment by chriseyhorn** [comment] 2016-09-19 20:20
It turns out our crash was related to adding a model to the map that has an image as a texture.  Once the model gets added the browser crashes on iOS.  If you add the same model without the image texture then no crash.

**Comment by drewpotter** [comment] 2016-09-20 17:19
@chriseyhorn thanks for those details. Hopefully Apple will fix this bug. I am waiting for them to get back to me on that bug report.

**Comment by bhoske** [comment] 2016-10-15 07:42
Dear all, I am also face same issue with IOS 10. When I am trying to load WebGL link on Safari of iOS 10 iPad Air 2, it is crashing. I think canvas is getting resized when trying to load texture image. 
Any one have any work around to do these.

**Comment by mramato** [comment] 2018-08-08 14:16
I'm closing this since it's not clear to me that there is a bug or anything actionable still here.  I play with Cesium on my iPad all of the time and haven't had any issues and we've definitely made improvements to how we do things.  If there is still an issue here, please re-open with details.

**Closed by mramato** 2018-08-08 14:16 UTC
Labels: category - graphics, type - bug

**Comment by tyit** [comment] 2019-10-10 01:25
![image](https://user-images.githubusercontent.com/31933126/66531792-a11cd880-eb3f-11e9-976c-23642f998f3e.png)

Hello, I have the same problem.
