### ISSUE TITLE
Cardboard demo has missing terrain tiles

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6795] opened 2018-07-11 20:10 UTC
![vr-log](https://user-images.githubusercontent.com/915398/42596665-72ed36b2-8524-11e8-8754-3c7ed442a574.jpg)

This seems to have been introduced with log depth and specifically this commit: https://github.com/AnalyticalGraphicsInc/cesium/commit/d681755611f2fc47f28e33db61a9ec0583a4abe3

`viewer.scene.logarithmicDepthBuffer = false;` does not fix it, so it might be not be caused by log depth itself but possibly other changes surrounding it.

@bagnell could you check this out?

**Comment by mramato** [comment] 2018-07-11 21:20
This is a dupe of #6612, there are some links to potential fixes there, so we should probably have a look.

**Closed by mramato** 2018-07-11 21:20 UTC
Labels: priority - high, type - bug
