### ISSUE TITLE
Cesium.Color has alpha display problems in Firefox 50 Windows/Mac/Linux

### ISSUE THREAD

**Issue by neutrino84** [AnalyticalGraphicsInc/cesium#4718] opened 2016-12-05 18:15 UTC
![firefoxcesiumcoloralphaproblem](https://cloud.githubusercontent.com/assets/619688/20896304/2560ca6c-baeb-11e6-8948-4ac4104e5934.jpg)

Latest version of Firefox 50.02 and Latest version of Chrome were used to generate these results. I also tested Firefox 51.0b which has the same problem as 50.02.

Firefox 49.x does not have this problem, **but I haven't noticed any issues in any other WebGL applications using Firefox 50 and 51**.

The polygons are drawn using Entity and PolygonGraphics objects.

When alpha is set to 1.0, they both display correctly.
When alpha is set to 0.1, Firefox seems to apply the color incorrectly (maybe additively)

Happens on all platforms.

Maybe related to ticket #4704

**Comment by hpinkos** [comment] 2016-12-05 19:57
Thanks @neutrino84 
This is a duplicate of #4658 so I'm going to close this issue and link that one to the information you posted

**Closed by hpinkos** 2016-12-05 19:57 UTC

**Comment by pjcozzi** [comment] 2016-12-18 14:13
@neutrino84 thanks again for the report, this should be fixed now via #4762. It will be in Cesium 1.29 on January 2.
