### ISSUE TITLE
scene.click() does not work on latest Chrome in Windows 7

### ISSUE THREAD

**Issue by andreabadesso** [AnalyticalGraphicsInc/cesium#3713] opened 2016-03-16 19:27 UTC
You can reproduce it on every demo on cesium website, like this one:

http://shinsai.mapping.jp/index_en.html

It works on Opera and Firefox

Google Chrome Version: '49.0.2623.87 m'

scene.click with the click position returns undefined

**Comment by hpinkos** [comment] 2016-03-16 19:43
Hello @andreabadesso 
Do you mean `scene.pick`?  `scene.click` is not a function
I'm not able to reproduce this problem.  Try clearing your cache, that can sometimes create unusual side effects.

I'm going to close this issue.  If you are still experiencing issues, please post in our forum and I'll try to help.
https://groups.google.com/forum/?hl=en#!forum/cesium-dev

Thanks!

-Hannah

**Closed by hpinkos** 2016-03-16 19:43 UTC
