### ISSUE TITLE
The moveEnd event raised by the camera delayed.

### ISSUE THREAD

**Issue by ZacBrownBand** [AnalyticalGraphicsInc/cesium#2950] opened 2015-08-19 16:07 UTC
When a user drags and lets go of the 3d globe, there is a moveStart event when the camera begins to move. If the user stops moving the mouse before releasing, the translation inertia is not used and moveEnd event is fired as expected. If the user lets go of the mouse while the camera is moving, the inertia keeps the camera's position moving. The moveEnd event is not fired for a delayed time as the camera continues to move just a smaller and smaller rate. 

Possible cause / solution: 
In the ScreenSpaceCameraController it seems like the decay method has no lower bound on its return causing the camera do continue doing infinitely small translations before coming to a stop and raising the moveEnd event.

**Comment by pjcozzi** [comment] 2015-08-19 16:11
Thanks for the report @ZacBrownBand.  I believe this is a duplicate of #2839.  Do you agree?

**Comment by ZacBrownBand** [comment] 2015-08-19 16:21
@pjcozzi Yes, that is the same issue. I was unable to find that one while looking for open issues. Feel free to close this one.

**Comment by pjcozzi** [comment] 2015-08-19 16:27
OK, thanks!

**Closed by pjcozzi** 2015-08-19 16:27 UTC
