### ISSUE TITLE
Imagery Layers Manipulation check boxes get out of sync

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2343] opened 2014-12-23 14:54 UTC
For example, in the screenshot below, `United States GOES Infrared` is checked, but is not visible:

![image](https://cloud.githubusercontent.com/assets/782098/5538939/1d1dfca6-8a89-11e4-9aae-d9715785e93d.png)

Local link: http://localhost:8080/Apps/Sandcastle/index.html?src=Imagery%20Layers%20Manipulation.html&label=Showcases

Perhaps this is a Chrome bug.  Firefox is OK.

**Comment by emackey** [comment] 2015-01-21 19:48
The behavior I'm seeing (in Google Chrome stable 39 & 40) is that clicking on one of the lower checkboxes fires the event, updates the map, but does not update the actual graphic of the checkmark itself, so long as the checkbox retains input focus.  The checkmark is then "out of sync" until the input focus moves elsewhere (by clicking in the blank area alongside the toolbar, or in a different window.  Note that clicking the Cesium globe does not change input focus).

Here's a reduced version.  Load the [Hello World Sandcastle](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases) and switch to the "HTML Body & CSS" tab.  Paste in the following CSS and body:

```
<style>
    @import url(../templates/bucket.css);
    #toolbar {
        background: rgba(42, 42, 42, 0.8);
        padding: 4px;
        border-radius: 4px;
    }
    #toolbar input {
        vertical-align: middle;
        padding-top: 2px;
        padding-bottom: 2px;
    }
    #toolbar table tr {
        transform: translateY(0);
        transition: transform 0.4s ease-out;
    }
</style>
<div id="cesiumContainer" class="fullSize"></div>
<div id="loadingOverlay"><h1>Loading...</h1></div>
<div id="toolbar">
<table><tbody>
    <tr>
        <td><input type="checkbox"> The top 3 work.</td>
    </tr>
    <tr>
        <td><input type="checkbox"></td>
    </tr>
    <tr>
        <td><input type="checkbox"></td>
    </tr>
    <tr>
        <td><input type="checkbox"> This one is broken</td>
    </tr>
    <tr>
        <td><input type="checkbox"> and following ones too.</td>
    </tr>
</tbody></table>
</div>
```

Run this example and try clicking one of the bottom checkmarks.  Note the graphic does not update immediately, it waits for the input focus to change.

Note that I can't turn off Cesium from this reduced example, so I think WebGL or at least a canvas is required to be behind the buggy checkboxes.  Also, the "translateY" in the CSS plays a key role here, the bug won't manifest without that either.  I also tried replacing the table with a stack of divs, but the problem went away then too.

**Comment by pjcozzi** [comment] 2015-10-08 00:58
@mramato is this worth @ggetz looking at during the code sprint?

**Comment by mramato** [comment] 2015-10-08 01:03
Sure, should be a good first issue.

**Comment by emackey** [comment] 2015-10-09 13:46
I suspect a browser bug here.  Note my reduced example above is just DOM elements & style in front of the Hello World globe.  There is no JS or KO interacting with the offending checkbox elements.  Yet, the canvas and the CSS transforms are still required.  Would be good to reduce-away the Cesium globe and leave just a canvas element (with or without a running WebGL context?), and see if a Chromium bug can be filed.

**Comment by emackey** [comment] 2015-10-09 13:49
Er, actually I'm not able to reproduce this at all in Chrome 45.  Maybe it's fixed.

**Comment by hpinkos** [comment] 2015-10-14 18:59
I can't reproduce this either.  I'm going to close the issue.

**Closed by hpinkos** 2015-10-14 18:59 UTC
Labels: bug
