### ISSUE TITLE
CI zip file broken

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6030] opened 2017-12-05 20:20 UTC
We used to be able to get the zip file from travis, but now it returns a 404

@ggetz @mramato

**Comment by mramato** [comment] 2017-12-05 20:33
The problem is that `yargs` 9.0.0 and later enable the `--version` option by default, which prints the version of the module and exits.  This means that the `npm run deploy-set-version -- --version $TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER` command is effectively a no-op so the resulting url is no longer correct.

There are two ways to fix this.

1. Change `--version` to something like, like `--build` and update the gulp task accordingly. 
2. Disable the automatic version handling in `yargs` at the top of the gulpfile and `--version` should start working again.

**Comment by hpinkos** [comment] 2017-12-05 20:35
@ggetz do you have time to take a look at this?

**Comment by ggetz** [comment] 2017-12-05 21:11
Fixed with option 1 in #6031

**Closed** 2017-12-05 21:29 UTC
Labels: category - tooling, type - bug
