### ISSUE TITLE
geojson memory release

### ISSUE THREAD

**Issue by newnewplayer** [AnalyticalGraphicsInc/cesium#6009] opened 2017-11-29 10:22 UTC
![image](https://user-images.githubusercontent.com/31023652/33370351-3c4f4cc8-d532-11e7-821e-31c048a18514.png)
![image](https://user-images.githubusercontent.com/31023652/33370362-43336e66-d532-11e7-9ead-384830f5a6c6.png)
meomery not release

**Comment by hpinkos** [comment] 2017-12-01 19:35
Thanks @newnewplayer.  I'm closing this a duplicate of #5662

**Closed by hpinkos** 2017-12-01 19:35 UTC
