### ISSUE TITLE
Google Earth Enterprise example not working

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7756] opened 2019-04-18 13:02 UTC
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Google%20Earth%20Enterprise.html

It looks like neither the terrain or imagery are loading.   @tfili any ideas?  Is the data server not up anymore?

**Comment by mramato** [comment] 2019-04-18 23:47
Duplicate of #6589 (which you also wrote :smile:)

**Closed by mramato** 2019-04-18 23:47 UTC
Labels: category - sandcastle, category - terrain and imagery, priority - next release, type - bug
