### ISSUE TITLE
Sun shadow disappears in 2D view

### ISSUE THREAD

**Issue by craigp1231** [AnalyticalGraphicsInc/cesium#6303] opened 2018-03-03 10:30 UTC
When in 2D mode the suns shadow disappears when translating in longitude.

If I center the display on the US, the suns shadow is visible
![image](https://user-images.githubusercontent.com/4073362/36933242-909b0148-1ecd-11e8-9b47-51f0a480951a.png)

If I center the display on the UK, the suns shadow disappears
![image](https://user-images.githubusercontent.com/4073362/36933254-bf35ef40-1ecd-11e8-9e65-2649f88e83ff.png)

I would expect the suns shadow to be visible wherever the display is centered.

Kind Regards

Craig

**Comment by hpinkos** [comment] 2018-03-03 14:46
Thanks @craigp1231, this is a known issue.  I'm going to close this as a duplicate of #4122.  I'll make a comment in #4122 so we can notify you when we have a chance to fix this

**Closed by hpinkos** 2018-03-03 14:46 UTC
