### ISSUE TITLE
Polygon entity blinking when updating its color on mouseover

### ISSUE THREAD

**Issue by jeremiebailleul** [AnalyticalGraphicsInc/cesium#8365] opened 2019-11-06 09:49 UTC
[Here](https://sandcastle.cesium.com/#c=jVhrc9vGFf0rqL6ImrDQvh+25KmrKrVn5Mi14vRD5MnAJGSiBQENAMpVMv7vPQvuXYEMW0XfAJy9r3PuvUs9FF32UJVfyy47z5rya3ZR9tVmnf80vpsdL8bHi7YZiqopu+OTl7fNbfOAU/dt/filbfqr4rHsOE7/fNtk+Pv5zyJXXGulrFBSMi3MPFM2F45z4zWXmlk3z0aUtI4rroyS3AtCaeuVZIZ7STBuOVdMM6U05xEmmNbScmNhhGBCWaM9U05oSzAufTDJrJIRxpTVTnhulJfJmsJhJbhxJjpl3iunA9ZKPoFZYY2VzFuCcQczsOqcUwTTTlrrhWHcRxgcOmW8ENYbsiaZYFIwy20MjWlvrREabp1yhNKaM8E1E8knkuYMeWjzVFztGLJ2SkgqG7M46b1kXCtD1rQK6ShnrFGUgZRChzycfIJxqWARnpwgWODKWFSAKeJKGSY9opXaC6ouggBLmmsR0trCANLSwYb2xJULtMK1clYnmFXKeQEeCCaksYjMMu1UgmnmuBNSG05OhQOd0gqQ/4SSzmtwI1NoSiN6zz0D855ggoNp5qwJJ0eYYQJUSjAlRLLGGcMTS4SiChKRQ5Yhe6LKG7wKZxmJ7Zk++DR/aprx9FhK70Z9bZkwCuqxoS7bPKS3AprjeMWFpjy0YMIoC2RUCWCKhaNwbhOv0BXYNhJRu2TNoJjM4hUjp2g0SEyDNkswlBfyRN1DfyZpeo8+tExYcmoU4rfoBrBB9EtphAGJFgaTNdhzaFeIKlmD2iBGiywoU63AK4oeBG8TLPQm2BWKUHBvDWh1IJZQaGUumdP4GmFKIEcvALIqRQaFeeOBJWNSo3NBrvJJcFo740GBRNkTCgLT0JjHgIkwZGSRPFpEcYoMksDMko4nXWowajCotmX8Q7R/um0+HR67YnfsSsNcGKcsFE3EJFFBDmtmlP3WIxSO+WohZsUFoZSAO6PDGN2iMF1QZA+laYypCGNhfunQopZggmFYYKQaSF8TDC6gA2clKUMFD3ihMT1pAmIqgDOcQkvoaA1pM4dZCSkbygCNjUpClWibCINsUGxMBwZ1R5jDQEcpwYqKbBqchX30G4pgCYaqWkwA1COKG6LFA2YSFGJFcorhIzQXXpK1wLhFah6VIWtYJQg4hOE0wUA6xhEbF0OEhdkWUsCoIp9QKLx5zqSJqvXjTEMWhptE1TOM7kwQY7DuPPgxWDWRCxQgkIUeskamCLVBqdG7xhIKXrEdfNhtFKGCS8+wRzgNEPRsmBbhQxIT8sfWBTtIJC1n48LQNrTqgVIuEAtJEShUA/t1TDiCDNZX2MrOmTSgLQYWlitzcfRKi7xNmKeMY51S84UaYa9hPUcaLFa5wRKHBMe+HcPHfMLdAuLCO/L5TMlCgUP7ocYHOlDudSBmv4HmHG4ndhw9oz2MCUxEJCFJSyghQ71kuD7QvQETMyw/q3S8q8hQJPSRBuWCLkgYMpAhFOWMoBEosfccmpCBwHSRQnNgPYFPQZqDAsEgygevPK0jFloIE9qkO8EfyIJkd3q6XV0MtyxcvsJFzRInUBSmqIISaKRgWiJOBCqwTMk/Bh8ixzWOE3XoA0gbGw0dSdl4XHu0xGWITMEKVsB4BaJxjiqEPoOW441qROECgesIZ+me4RyKg7Fs06504V7kce9EFZhIMMhX4nrAiTRcC6AzE+6ihpFAsSOB8Ao6otCeK8bOQK+DjPogo90b9Xxv1O89y2AhnF+Wd8WmHi7aug13+Hh/Hx/zi+sPP3x/df3Pyw9/vfp4mX+thtXr+n5VzFjuTuL5VftQduXy4Pn3r68uf/z44R8fr9/eHDh+22yDz+/a7rJYrGZ3m2YxVG2TzcYP821yb5tl+Z+T7LfYQ0E2KfEfinUJr8fjw3H2XTw5HsETP3n5dIDy/1sxFDftpluUu79ZLjb90K6fvs6Sh5OXE9/j2wMhL9q2W1ZNMZR9qvVO6BkFUjZDNTzuOr8c380myPBXLV9M8vwuO/4lGh5TnToZk53vnr4ri2HTlW9h5Fls8jJxuAeJJl5Mw36/fff3rrhfVYt+P/7wt6rKrugWq8dDB9/QxxmRUHQoYFU0Mr/rwEb5pSvL/nXXFY/TCp/sxx/+1vjSVUX9YkfUu7hvJ0/P37Yi3Mtvoo98ZKoq+7xYLmdb2khR35K0xp+6+TKd2qJ/by0ciC7jJujKh6rd9G+2LbSVQGrsVdEs6/3f1TcLlKO5uS8W5eUDAnqzBc1iEP2ibMp8UcBAHzxFG3lfDm+b+83wetRqEu1sDc9rmBklOumUavHvcnn9+V/lYoD/HePhWzqHAi3ft30VjFE9Fki6rcu8br/Mpoboe3WXEdmgqWrK5S5sp10C+GCZsj+dn2ebJlrYOTNyeehMHjnJSSjIbaqUlxNpTGQxCS6vloeMTGfgxMjhwM/3LZKgAgPf5v+L6R8f78v83fXHm8tf3l3/dBn/kbJL+xrNFLgO/32hVlyW/RB6pgqd+3+bbDZee8yB1S12LyD4HcSo/9quQnDR/ISEVVmgVb9kLzI2n9ZyWKyyFMe7YljlQ/sB0KKBf6Wnbd21dR3O5ywVaGyfo/nRWT881uWr7fu/VOv7thuyTVfP8vx0KNf3dZgRp583qPOQL/qxF85O6dDZsnrAaD2/Pdr799TtUbaoi77Hl7tNXd9Uv5a3R6/OToHfOVa3Y3LXoBXDMkBW/NXV9mWe52enePz9qaFt689FN7H4Xw) is a sandcastle of my problem.

**Expected behaviour:** I have three groups of polygons, and I want to add each group to the viewer as a `CustomDataSource`, and instanciate each polygon as entities in these dataSources. When hovering a polygon, I want to change the polygon color and reset the color of the previous hovered polygon (if there was one).

**Actual behaviour:** In the provided example, as mouse moves inside the polygon on the right side, it starts flickering, while it works fine on other polygons. I then noticed that if I add another polygon entity in the same dataSource (uncomment line 15 to do so), it doesn't bug anymore. It seems like it bugs out only when having a single entity in the dataSource. I've logged the pickedObject in the console and when moving the mouse over the "bugged" polygon, `undefined` value is sometimes returned by `viewer.scene.pick` method instead of the expected entity.
Have I messed something up in this code ?

**Browser:** Tested on Chrome/Firefox
**Operating System:** Tested on Linux/Windows

Thank you in advance for your help ;)

**NB:** In case the following information is relevant : I've seen posts suggesting that color changing on hover events like this example can be done using a `CallbackProperty`, but I can not do it this way because I've got a use case where I have up to 2320 polygons and the scene won't even load when instanciating each entity with a `CallbackProperty` for the color.

**Comment by OmarShehata** [comment] 2019-11-06 19:06
The picking is actually working correctly - the problem is that when you update an entity, this update happens asynchronously. When the entity disappears for a few frames, the picking result becomes undefined (because there's nothing rendered). 

Ideally you could just say "I want this entity to be update synchronously" for cases when it won't update every frame, but when it does update it'll be on user interaction and you'd want it to be synchronous. You can read a bit more on this here: https://github.com/AnalyticalGraphicsInc/cesium/issues/7934#issuecomment-501304278

**Comment by jeremiebailleul** [comment] 2019-11-07 09:27
Hello @OmarShehata and thank you for your answer.
My bad for incriminating the picking, I misunderstood the problem !

I've read #7934 and I understand the following available solutions:
- using a `CallbackProperty` to make the entity dynamic but it would result in poor perfs for my use case of thousands of polygons
- or use the primitives directly with geometryInstances as said in [this comment](https://github.com/AnalyticalGraphicsInc/cesium/issues/7934#issuecomment-536052263)

Nevertheless, I can't help wondering how come there isn't any blinking when I have several entities in the `EntityCollection` of the `CustomDataSource`, but there is blinking only when having a single polygon entity.

See in [this simpler sandcastle](https://sandcastle.cesium.com/#c=hVVtc9o4EP4rOr7UzHDCyO8pZJpy3LUzScmFpvchZDqKLWL1hOSRZDJcJ//9JL8Qm9DWX8CrZ5/dfXZX3mEJdpQ8EQlmgJMnMCeKllv4pbI5b9LqdS64xpQT+Wb4ds0BAGu+M46FYPtHwZVxvavM4O53BD3fQ2EShbEbBFESoBHwI4giL0Fu7MWx63n+CFic57uu64VeMomT2G9gyOB8FPmB79UoZJxQggKUTMxPg4qCwDcWPw4RatkSN4g9P3IDP2lxsRdGE9+NPBehuIb5sYeiOHFDE3WCwgZn8ojCEIVhGIUN36+ruB/VRY/Hd+4IuPdrfm/UqaXJyAaXTM8FE1bZRtXqFc6XN5/+vFz+s7h5f3m7gE9U5xesyLHjwtjqa/1zsSOSZCf9ry8uF59vb/6+XX5cnXB/1Z4/sMYrUcqU9Hs8L5UW25dTZ1il37rBjZALnObOpuSppoIDJxVCZpRjTdQQfK+rt5EI11Tv++yLyuY0KPs0xGdd1HVt+0viIqep6sLtk1MisUzz/SmnD+2h0xaEpcmMYu7BjTSVkUdJiLqQEu97qQ9H/ShbY5UUs7Ne214wz8P6/3MtUKeWjrawEoESBXGWObUiFl851SsGswO6Rr1mGR4mqJmAWsYXK+YZO17WVWrq5KsCp2SxM5E/1CCniapSwglMsSFQlr/hgIroj7wo9UXV3UObna2JvDU0VYtfmlzQ9F+SLR++kVSb+D1ye3bwM0pk10JRS9YMJKAb0HbJaGyuElN8h294GKcW3D2FNAO/zWZ9SXoeVUv6HrARF7bdBbPeVr09mrQut4EesXXQz80wAMIUOU67T2OTLnlT8KuEe9hT6Xan8RfpHqKcSNQ28Xn0o2H5vC8IvFrerhZfr5ZfFs0A9idnaxbNjov9KrQrmhGl7T5Ru9E/XUCnup7DE9ep3/8o2O9Bu5tCUpNcQ98RLifYrPEjOANuZ4sLqtMcHPK4wjqHWtwYKOYmvh90V14Kxqw/dA8CVUs6GA2mSu8ZOa/t7+i2EFKDUjIHwrEm24LZ+2P8UJrZ0DBV1TpNx63TNKM7QLPZenD02VwPQMqwUuZkUzK2ov+R9eB8Ojb4nhsTVXFL01uG9xaST84vayOEcDo2r6+9tBDsAcsO4/8) how it blinks on hover when I declared only one array of coordinates to be translated as an entity, but if you uncomment line 5 and add another polygon with [0,0] coordinates, it doesn't blink anymore.

![GIF](https://s5.gifyu.com/images/Peek-07-11-2019-10-22.gif)

**Comment by jeremiebailleul** [comment] 2019-11-13 11:04
I edited the title so it matches the actual problem and so it doesn't incriminate the picking !

If you have any hint on why this behaviour is happening when the entity is declared alone, but not happening if I declare several entities in the dataSource ?

Maybe some collection is dropped in first case when removing/recreating the entity and not in the second case or something like that.

**Comment by OmarShehata** [comment] 2019-12-14 19:20
@jeremiebailleul I'm closing this since the blinking is expected behavior as explained in my earlier comment. The fact it doesn't happen in all situations is a good question, but I think what would really solve this problem for you is being able to control when entities are sync/async, which is the feature request here: https://github.com/AnalyticalGraphicsInc/cesium/issues/5127

Feel free to 👍 that to express your interest in seeing that feature in the engine.

**Closed by OmarShehata** 2019-12-14 19:20 UTC

**Comment by Akbalder** [comment] 2020-02-21 08:46
I think that I found why the blinking happen only on some situations.

When we are updating a polygon, we are removing it from the batch before inserting it again.

GeometryVisualizer.js:
```javascript 
            //If in a single update, an entity gets removed and a new instance
            //re-added with the same id, the updater no longer tracks the
            //correct entity, we need to both remove the old one and
            //add the new one, which is done by pushing the entity
            //onto the removed/added lists.
            if (updaterSet.entity === entity) {
                updaterSet.forEach(function(updater) {
                    that._removeUpdater(updater);
                    that._insertUpdaterIntoBatch(time, updater);
                });
            } else {
````
If the polygon is alone in a batch, the batch is destroyed when removing the updater. The function _insertUpdaterIntoBatch will have to create a new batch.

StaticGroundGeometryPerMaterialBatch.js:
```javascript
    StaticGroundGeometryPerMaterialBatch.prototype.remove = function(updater) {
        var items = this._items;
        var length = items.length;
        for (var i = length - 1; i >= 0; i--) {
            var item = items[i];
            if (item.remove(updater)) {
                if (item.updaters.length === 0) {
                    items.splice(i, 1);
                    item.destroy();
                }
                break;
            }
        }
    };
````
Not destroying the batch when are updating an entity seems to solve the issue.
The color update is still a bit slow but the polygon doesn't disappear before being displayed with its new color.

**Comment by OmarShehata** [comment] 2020-02-21 14:54
Here is the [recommended way of changing a polygon's color](https://sandcastle.cesium.com/index.html#c=pVVtb9owEP4rLh/aoDFTWk2VBlSrKFIrtaIafdE0pslNDvBq7Mh2UmUV/32XF0OcQr/MEig5P3f33GtSpknK4RU0GRIJr2QEhicr+ljIgqOweB0paRmXoI/a/ZmcyXkiQ8uVJKEGZuFOiWyhZBArw3Ox6ZBQCaXb5G0mCZ4UvawQqDkTd1rFoG3m+xvl+NsGJMi95fpNXVqYb1hgQjyz8GWj7EgGGxr50WATLUlcUh5Ly525yte6Q+ZMGCgjdew9PDouc0Yhf+dgKIuioOalgpOvddf5WXLQTIfLDK+26fIxLlqENAPfAtcVW5eiHQEhTRfYOo/FL9YmbdriE5OndK7V6hIWGsBcaM2y4Gdp+nOv94Ued8jpGf43RCc10fFZITqti04KUe+9CNVn8le74zUAfbq6vh+Xmf9fvuQTOdlF2smbzJ28Sd/Je3vkuwP5Pr50YeTtY0BAaCEqy9N34iWTkWiO3hTjBjmNWQjjFBvsqgQFVcuZECTQkKEBk7uobFAD9lrGib0om37T/SuVwgrNeMMY8/AFosnzH2S17ebSdH630cIOj+6qPnWtxufEVSOCOa6FKKjba5PDQ88B5RHlZlqlgBwMh8TqBLyx7HbJgyyzRJjMSKwh5SoxIsORWSwF/nLdYt5qU5DIze1mWeRn++RnHmNtMOvvg9Ypl4T3Q5XmCy6ZGFVj17iur5cd2m5YvQb6Mb65mTy5nVQFtM3/wUcFaHtLZ1eOcB+sO/sa7j6Lgd5OHqbj37eTx3Fj5Xvm3vYz8oNs16pdruC+C6faZHuS8lGm+zs1vboVq3wnDi8TWZHtI5V1q9MaGJsJOC/h3/gqVtqSRIuA0q6FVSxwH5nuc4K5tjQ0xfwNuk5pEPGU8Gg4azW+mrMWCQUzBm/miRBT/hdmrfNBF/GemlAs4nIxSUELluWQZe/8phRSSgddfH2vZZXCD5+uWfwH) on mouse over that avoids any flickering. You need to use a ColorMaterialProperty, that has a CallbackProperty for its color value.

This will not mark the entity as dynamic, so it should be efficient to have this on thousands of entities.  This will simply change the color attribute of the underlying primitive. [Here's a version of this implemented in the primitive API](https://sandcastle.cesium.com/index.html#c=jVVtb9owEP4rGV8IUueUVlOnllZDjG6VWlEVSjeVqjLJAd4cO7Idumziv++SYOLwIjUSL/bdPb57njtnSZW3ZPAGyrv0BLx5PdAsjcm42PObYbHsSWEoE6CarYuJmIglRiWSZ3MpboQ2VIRQD/8GMgajMmv1/02Ehw+Lzr1mu3lUruZrL+/cxt2XoDaczJSM76VmhkmhLUj+JHaziu1RZfAfFadF2FeYKwDdVYpm/nMVmT8f2+1P5PjIOz3D7wOmkz2m47PCdLrPdFKY2odNCFtZXlqO2xIw8z/XUsXUOFyAsvT1JJeqmyRAVb4k4/7DqP/j9XrwcNcdlTgrC0iNUWyaIhXnnkNYmENUXOWrbZG6NrLgr3DxXX/y9P1m1G+tz5uI1boZilYhOgQBJFEsRmGWoAmNIt9piXtrsTIGAdWZCBdKCplisjPKNWx1hk0tl/l5q+NebMEbXtDJPfAgf24jhVxqiDDSqBQcTQx6ap5iUWZttDznhZeVl4OggUNoINoUuBmRBRUR356sYYhtKYYJDaG/RPTvpZNfozGkCKDzU9YYRIO5EUlqumHe9v4sFeWfWC4hRpiWFbuYTRb+hmgw/YWJ4el1hdC2iSIgIjtf+WnFjM48K3sEM5z6yHfxWi23rRZsvuD4MTWfqg0s6MoDVNeNTMUmdrhm0N94I8dHhwgbZQmQu8HjsP96Nxj3SyksH25Cmxzssfsqs05EKjZngvKiV+pFBoHX5QpolFXwEFV2BSZVoso9/9npCtQhcTrESlWNq+tA5mAOjqf28Qq1VB0oYN1zj0yYz+UVWB1EirvAAmzvY+T7Lgkjx5SnUL8ifvZvbwdPOfaqJstetV1dPmwJs8NfXZJ9lO/QuYPxflr3sLKLVmP84oDuO7qkYl3jxeFOcX1WjaNGR5uMw1UZ8IXFiVTGSxX3CQkMxAmnmGkwTXEEDQl1cXN0AhvUidgSX72Xk8bW63zSwPuPao2WWcr5kP2FSeOqE6B/LYxLGjExH+CLitMsd1m0r27LTUJIJ8DlbpSRkk+pchD/Aw) to make it clear what's happening under the head. I'd be happy to review a new Sandcastle example that adds this to the list of examples since it's not obvious this is the right way to do it.

**Comment by Akbalder** [comment] 2020-02-24 08:31
Thank you for your help.

The solution using entities and a CallbackProperty is too slow to be used when there are [100 polygons](https://sandcastle.cesium.com/index.html#c=rVZtb9owEP4rLh/asDLz0lWVClSrWqRWakU1+qJpTJObHODV2JHtpMoq/vsuJIE4I90+LBKI+J67e+6x70zMNIk5vIImQyLhlVyA4dGSPq7XvAN//XqhpGVcgj5okbepJPhY0BqX7rSKeQD6tHD0NTALT0qL4D6DeM2pXDX7UzmVs0j6litJMtSdEslcSS9UhqfLpkV8JZRuFkliZLdEoOZMYKYQtE1cnhcp/rYC8dJsqX/Vl67DVyIwIZ6Z/7JxLkh6Gxrpo8FGWpIwozySlhfh8lyrFpkxYSCrtGDv4DFxpjWF9J2DoSwIvFKWHE5Oy6nTZ8FBM+0vEjRt5XIxRbUIqRa+Ba5ytoVEOwpCmkVhq/WuKe2ltXA0dPqED47T78PDjT7ubm501RZ/MXlEZ1otL2GuAcw5HonE+7bl87HbPaYdcojRP5Bep0WOTmin9Z69V7F3Tlz7UdXec+3dv9gxXWb+3mw5x4w+XV3fj7L9/Y+F98rZP9VU74JqJHBBNTq4oO6/gOoV+TK6bBbHZCrTQ2JAgG8hyA5Uv1heMBmI6pCZoH4gJyHzYRRjS1xlIC9vEuODBOozDGDSLHkMasBeyzCy51mbbvp1qWJYYhhnfITcf4Fg/PwTWW37Lwud2jZe2JPBXd5ZRXPwGSl2NYAZDsDAK8drkv19JwHlAeVmkktA9oZDYnUEziBpt8mDzFQiTCYk1BBzFRmRYJPPFwI/qe96QpT6NpIb62a8pc/2l6s81lph1q+DlilnhOuhSvM5l0xc5IOiYi4PxB3exXhxztDX0c3N+KmYonlBW/333tuApjMmd2mER3PVqjtw90kI9Hb8MBn9uB0/jiqXlBPurZ6RW2SztNvZpdEvyslnb40o7ynd3+np7Nv68tmJQ2Mkc7J9pLJqtBoDYxMBZxn8M1+GSlsSaeFR2rawDAXONdN+jlBrS32z7r9Bu3AaBDwmPBhOG5X/B9MG8QUzBi2zSIgJ/wXTxtmgjXjHTSgWcDkfx6AFS1LIont2ky1SSgdtfP3TyyqFV7UuRfwN). We were able to display a lot more entities without the CallbackProperty.

The solution with the primitive API seems to work fast enough for about 2000 polygons.

**Comment by mramato** [comment] 2020-02-25 18:25
@OmarShehata FYI, the primitive/Entity versions you link to above are not doing the same thing.  The primitive one does not confirm the Polygon to terrain, while the Entity one does.  You need to use `GroundPrimitive` to have the polygon on terrain. That is most likely the main reason for the performance difference.  I'm pretty sure there is also a performance bug in the Entity API that I'm looking into as well but may be something different.

**Comment by mramato** [comment] 2020-02-25 19:50
Just opened #8630 which greatly improves performance in the Entity API for this use case and should scale to thousands of polygons.
