### ISSUE TITLE
when tilt camera slanted into the ground

### ISSUE THREAD

**Issue by gee1m** [AnalyticalGraphicsInc/cesium#6181] opened 2018-02-02 03:02 UTC
when i tilt the camera,camera sometimes slanted into the ground

**Comment by ggetz** [comment] 2018-02-02 14:36
Hi @gee1m, thanks for the report? Can you be more specific about when this occurs and what the problem is? Coul you create a [Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases) showing the issue?

**Comment by SelimAbidin** [comment] 2018-02-04 23:46
The problem occurs before higher level tiles load

[https://www.youtube.com/watch?v=SsX8h2dMn2c](url)

**Comment by ggetz** [comment] 2018-02-05 14:37
Got it, thanks @gee1m and @SelimAbidin. I think this is a duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/5837, so I'll close. Feel free to reopen if you think this is a different issue.

**Closed by ggetz** 2018-02-05 14:37 UTC
