### ISSUE TITLE
Label letters skewing out of alignment when changing terrain provider

### ISSUE THREAD

**Issue by jrafidi** [AnalyticalGraphicsInc/cesium#8419] opened 2019-11-27 14:57 UTC
In the sandcastle linked below, clicking back and forth between "Remove Terrain" and "Add Terrain", while adding back the point with label, can lead to a state where zooming in on the label distorts the letter positions.

Example of the broken state:

![Screen Shot 2019-11-27 at 9 54 17 AM](https://user-images.githubusercontent.com/1316699/69733832-fdda4f80-10fb-11ea-977b-0ac44ce5f7f5.png)

The set of letters skewed appears random, and the skewing gets significantly worse as you zoom in.

Sandcastle example: https://sandcastle.cesium.com/#c=7Vrtc9o4E/9X/OQLZkqFX7F9SToPTWgvcwQyhGun03Q6AgvQc8ZiJJE0vcn//qwsmxpj8nJtevfh/IUX7a5Wq9+ufiu4xty4puSGcOPYSMmNcUIEXS/Ru+w7szHNPp6wVGKaEt5oGX9epQY8knAOX11wdk1jwn8pFKecYEneM57EYy1iNq/Su+bhVarnQWJKUoLmCZsQFJOVXIyJkN05SAqZq4Avkq8J6IAWeLhiNJXvqVz08YQkMDpbp1NJGdgu/FFiBEbySUgqqaREIBzHZi6inhUTVCkaG4dPMJfwDqcumnG2PCVzTogwX9qOg+zID1uG14E3tt9slc2AQ2CjZFk9U5YwXjKtPqLL3z687v/ea22LrugXklzSrwTEbasyyNYygXCf1Jn70Ov3h+/rFd7TWC5Awa0MLwidL+SIzAgn6ZR8M/nr9gA66XfPLz6Ph5/fjoa/D06/WbkrWUyyTdhZvCRfVEgaJwlerkhsSGbMOVuncaPizYxlsWvY3koaAqfipSCczho/yOmqGcbpV4XfZMjpnJZ2/tfKCOr33owr2teESzrd1X239T163b3s9c8G1U2e0SSp3cTX/e7JbxXhCZ7+oQN2AaCl6RyUShm5waljKkw2K9oxFXiSkNMioU6pkFiHbbBeTiAlLoaXZ+Ozd73PZ4M3Z4Oz8Qej3TZijm+EIRck31VYI2QB7A+bFSleAoF+myVznnU62yQH30ncU0l3C0moMvdOyVziNJ5iIROiEvGUzPA6kWPGkgnm5yRdmx9zELXbxasxZsZUQUgnmTAgehOI44RhHgtDEJm5W0UHoK2CA6U46vW72ZorkC6mKzB7CmEwLrKkvoEyY2R1pgAkSwVJyFQJbhciGL8rFcSSqdeFwzU2dmvXE+rXD6xhGeYKP3fTWT10iecKQQ2E2tl70Z7hKU1gl9F8N2N/TKkpIa2CtgcQlyt+25ISqE4Y5zRmXLQgfMntHPbDAGwaHPYEp/OECNj4JDEmRIMP6hdeS7bEWZYntwadKdjdGpiTLK1BIEMKhqKfqlSTefUHq5tZF1gYKctjovAIGOHrGHT1V2gjORiOe78Yl0RKlfi5AmDa0m7l2a19Awl0D4yLpT4H9Ka57Xq4FMAUDyGzC4Xl1vy4a0E9OWoLzHqte8QcOxODl/uE3FxoV+ZTs0bxJj9FHcuykFUjAKiAAwsn1ar+dtTrDZCCRTdZLbBpIb/5RFx/ZWw5ZiZp1uG5Uq0yGD9PgclM12/yghKO+XRxWz9cxcHHuiPMNV86rh/abohCL3A9ywlhI1+6gedZgYM8P/I9Gz7BvoGU7YfID2zPDnw38Jt7tnrr2T9p4Lg28iIHTFkdy9Wz+rbloiAMOx3LsUM/m9YKLAdFgR8EHafjfu+0fmSDNctxLN9zi7U6XoQsJwqC0PP1Wh0IBbJBJAjBpe9eqhWCfSvyfVhBR08KrrgIpra8MLSLCEcdG4Ud14EAOFHz0+6sd0/IAkV2f1YSjOHDmkM9fWo2QDk3/5O7rQ8RJNarFeNSnOfrEjPGe3mWDNOimSk3Mc1mNQNuaBqzG4QToIdmo+hm8lOqCJjIDpGUAfnVU4L/kG1yQYWxSrCEeZeNYu3FwwksND3cImP/Jve/yf38yV0if9qVz302Z591sv9vNa9jgcBThKAz4E4KKuPbVYkInuyMoXFvNOqeDWoMCTliEm+zXUjQBZJshGOIhjC9Z6wvo4IePscxu+Ge9ck2ZYxDGwgbUeJTG4d2ib5mOVZLkx4r+1SLsn2Fe9Q7/Vl1+5zFtf3VP6k3Wiof67dmzWmeGJfAx6HrxhK3M/kiR85xWmQLvEXzZPIjm6W6TaUpXa6XF+VrJSes3f0vSvAS2hp992Q9R+tV7LaOj6Eup0onh+q81M2DbqGyS0DQELLoc57WNicknYOBY7UW67B6LEJvxmWfqTvF+voRdlAEB0bklo/cDHJp/IBeGHW8KGjuzAmH+F41J0BRGDp+jVp+4aJjdrGJ1rHx8VPJNaAHhqnEKYxYh/BylIfg0Hjxgu5wksyhnXUAQ1mZeoWtTYxaYKxtmHlAXxp2s0pD9G1snmPH1fOJzTleLejUTJQtiEJVvX6FaLUWC7Mw29xHcvKJbhYkNfP3IjOU86xzJuQpkZgCgAqeVrmmbu3xoNn6hi9tU9TGkc1m6gJKQQ1Zh9Vrzd19yW2h+/YnO+a03Ef6CeW9/4vjfLLDnfSsuPVwUSxoX5aFjyJ2BTNOEroSjMbo/dvL0EPT0h5nPfyYbcqr7umL4O0hN8Att8lAV3+BBsOdy9NqO+7vGS8dZyU4XuTrHeqb8YLUAxBWwM1vzT/3s6/aW/zhqDt427uHs1Wu4J2HRfffDNer3u2LalZA3wDuz39KKIAn/M1xqOGwlSzZLq6bAov5PEvfel7tWlYQAO+xQmgkwsgNgUH7HddT9N52bTcCOg39A5D60PYdBIza96G9sDvVMrcpE/XzgEkPug/PisJOEPodBzgbnD/I9ewoiEJLcXdoI6CDiOBosqB1sYKOa3ecnWqsc3+Kl9C2oYSxP7rS1Its5U48RmXM4WBSXaf57YTg9IuHzk57g/HZ+MNWSX6Y3W1qjepqdb198EB/VGteIPkv9uMb9ZJjT+3F72oY0UPt9v66+2NuTDcMBjAD7MJR7KL1KNHwflHNb0qij7xBza6px+xt9msWLE39mHvPRat/f5Py/aXs6RX9kVXsL1Swu8d3VT+pYm0Rm2esWE+sVt9VqVRx+tQyGqolfb2WElKsoaO7/ZNk/lukFjGvDkZkya7J5qfPg1bdXw1qqeV27DbMabwtZSon7h7jSTeOv9+Nun9j1DrAid7+YhpjZ55NkeNZiLpJok1llg5aB0dC3ibkldb5L12qYgqNcmJClyzJUhVTItqTNfSOEk2FUMpH7ULpKKbXBo2Prw4q/zi5OtCXSTAyWydZa3t18OqoDfJbagnD6jfz4TXhCb5VIgv7VV9/iRA6asPHXS2pgw7i2u/SSN5TkHRdmm9bpgSuvTLAl+cJ6StOD57sFdO8eddY8fp/

Browser: Chrome 78.0.3904.108

Operating System: Mac OSX

**Comment by lilleyse** [comment] 2019-11-27 15:49
Thanks @jrafidi, I believe this is a duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/7376

**Closed by lilleyse** 2019-11-27 15:49 UTC
