### ISSUE TITLE
Google "Cesium Sandcastle"

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2182] opened 2014-10-07 12:30 UTC
I always get this 404 in the console when I google "Cesium Sandcastle."  Can we work around this?

```
RequestError: Unable to load gallery/3D.html status: 404
```

![image](https://cloud.githubusercontent.com/assets/782098/4542067/885ccdce-4e1d-11e4-9f6b-18239570b74d.png)

**Comment by emackey** [comment] 2015-01-09 15:37
It's sad that Google has cached an invalid URL, and continues to use it as the top search result.  Some possible fixes on our side would be:

  (a) Put in a redirect from "3D" to "3D Models" making it impossible to introduce a future demo named "3D".
  (b) Actually create a Sandcastle demo named simply "3D".
  (c) Show a friendlier demo-not-found error, and preset the catalog of demos.
  (d) Hide the demo-not-found error, and redirect to Hello World.

**Comment by shunter** [comment] 2015-01-09 15:42
We should be able to purge the URL from Google Webmaster Tools.  Does anyone have access to that?  (we can take offline if someone does have access)

**Comment by emackey** [comment] 2015-01-09 15:49
I do have access to Webmaster Tools for cesiumjs.org.  Stop by and we'll take a look...

**Comment by emackey** [comment] 2015-01-09 19:26
This appears to be fixed now.  Google has stopped serving the "bad" link, and unfortunately Sandcastle itself is no longer the top result, the demo page and our home page are now the top 2 results  Still that's "good enough" and next time Google re-indexes it should pick up the corrected link.  Several other search engines (Bing, Yahoo, DuckDuckGo) already have the correct link as the top result, without any manual intervention.

**Comment by shunter** [comment] 2016-05-19 21:31
FYI this problem is back again.  Top Google result for Cesium Sandcastle is the same broken link as before.  Not sure why previous efforts didn't fix it (or whether it regressed at some later point)

**Comment by hpinkos** [comment] 2017-03-27 18:02
This is fixed locally but still broken on the Cesium website

**Comment by emackey** [comment] 2017-03-27 18:51
Looks like the fix included a specific test for `if (error.status === 404)` and thus only works with `404` errors.  The deployed site is currently returning a `403` and so the fix doesn't apply.

@hpinkos maybe instead of bool `notFound` we could have a "deferedLoadError" message or something, and handle all errors the way we handle 404s now.

**Comment by hpinkos** [comment] 2017-03-27 19:03
Good idea @emackey!

**Comment by pjcozzi** [comment] 2017-03-27 23:35
@rahwang this could be a good one for you.  CC @lilleyse

**Comment by hpinkos** [comment] 2017-05-03 21:53
Confirmed this is fixed

**Closed by hpinkos** 2017-05-03 21:53 UTC
Labels: beginner, bug, enhancement
