### ISSUE TITLE
Why do I follow the official website example in the browser 3D tiles does not appear properly? Who can help me? Thank you very much.

### ISSUE THREAD

**Issue by jingyebuchen** [AnalyticalGraphicsInc/cesium#8084] opened 2019-08-19 07:05 UTC
![image](https://user-images.githubusercontent.com/41276803/63245443-c9e8c600-c292-11e9-9b49-12d8c9a2506f.png)

**Comment by jingyebuchen** [comment] 2019-08-19 07:54
I found it to be the reason for Adding Cesium World Terrain. If you don't add this, you can show it. Can someone guide me? thank you very much

**Comment by OmarShehata** [comment] 2019-08-19 12:45
Welcome to Cesium @jingyebuchen! Thanks for reporting this. One thing is that when adding your building model to Cesium ion, you need to select a height reference of "Cesium World Terrain" for it to correctly clamp to the underlying terrain, which the tutorial doesn't mention.

But it looks like the issue is a recent update to Cesium ion makes it ignore setting the correct height related to the ground on small models. I opened an issue for it here and closing this one, since it's not a CesiumJS bug: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/210

I'll update the linked issue when a fix is deployed. In the future, you can ask general questions [in the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev), that way we can keep specific bug reports and feature requests on GitHub.

**Closed by OmarShehata** 2019-08-19 12:45 UTC

**Comment by jingyebuchen** [comment] 2019-08-19 13:35
@OmarShehata Thank you for taking the precious time to guide me to this beginner. I have to say that Cesium is very attractive to me. When I find the problem, I can't wait to solve it. So I have asked questions in many places, I will pay attention to the problem at any time. Thanks again, I am very grateful to ask questions that are more standardized in the future.
