### ISSUE TITLE
Clustered labels do not reappear after clustering

### ISSUE THREAD

**Issue by ollazarev** [AnalyticalGraphicsInc/cesium#6897] opened 2018-08-08 14:42 UTC
Look, please, at this example: https://codepen.io/ollazarev/pen/rrQaee

After clustering, only the points appear again, but the labels after the clustering disappear forever.

After camera zoom, in addition to the points, the following cities should appear: Philadelphia, Canada, New York, Toronto.

A piece of code from this example:
```javascript
let dataSource = new Cesium.CustomDataSource('dataSource');
dataSource.clustering = new Cesium.EntityCluster({
  pixelRange: 80,
  enabled: true,
  clusterBillboards: true,
  clusterLabels: true,
  clusterPoints: true,
});
let entity = new Cesium.Entity({
  position : Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222),
  label: {
    text: 'Philadelphia',
    pixelOffset: new Cesium.Cartesian2(7, 0),
    horizontalOrigin: Cesium.HorizontalOrigin.LEFT
  },
  point: {
    pixelSize: 5,
  }
});
dataSource.entities.add(entity);
viewer.dataSources.add(dataSource);
```

**Comment by hpinkos** [comment] 2018-08-08 16:40
Thanks @ollazarev, I was able to reproduce the bug

**Comment by hpinkos** [comment] 2018-08-08 17:12
Actually @ollazarev, it looks like this is a duplicate issue of #6087.  I'm going to close this one, but I'll add a link in that issue to this one so we can notify you when the bug is fixed.  Thanks again for including the code example!  That made this really easy to reproduce

**Closed by hpinkos** 2018-08-08 17:12 UTC
Labels: category - data sources, type - bug
