### ISSUE TITLE
buggy rendering in Chrome

### ISSUE THREAD

**Issue by alexander-entin** [AnalyticalGraphicsInc/cesium#2619] opened 2015-04-02 18:03 UTC
Run below code. 
It will display a ripped polygon briefly.
Rotate the camera to see the bug again.
It is less visible w/o `depthTestAgainstTerrain` but still there.
Polylines are affected too.
In a "real" application it never goes to normal for some reason.

Introduced in 1.8.
Tested in Chrome 41.0.2272.118
Windows 8.1
````
var C = Cesium
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.scene.globe.depthTestAgainstTerrain = true

viewer.entities.add({
			polygon: {
				hierarchy: C.Cartesian3.fromDegreesArray([-122.43519235894726, 37.81387973942226, -122.43476820785477, 37.811148802628516, -122.43680077372593, 37.81008806320625, -122.437225, 37.812819])
			  , height: 1
		      //, granularity: 0.001
			  , material: C.Color.fromAlpha(C.Color.GREEN, 0.2)
			  , outline: true
			  , outlineColor: C.Color.WHITE
			}
		})

viewer.zoomTo(viewer.entities)
````

**Comment by mramato** [comment] 2015-04-02 18:20
Thanks for the report and sample code (always makes things so much easier).  Both of these problems have actually been around forever, so I'm not sure what might have changed to cause them to crop up in your particular use case.  The good news is they will be fixed as part of the polygons on terrain feature that will be part of 1.9 (this particular bug is already fixed in the `globe-depth` branch but I have a feeling you are setting height to 1 as a workaround and what you really want is it to be 0).

In either case, we can leave this open until the issue is fixed in `master`.  Thanks again.

**Comment by alexander-entin** [comment] 2015-04-02 18:30
Just FUI. 
This particular example works correctly in 1.7.1 in all three major browsers (height helps).
Only Chrome is affected in 1.8.

**Comment by alexander-entin** [comment] 2015-04-21 16:51
I believe this is related. 

Open this [link](http://raceqs.com/test/gltf/_/test.htm#J22,1,boat,1,CHP,0,). Rotate the model. Leave it alone for a few seconds. You'll see "J/22" logo appear on the sail. Rotate again. Logo disappears. And reappears after some time standing still. The same in all Chrome, FF and IE.

What is common with the above? While there is something changing, something to compute, some parts are not rendered properly. And in my "real" application there is always something changing and thus some parts are _NEVER_ rendered properly.

**Comment by alexander-entin** [comment] 2015-04-21 17:00
Just an observation: In the above example the logo reappears at the same time as "Image courtesy of NASA" disappears from  credits.

**Comment by alexander-entin** [comment] 2015-05-05 09:14
Still there in Cesium 1.9 and Chrome 42-44

**Comment by mramato** [comment] 2015-06-08 18:36
@alexander-entin, is this still happening in 1.10?

**Comment by mramato** [comment] 2015-06-08 18:59
I downloaded the boat and chp bgltfs from your link and loaded them in a Sandcastle demo.  I'm unable to get the problem to happen in 1.10.  Since you're using bgltf, I assume your demo is also using 1.10?  I noticed in your demo that the logo doesn't actually completely disappear, it seems to just disappear into the sail, which looks like a potential z-fighting issue within the model.

Can you get the problem to happen in Sandcastle with the below code (or a tweaked version of it)?

```javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
    infoBox : false,
    selectionIndicator : false
});

var position = Cesium.Cartesian3.fromDegrees(-12.0744619, 44.0503706, 0);
var heading = Cesium.Math.toRadians(135);
var pitch = 0;
var roll = 0;
var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, heading, pitch, roll);

var chp= viewer.entities.add({
    position : position,
    orientation : orientation,
    model : {
        uri : '../../SampleData/CHP.bgltf'
    }
});
var boat = viewer.entities.add({
    position : position,
    orientation : orientation,
    model : {
        uri : '../../SampleData/boat.bgltf'
    }
});

viewer.trackedEntity = boat;
```

**Comment by alexander-entin** [comment] 2015-06-09 10:05
It is fixed in 1.10.
So, now I can switch `depthTestAgainstTerrain` on again.
Thank you!

**Comment by alexander-entin** [comment] 2015-06-09 10:44
As for disappearing logo. Add `scale: 100` and you'll see it.

**Comment by hpinkos** [comment] 2015-10-14 20:48
@alexander-entin i'm going to close this issue because the polygon error has been fixed.
If you are still having an error with the logo on your boat model, can you please post it to [the forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev)? The model demo you posted in this issue seems to be out of date.  Thanks!

**Closed by hpinkos** 2015-10-14 20:48 UTC
