### ISSUE TITLE
How to forbid this type of pop window?

### ISSUE THREAD

**Issue by hieeyh** [AnalyticalGraphicsInc/cesium#7584] opened 2019-02-20 03:37 UTC
![969f8b1f-c511-7222-fbdd-4f9c68fa1c2a](https://user-images.githubusercontent.com/6123902/53064733-dbc7f700-3503-11e9-8674-b6550f9db3a4.png)

Can I stop this kind of window to pop?

**Comment by hieeyh** [comment] 2019-02-20 03:38
![8325e1c8-bdac-5201-0631-934f3f2c2f07](https://user-images.githubusercontent.com/6123902/53064791-05811e00-3504-11e9-9cbd-64568b6394e2.png)

**Comment by OmarShehata** [comment] 2019-02-20 15:24
You typically don't want to prevent the error window from popping up because it's likely that the application will either have undefined behavior or crash at a later part. See the forum discussion here:

https://groups.google.com/d/msg/cesium-dev/bMlM2adWrG0/7WhyIsvFGQAJ

If you post a forum thread some more information about when this error is happening, and attach your code/a link to a Sandcastle reproducing it, I'd be happy to take a look. If it turns out to be a bug in CesiumJS we can re-open an issue here.

**Comment by cesium-concierge** [comment] 2019-02-20 15:25
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/bMlM2adWrG0/7WhyIsvFGQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7584 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed by cesium-concierge** 2019-02-20 15:24 UTC
