### ISSUE TITLE
Quaternion interpolation issue

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2233] opened 2014-10-28 15:41 UTC
@tfili already reported the details to @bagnell

**Comment by mramato** [comment] 2015-03-02 05:05
Assuming this is still a bug (and any of you remember what the issue is) we should probably put some details here before people forget.  It's already been 4 months.

**Comment by hpinkos** [comment] 2015-10-14 19:15
I'm closing this because it's been almost a year and this issue has no information in it.
@tfili @bagnell please open a new issue if you know what this was about.

**Closed by hpinkos** 2015-10-14 19:15 UTC
Labels: bug
