### ISSUE TITLE
Globe Rendering bug with planets other than EARTH

### ISSUE THREAD

**Issue by Nymria** [AnalyticalGraphicsInc/cesium#8142] opened 2019-09-09 06:54 UTC
There are rendering issues like flickering and going full dark after that (Ceres / Vesta / Moon). 

Or when you zoom out planet turns entirely black (Mars).

Mercury has black going tiles at the edge of the planet (Mercury).

There was no issue with my previous Cesium version which was 1.36
You can view them @www.terrainserver.com

Browser is chrome desktop, Version 76.0.3809.100 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/19736494/64509129-bf48ac00-d2e7-11e9-8879-53a79cf48e73.png)

**Comment by OmarShehata** [comment] 2019-09-09 11:10
Thanks for reporting this @Nymria ! Are you able to test with any versions between 1.36 and 1.61 to help us narrow down when this issue started? An easy way of testing older releases is using these release links:

https://cesiumjs.org/releases/1.45/Apps/Sandcastle/index.html?src=Offline.html

So that would give you a hosted CesiumJS 1.45. It would also help to post a reproducible code example. For example, is it the custom ellipsoid you're using that causes the issue? Do you have a custom terrain provider? etc.

**Comment by Nymria** [comment] 2019-09-09 12:22
Hello @OmarShehata 

I have narrowed it down to version 1.50. The rendering is broken @1.50 but working on @1.49.

I am using custom ellipsoid and custom terrain provider since this is a different planet.

You can see the sandcastle examples below


[Broken Version 1.50](https://cesiumjs.org/releases/1.50/Apps/Sandcastle/index.html#c=fVPRjtowEPwVixeClNpXXatKKdBWlFaV4HoS1d0LEnKSJbg4cWo7oSm6f+/GJJCA2jwk9mZ2dnY9JiXXBKQUuVEiJhOSwYHMwIgipfM27L15d4cPvfNJZ3X/1q1G79cZIcS9arJSwAF0n+nJxbxh5LYzlVkuMtBD/+jSUp4/avUTIitUFnQTv4JKNM93IroAvLPckb/OHIEVKUhkDIjVBWD0JCfkBha8Av0ooj3ogGy5NO43ISaCDJYqBhKQttqqjdHVbP4wv//cQPfVJ5sqk+9AQ0tC2p6JSHkCukKBpYjrKh39zxAueb4CXYoIvvWB3rFR3zyFlgEZ7qzNTcBYLnkGlusKh2NoYRJDE1WyKBGvQpGxOoqsH/A7cRvGjQWNQ9mEIC2LUKrZGJHmm6iSFBFD/1KKdOsSWY/I4ByGM5f1ZbZJpAq5HPo93HnuwWXZA7yMcPtSG8J1VrsBNWk867bnvi1Onx99iHf891AOhwNtGOvuQdNIpcwtnXR2UFrG7Eq3hl8FGPvMMXXJzb7ngyvQE2gLvx+UThEStG76T/eu3cb01JmKblVCIeOhhPpCuVodzO1EriI3fPVhQMO4EMnOiiw5Ew/8wdjYSsL0pPMjHrnSth6cRymzkKKTLI4mLPAOWBoZUyseszZpHIuSiHiyHlzdzvWARJIbg3+2hZQr8QfWg+mYIb6XJhWPUdF3PA50Ug3ZvZ4uTkFK6Zjh9jbLKiVDrjuMfwE)

[Previous Working Version 1.49](https://cesiumjs.org/releases/1.49/Apps/Sandcastle/index.html#c=fVPRjtowEPwVixeClNpXXatKKdBWlFaV4HoS1d0LEnKSJbg4cWo7oSm6f+/GJJCA2jwk9mZ2dnY9JiXXBKQUuVEiJhOSwYHMwIgipfM27L15d4cPvfNJZ3X/1q1G79cZIcS9arJSwAF0n+nJxbxh5LYzlVkuMtBD/+jSUp4/avUTIitUFnQTv4JKNM93IroAvLPckb/OHIEVKUhkDIjVBWD0JCfkBha8Av0ooj3ogGy5NO43ISaCDJYqBhKQttqqjdHVbP4wv//cQPfVJ5sqk+9AQ0tC2p6JSHkCukKBpYjrKh39zxAueb4CXYoIvvWB3rFR3zyFlgEZ7qzNTcBYLnkGlusKh2NoYRJDE1WyKBGvQpGxOoqsH/A7cRvGjQWNQ9mEIC2LUKrZGJHmm6iSFBFD/1KKdOsSWY/I4ByGM5f1ZbZJpAq5HPo93HnuwWXZA7yMcPtSG8J1VrsBNWk867bnvi1Onx99iHf891AOhwNtGOvuQdNIpcwtnXR2UFrG7Eq3hl8FGPvMMXXJzb7ngyvQE2gLvx+UThEStG76T/eu3cb01JmKblVCIeOhhPpCuVodzO1EriI3fPVhQMO4EMnOiiw5Ew/8wdjYSsL0pPMjHrnSth6cRymzkKKTLI4mLPAOWBoZUyseszZpHIuSiHiyHlzdzvWARJIbg3+2hZQr8QfWg+mYIb6XJhWPUdF3PA50Ug3ZvZ4uTkFK6Zjh9jbLKiVDrjuMfwE)

**Comment by OmarShehata** [comment] 2019-09-09 20:37
Ah, thanks for debugging this and posting your result @Nymria ! It looks like you've stumbled on this issue here https://github.com/AnalyticalGraphicsInc/cesium/issues/7124. I'm going to close this and add your discovery that it broke somewhere in 1.50 there.

**Closed by OmarShehata** 2019-09-09 20:37 UTC

**Comment by jumpjack** [comment] 2020-12-16 18:25
where/how do I get tiles for  "planets other than EARTH "?!?
