### ISSUE TITLE
Entity polyline blinks on position update

### ISSUE THREAD

**Issue by ihsanergun** [AnalyticalGraphicsInc/cesium#7782] opened 2019-04-26 06:46 UTC
![Aufnahme_2019_04_26_08_34_09_463](https://user-images.githubusercontent.com/49189724/56788128-df774300-67fe-11e9-8275-1e71f0cf634d.gif)

In my example above, on position update, the polylines will be updated with some delay (I have more than 1000 entities). I tried to reproduce it on a Sandcastle with one entity and the result is similar. The polyline blinks on update.

 

Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=pVVLb9s4EP4rhC+xYYWSnPoQxTF2kQRtgQIbIMHuIeqBkcY2EYoUSMq2Wvi/71Bvx3WzwOoizuObN4dbpsmWww40uSUSduQODC8y+nfFG18kFXmnpGVcgr6Y3MRyi5hcGW65kgZhL7Ek+P0USkYk9IhgNiKfgoN3xKe9hIYnsvlAOH8vnfXC2YlsgJzND7H83kTIMbKgOZvt+p5Zdg+JYBpQEI9SpCOesTX4KJ3uM+HFo5vadvc12DuuE+FgF4ukPib723gUBvGIJGV70niY499Yrd4AiRKEULuOc7njqd0g/wpZKy4EHqWSgJS/JBdnfD9qWPF95RspsgVtsOzOJw0RiXFLg9TG2jzy/d1uR3dXVOm1PwuCwKXWKkV7weXbL1XD6+trvxI7ZVRx6ZTNv416FuR7JDfA1xvb02g7MjlLXMK5BgN6ixktz6XzVKzqdOLRwkW3PFv0J6u5XKNmX4TpoBnT3toZAw/Sclt+dS2urQxHYNq7QDhOSTXvNGEZaEZXonxW45/HdlMwlkvmpj5qr8kd0xZPTF7RlVbZPaw1gBkHHo6jR+aB+ya9mcOkdoYBWs2SN4yrcQwuWA6GsjRtHbd37CNv3V18Cb5TvBYeOeYwO2kuzStO3atiOiXRu+Sqm0Cid3XzeiWTMAF4ywbJeG2YosTZQeFgfzw2zM+a5RuemGExu+g+SOxPrVk5XoNtjT22wKOUJ5NBmNW0EreGel7GLGjOBOn9KaE0/efL1+eHWu2ATWqaE0sD9plnoAo7XhUycX7GE9IkUOS4OQaRONDBI1eu0RW+hZBzgXemNNhCS/LiCtL1zbXLazk4pmHHdQRx2+1w5OYkoNZ8NWG0rRSO2n+doumUn8wRr+fo5th0nR0dPgb/v6McO9r44Ssyxj1+e9tHQgXINbb4koRdppUq+r4MG9yh/v22keeaWY9219DDyBstjC0FLGvZHzzLlbak0GJMqW8hy7EyYPzXInkDSxNjHA63WwNapHxLeIr78d1j6l4PwYxb36tCiCf+w23OhY/6RzChWIp76i/c/YKVTmUTLr/VTErpwkfyFGWVEq9MDyz+Cw

Browser: Chrome, Firefox, Chromium

Operating System: Windows, Linux

**Comment by OmarShehata** [comment] 2019-04-26 13:57
This blinking is actually a feature, not a bug! Entities by default are considered static, and will update asynchronously. You can mark an entity as dynamic by using callback properties. This is a good example on that:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Drawing%20on%20Terrain.html

Notice that it updates immediately while you draw, then it will disappear for a second once you finish drawing (pressing right click) because it switches from dynamic to static. 

This forum post goes into a bit more detail about how the sync/async nature of primitives/entities in Cesium works: https://groups.google.com/d/msg/cesium-dev/5N1P_qPmbPo/rbnHNKFoAQAJ

**Comment by cesium-concierge** [comment] 2019-04-26 14:03
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/5N1P_qPmbPo/rbnHNKFoAQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7782 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed by cesium-concierge** 2019-04-26 14:03 UTC

**Comment by ihsanergun** [comment] 2019-04-29 07:38
Thank you for your reply, I now understand how drawing lines with callback works. But my issue is a bit different:

1. How could I move entities if they are by default are considered static?
2. In my example, circle and line belong to the same entity (I do not have a line collection, I use Entity.Polyline). Are they rendered seperately?

**Comment by OmarShehata** [comment] 2019-04-29 14:14
@ihsanergun 

> 1. How could I move entities if they are by default are considered static?

Callback properties can apply to any property. So you can have a position be a callback property so it can move. Here's a Sandcastle on it:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Callback%20Property.html

This one shows you how to get a vehicle entity to move with a callback property, as well as get the wheels to turn:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Time%20Dynamic%20Wheels.html

> 2. In my example, circle and line belong to the same entity (I do not have a line collection, I use Entity.Polyline). Are they rendered seperately?

Can you elaborate a bit on this question? An entity can have several different shapes attached to it, which is a convenience of the Entity layer but I think in general at the low-level primitive layer it's the same as having creating those shapes separately.

**Comment by ihsanergun** [comment] 2019-04-30 04:42
>  but I think in general at the low-level primitive layer it's the same as having creating those shapes separately

This answers my question. Thank you.

But in my Sandcastle example, I have a circle(as image) and line. None of them has any callback property. So why the circle does not blink but line? Because it is an image?

**Comment by OmarShehata** [comment] 2019-04-30 12:16
> But in my Sandcastle example, I have a circle(as image) and line. None of them has any callback property. So why the circle does not blink but line? Because it is an image?

My best guess is that this is because not all entity types have asynchronous code paths. A lot of geometry construction is moved to web workers, but an image may just be fast enough on the main thread so it updates in a single frame even though it is marked as static.

If you're interested in delving deeper into this I definitely recommend reading the forum discussion I linked to here https://github.com/AnalyticalGraphicsInc/cesium/issues/7782#issuecomment-487066321. It's an area where there's a lot of improvements that can be made (at the very least the community is missing a good tutorial on all this).
