### ISSUE TITLE
Bug in zoom with disableDepthTestDistance on billboards !

### ISSUE THREAD

**Issue by benjaminmur** [AnalyticalGraphicsInc/cesium#8009] opened 2019-07-17 10:39 UTC
Hi everyone !

first, the sandcastle : [link](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1VqLb+I4E/9XrEqnBB01CdAHbKmur/0WqS0VZXd1t11VJjFg1SR8jillV/3fb5wE8i7pbdvroe0mccbz+Hk8Ho9zTwS6Z3RBBeoghy7QCfXYfIq/+G26ZvmPJ64jCXOo0Cofbpx76GORKRUE+gSdcfAML2+c0dyxJHMdRGz7mHE+dImw9Qr6eeMg+F0Tx7aIJznFNrU4EVSPE1Z8Hoow5EwdySSjHgYqPeShfjPXY76Y9krnEyIk3BGngUfCnZ7SsaDU03erqNmoVKOew5Us1I7xUz/PIpy2kVlNNrMpGVOQc7NlE0na/mPNux///jDlVXQAd+ieCg+U6WgmNjXE7I52Qvj/5/QWnoDK8TraRMpZu1ZbLBZ40cCuGNfqhmEoPiFJ+4Ez5y6P0Gy1WjX/LZB2NGP2oKFlcL2RaMFsOelozX3VPKFsPJGrJ4Xhsau6IAM19+GfhqhDhpxuD4l1Nxbu3AFd1cDHKECbtjcjFu1oM0E9Ku6pdnggqCWRC81MKtl4V4skx+VqtcMDiwmLUzQCpDvab/WGYeztj0YaskCVehOuy+AqFGA7mR6O61ANeVK4dzTRP2jaDuXW1w1TJqngDC7A0MiX01BiAMMXE/JgBsyXcG3swXM9fIarab6GNODqS1NSlDQldRlIBWnKlQ5vtlLOGwxMn46ooI5Fo+nyKfkCn5wfXVzdDnq3/+v3Pl+eptjYzFNuc0pncjKgnjxlniQBv8v5dAgT9ap33R10v5zddi8/di+7gz9THLyJu2gjKeY09aJWs0NmwHTGyRLCjb2a27GYdFpApTdhHhmViOljcPuoYom6CYIT9qhUYS0KIjbYwRyieJQKIlXU8CWt9XcFg/AUMviZxp3YzBm3kZEyd8akNVnLuyBygqXbB2LiePp2y6ik6IXLOXDBRrw5buJjIuqCletgeiXcGRUqej4Zf/O7vHwk3t7bwTutvb09ABPsaezvF8XlNJirCKxhXPPvvVog6vbcHbu3LoRf8Ag8c8ZaFfwJRnZE5ly2EYQ3OoJZaGd9EYXOGKPPWQ2Aqo6NJFMzORbgYC53Rcx89YjPuxdnyX5fP3UHZ+nBDdwHJR3iqnvb+3LWv/3Y+9xP8jDSsglnY7Dv6IF5uQPw11m/V2yjH3agn2kYpYALookCZWcTebGLWhPijOlzvbSwV8xRITPxvXQZZSav4bVhIICnl/fffAAj+yIpndBWvG4K4936GQcu3EENbGTeBU7bSTqt76J4weTkiM8mRDdwfScnxrAf0UB0nQsKS9WGEJPX4+0H7hXCTSpmgJ0r88IA8+SABqb+cN3pwNUDBLJwAwAXMMvYjEcYepsy6myPJNwcLPksOOBdwsoPUb8RJIAc1Mz0Xb3AYzbS3uHaERpcnCa8mKr7Bt6BcNrYwWbzmUrG0H0bRc16FWI5bu6+tKKpiKEC0fFylcI9HSuStO88D0m4fTUng4gsSaazl5SIj0RcAw0ROmyDqBoKlWuoe9ANvKhSBtsRsctCmyT9r2Z4yZ5SQOLM5xZsYpavjrU7GqlsuRzaaeLV/A2VWkyogwnn+reYQeG7PvXcuYBd2YjCbqGrANFLQJPYO5RjlfDfGAbfY6xW5utBn0p68CATPPJWdSS1mHnI4q4HD9JdR4po9DP7P8QcS1DiUdgcPVDe83FDAHdggjIz5jvAU04g2w1y0SSv+AoVbHBhkQq0/mZ+x0GXtdvHNFDZkEUktSNBXhU2UzMioBWRtXljKlfWpUQ/PYdeei6VmFPpubXGoZpPN4H97A9V6uM9wcYspuKn1Bt8cnY5OOsX8LlXebmV5fIl0Y6Pe4NB7yLL4jHZtF72/nNAG+8K6AIe8RmXiJlrtOqwC4BIuZ2cV5XN/K6fs/wZtKGicRiSd1VINopk/JOQn8PfrJR3vsf8tJyIOyqekZSn6KMVWIVQ24aAA2NKeCwIoSHERVsFQzmBODSEcB/6GQubJCcefsfr+GLCJL2ekBkolLN++1TX82GfjjMlv2NVn2bOuE8tGOIxp3qzFVTizH31l3aQwkLMWyTTTeVcjdavFAVeFKpdE3KcjVDFZ7xq0g0/G1rPlacKqy/nbn6EaZrvBzvw/H1lf1P9lcdOAWfg1huj1/A9b+/doFcH9EwDXK+u0ux6qVnaPzt9C6haONiZvxeoTENNNf+/8hHtz7Pz897XJ/YrKg2WVAjCnCvh3jObig+xlSt9mPPkspUmjtaslISodJcVHRvEbK/QNrUFkPSrK7g9CGj01Ph7sOJTPObuUKkX6nM0BkpPhl2AnSq6vfzO1qzXsdnagUFq7sKNufM6JYN/77hu4+wLq5QpRNc+F3MdAHngunxIxAV15vq3nyt/eVA5pqYSnTViKwBcx6NcHTG3o+1mYqOZ/JwgtieICZ4ARlzhlPmmILTrsYpSylxD3hsN32x9qgB5FfI9EhQprWPR4dsmbYtP4Ar1PvGPQ3JVL63uEwcxmzR+8jSmGGz2I64yTNepXyovD3D+ycNGfIuOHwo1VT46DUvosWz8Od6aV7Mv4bb5hftiSP0jnuFyVZ9YnaWXhzRdmt0IZrY+W6jdR2L/knLp2uYm3bIFzkLVwj3vLyiXLQZuUq+oIljsgv6G8Z86YGZ3Wsb9craohSqeBsuMvw/1F2R440mkKpsIsofpjPrluuA7o9KqZ9OTTXrn5Sgrpb8HCUusn/qmSdUF1/lQJD7xORse8eUnd0p1oygPFXQK+/EjzvUoK2IjpIdrdngmrqdSnkrC2sK0KD+Lyk+81ufvHzKMyyVNI8I9GkMNbreqWweeXHJ6GDT/waYzV0g0F1yHZEbS6YxDwubVhnPrjkpseb6zHNRWnQ5sdq++hbvZSn1GeLOlvMPz4M1ozrlaFW62Dg9qQJ/oxl3/G5peUOFWJBPz8DxoxBgf1OAx20sGqUeM498)

It's a bug when you zoom, while a billboard is perfectly centered, with depht test against terrain activated, AND disableDepthTestDistance Number.POSITIVE_INFINITY set on this billboard.
Pretty easy to reproduce if you wait the scene to finish loading, then use the mouse wheel, or any other way to zoom in / out.

Just wait for the scene to load, if you zoom while the scene is loading, it won't happen.

You can't zoom in or out anymore.

It happens on startup because our view is centered to a billboard, but also randomly when we move the camera, zooming in and out, and a billboard come accross the center of the view.
The more billboards on screen, the more frequently it happens.

If you need more info, let me know.
It may seem related to another issue: disableDepthTestDistance causes weird mouse interaction #6840  what do you think ? Related ?

Just so you know...this bug is really impactfull on our work.

"Help me Obi Wan Kenobi you're my only hope".

**Comment by hpinkos** [comment] 2019-07-17 13:54
@benjaminmur yes, this is a duplicate of #6840
When the billboard is at the exact center of the screen, `disableDepthTestDistance` makes the billboard act as if the camera is right on top of it, and the camera can't zoom in because it thinks there is a collision.  We had this come up with another user recently, so it's possible we might be able to look at it before too long.  I'm not sure when though.  In the meantime, keep an eye on #6840.  Or if you would like to investigate a fix and open a pull request, we would be happy to review it!  Thanks

**Closed by hpinkos** 2019-07-17 13:54 UTC
