### ISSUE TITLE
pickPosition return a wrong altitude

### ISSUE THREAD

**Issue by hieeyh** [AnalyticalGraphicsInc/cesium#7506] opened 2019-01-24 12:51 UTC
cesiumManager.eventHandler.on('LEFT_CLICK', onLeftClick)
onLeftClick = function (movement) {
const viewer = cesiumManager.cesiumViewer
      let ellipsoid = viewer.scene.globe.ellipsoid
      let cartesian = viewer.scene.pickPosition(movement.position)      
      let latlng = GSModel.LatLng.fromCartesian3(cartesian, ellipsoid)
}
the altitude of the latlng is higher than real.
![default](https://user-images.githubusercontent.com/6123902/51679406-dae19980-2019-11e9-839f-6ec68f9ded97.PNG)

**Comment by hpinkos** [comment] 2019-01-24 14:46
Closing this as a duplicate of #7261
@hieeyh, if you have any more comments or sample code to reproduce this, please add it to that issue.  Thanks!

**Closed by hpinkos** 2019-01-24 14:46 UTC
