### ISSUE TITLE
cesium1.36 Model transparency

### ISSUE THREAD

**Issue by duoduohappy** [AnalyticalGraphicsInc/cesium#5731] opened 2017-08-08 05:35 UTC
![2](https://user-images.githubusercontent.com/14144081/29058542-6c3cffb8-7c43-11e7-8abe-b309d8807427.png)
cesium1.36
![1](https://user-images.githubusercontent.com/14144081/29058562-8a77ff8c-7c43-11e7-9efe-c7d90822d9d4.png)
cesium1.35
Find a problem, cesium1.36 The model becomes transparent,cesium1.35 Display normal

**Comment by lilleyse** [comment] 2017-08-08 14:01
Would you be able to send over the model? That will help for debugging this.

**Comment by pmconne** [comment] 2017-08-08 18:11
I'm also observing this issue. When globe is on, depth test appears to be disabled for translucent geometry only. If you have our OfficeBuilding data set, that one exhibits it - or I can send a simpler test case.

**Comment by pmconne** [comment] 2017-08-08 18:27
[Translucent.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/1209171/Translucent.zip)

Globe off (translucent red cylinder behind opaque green cylinder):
![image](https://user-images.githubusercontent.com/22944042/29087958-a9b7cdd0-7c45-11e7-814e-db02be74319c.png)

Globe on:
![image](https://user-images.githubusercontent.com/22944042/29087928-9786f456-7c45-11e7-9528-e6e450d6361f.png)

**Comment by lilleyse** [comment] 2017-08-08 19:17
Thanks @pmconne for uploading the model, I'll start looking into this and #5734.

**Comment by lilleyse** [comment] 2017-08-08 23:26
@pmconne It seems like this is caused by the recent architectural changes that allowed classification primitives to work on 3D Tiles - see https://github.com/AnalyticalGraphicsInc/cesium/issues/5676 for more context.

Now the globe and opaque 3D Tiles are rendered together into the same depth buffer, and their depth is cleared after classification primitives are rendered. This causes the red cylinder, which is in the translucent pass, to not depth test against anything.

For the time being our recommendation is to set `scene.globe.depthTestAgainstTerrain` to true, but we hope to have a better solution before the next release.

**Comment by duoduohappy** [comment] 2017-08-09 02:48
scene.globe.depthTestAgainstTerrain=true   Display normal，Thanks@lilleyse

**Comment by duoduohappy** [comment] 2017-08-09 02:53
Thanks @lilleyse , scene.globe.depthTestAgainstTerrain=true Display normal

**Comment by duoduohappy** [comment] 2017-08-09 02:56
@lilleyse  vector layer Will the next release increase?

**Comment by lilleyse** [comment] 2017-08-09 13:59
> @lilleyse vector layer Will the next release increase?

It's unlikely that vector tiles will be ready by the next release. Or do you mean something else?

**Comment by duoduohappy** [comment] 2017-08-10 03:24
Thanks @lilleyse  We refer to mapbox vector label and vector line , I wonder if it will increase  next release？

**Comment by pjcozzi** [comment] 2017-08-31 14:13
@lilleyse please close if you confirmed this is fixed in #5770.

**Comment by pjcozzi** [comment] 2017-12-22 13:27
Reopening to investigate @pmconne's use case when the globe is off.

**Comment by pjcozzi** [comment] 2018-01-02 13:01
Pushing post 1.41 release.  @bagnell please still look at this soon, thanks!

**Comment by pjcozzi** [comment] 2018-01-18 16:45
@bagnell could you please look at this soon when you need a break from tests in #5615?

**Comment by bagnell** [comment] 2018-01-19 21:18
I can't reproduce this. I see the correct rendering regardless of whether the globe is on or off.

Translucent in front:
![translucent_globe_off](https://user-images.githubusercontent.com/1494815/35172127-692ade4a-fd34-11e7-89b8-e04ad6b4eb45.jpg)
Translucent in back:
![translucent_behind_globe_off](https://user-images.githubusercontent.com/1494815/35172132-6c61f53a-fd34-11e7-81ad-ac5713f2790d.jpg)

**Comment by hpinkos** [comment] 2018-01-19 21:20
@bagnell this area looks questionable
![image](https://user-images.githubusercontent.com/3451886/35172189-9acc6720-fd34-11e7-9f06-6ddd298e1fd3.png)

**Comment by hpinkos** [comment] 2018-01-19 21:23
Or wait, I guess they're intersecting so that would be correct

**Comment by hpinkos** [comment] 2018-02-26 16:58
I'm going to close this.  I got the same results @bagnell did

**Closed by hpinkos** 2018-02-26 16:58 UTC
Labels: category - gltf, priority - next release, type - bug
