### ISSUE TITLE
An error occurred while rendering. Rendering has stopped

### ISSUE THREAD

**Issue by bidolah** [AnalyticalGraphicsInc/cesium#6940] opened 2018-08-20 20:54 UTC
Hi Team!

I get next error when I try to display my gltf model in https://www.virtualgis.io/gltfviewer/ 

> An error occurred while rendering. Rendering has stopped.
TypeError: Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at d (https://www.virtualgis.io/gltfviewer/node_modules/cesium/Build/Cesium/Cesium.js:526:10900)
    at https://www.virtualgis.io/gltfviewer/node_modules/cesium/Build/Cesium/Cesium.js:526:10342
    at Object.t.object (https://www.virtualgis.io/gltfviewer/node_modules/cesium/Build/Cesium/Cesium.js:525:6809)
    at Object.t.topLevel (https://www.virtualgis.io/gltfviewer/node_modules/cesium/Build/Cesium/Cesium.js:525:6901)
    at Object.t.material (https://www.virtualgis.io/gltfviewer/node_modules/cesium/Build/Cesium/Cesium.js:525:7493)
    at c (https://www.virtualgis.io/gltfviewer/node_modules/cesium/Build/Cesium/Cesium.js:526:10258)
    at Ee.update (https://www.virtualgis.io/gltfviewer/node_modules/cesium/Build/Cesium/Cesium.js:528:22221)
    at a.update (https://www.virtualgis.io/gltfviewer/node_modules/cesium/Build/Cesium/Cesium.js:549:22895)
    at tt (https://www.virtualgis.io/gltfviewer/node_modules/cesium/Build/Cesium/Cesium.js:553:3390)
    at Ke (https://www.virtualgis.io/gltfviewer/node_modules/cesium/Build/Cesium/Cesium.js:553:1194)

So I try to find solution and found the problem of falling. If you have .gltf model with **unused materials** this leads to an error. So I download gltf model from  https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Box/glTF-Embedded/Box.gltf and render it without problems. But when I try to add additional unused material it leads to stop rendering error.

You can look my changes here:
![image](https://user-images.githubusercontent.com/9832538/44366029-0c3ac400-a4d4-11e8-91b4-9062e93a5958.png)

 Also I attach .gltf document with unused materials.
[Box.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/2303889/Box.zip)

Could you please fix it?

**Comment by ggetz** [comment] 2018-08-20 21:28
This model load in the branch from #6805 

![image](https://user-images.githubusercontent.com/4439461/44367631-5903a800-a49e-11e8-89a1-babe2c9d9926.png)

**Comment by bidolah** [comment] 2018-08-20 21:34
Thanks for quick response. I would be glad to see the fix in the next release. 

Have a nice day! @lilleyse  @ggetz

**Comment by lilleyse** [comment] 2018-08-30 17:33
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/6906.

**Closed by lilleyse** 2018-08-30 17:33 UTC

**Comment by wuming2019** [comment] 2022-04-06 09:13
RuntimeError: Fragment shader failed to compile.   Compile log: 
 
Error 
at new RuntimeError (webpack-internal:///./node_modules/cesium/Source/Core/RuntimeError.js:40:11) 
at createAndLinkProgram (webpack-internal:///./node_modules/cesium/Source/Renderer/ShaderProgram.js:253:13) 
at reinitialize (webpack-internal:///./node_modules/cesium/Source/Renderer/ShaderProgram.js:509:17) 
at initialize (webpack-internal:///./node_modules/cesium/Source/Renderer/ShaderProgram.js:502:3) 
at ShaderProgram. _bind (webpack-internal:///./node_modules/cesium/Source/Renderer/ShaderProgram.js:578:3) 
at beginDraw (webpack-internal:///./node_modules/cesium/Source/Renderer/Context.js:1144:17) 
at Context. draw (webpack-internal:///./node_modules/cesium/Source/Renderer/Context.js:1250:3) 
at DrawCommand. execute (webpack-internal:///./node_modules/cesium/Source/Renderer/DrawCommand.js:570:11) 
at ComputeEngine. execute (webpack-internal:///./node_modules/cesium/Source/Renderer/ComputeEngine.js:126:15) 
at ComputeCommand. execute (webpack-internal:///./node_modules/cesium/Source/Renderer/ComputeCommand.js:120:17)

![FCVAV9__X LF`6AY N4}K58](https://user-images.githubusercontent.com/52288916/161940704-fdc60c40-a95d-48be-be69-022f24455214.jpg)

**Comment by ggetz** [comment] 2022-04-06 13:02
@wuming2019 I think the issue you are running into is https://github.com/CesiumGS/cesium/issues/5991. Your page is losing the webgl context, which we don't have control over. However, we could report a better error.

**Comment by wuming2019** [comment] 2022-04-07 01:21
> @wuming2019 I think the issue you are running into is #5991. Your page is losing the webgl context, which we don't have control over. However, we could report a better error.
No, this is a VUE project。I'm just doing a tabs switch，create multiple cesuim view，switch back and forth between several tabs，memory cannot be freed，and eventually collapse。

**Comment by ggetz** [comment] 2022-04-08 13:00
> No, this is a VUE project。I'm just doing a tabs switch，create multiple cesuim view，switch back and forth between several tabs，memory cannot be freed，and eventually collapse。

VUE shouldn't affect much. This is caused by how the browser is handling memory. When too many instances are created, the browser can be agressive about destroying WebGL contexts, which then causes cesium views to crash.

**Comment by WahajTariq** [comment] 2022-04-10 23:45
Hello, 

I wanted to use Cesium to verify the coordinates of a BIM Model (ifc imported). When I launch the HelloWorld program it gives me the following error:


An error occurred while rendering. Rendering has stopped.
SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.

Error: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
    at new Texture (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:292351)
    at Material$4.update (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:320751)
    at EllipsoidPrimitive.update (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:2554722)
    at Moon.update (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:2824039)
    at Scene.updateEnvironment (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3102902)
    at render (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3106427)
    at tryAndCatchError (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3106686)
    at Scene.render (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3108572)
    at CesiumWidget.render (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:90:113237)
    at n (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:90:98966

The image of the error:
![image](https://user-images.githubusercontent.com/83837323/162645090-4b5ebe0e-cb1a-4695-9dff-e79f228ef298.png)


Could you please help me to solve this?

**Comment by supershunan** [comment] 2024-05-13 14:13
![image](https://github.com/CesiumGS/cesium/assets/63410972/abf71887-828e-4ff2-b3b4-7a91109a5ea8)
Could you please help me to solve this? Very thank you.

**Comment by amarnath45ds** [comment] 2024-09-24 12:48
> Hello,
> 
> I wanted to use Cesium to verify the coordinates of a BIM Model (ifc imported). When I launch the HelloWorld program it gives me the following error:
> 
> An error occurred while rendering. Rendering has stopped. SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
> 
> Error: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded. at new Texture (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:292351) at Material$4.update (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:320751) at EllipsoidPrimitive.update (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:2554722) at Moon.update (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:2824039) at Scene.updateEnvironment (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3102902) at render (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3106427) at tryAndCatchError (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3106686) at Scene.render (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3108572) at CesiumWidget.render (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:90:113237) at n (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:90:98966
> 
> The image of the error: ![image](https://user-images.githubusercontent.com/83837323/162645090-4b5ebe0e-cb1a-4695-9dff-e79f228ef298.png)
> 
> Could you please help me to solve this?

Hi @WahajTariq Did You resolve this issue. I am facing the same issue. Please help me to resolve this issue
