### ISSUE TITLE
Lock camera to a given volume

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#8143] opened 2019-09-09 10:58 UTC
This suggestion came up over email as work-around to the issue of it being easy to accidentally lose your place while navigating inside of a building or other confined model in CesiumJS.

The idea is you would be able to pass a volume (perhaps a sphere or box) and the camera class would take care of limiting the user from leaving that area - in the same way that it currently won't let you go underground. 

Normally I think this type of thing would be better implemented by the developer since there's so many potentially application-specific details (does the camera just stop when hitting this volume, or does it gently ease back? Should there be some visual indicator? What if you get stuck in a corner?) But it may be a non-trivial thing to implement, so if it's common enough it might be worth supporting in the library.

The current best work-around I'm aware of is to have some stored views in the app, so even if the user loses their place, they can easily get back. An example of this is in this Sandcastle:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Montreal Point Cloud.html

And here's a nice helper function for getting a camera view you can fly to. So you can just position the camera how you want, run this function (as a button or keyboard press etc.) and save the resulting string:

```
function getCameraFlyTo() {
            var camera = viewer.camera;
            var position = camera.position;
            var direction = camera.direction;
            var up = camera.up;
            var cameraString = '{\n\
                destination : new Cesium.Cartesian3(' + position.x + ', ' + position.y + ', ' + position.z + '),\n\
                orientation : {\n\
                    direction : new Cesium.Cartesian3(' + direction.x + ', ' + direction.y + ', ' + direction.z + '),\n\
                    up : new Cesium.Cartesian3(' + up.x + ', ' + up.y + ', ' + up.z + '),\n\
                },\n\
                duration : 3\n\
            }';
            return cameraString;
        }
```

**Comment by mramato** [comment] 2019-09-09 12:47
@OmarShehata this is a duplicate of #4802, which is a long standing feature request.  The general consensus is that it should be part of the core API.  We even have a branch that a lot of work went into that we just haven't gotten back around to yet.

**Closed by mramato** 2019-09-09 12:47 UTC
Labels: category - camera, type - enhancement
