### ISSUE TITLE
ScreenSpaceEvent LEFT_UP not working properly

### ISSUE THREAD

**Issue by kteneyck** [AnalyticalGraphicsInc/cesium#7571] opened 2019-02-14 15:24 UTC
See forum post here: https://groups.google.com/forum/#!topic/cesium-dev/Iv86c72Yq5g

Includes a working example in 1.52 and the same example not working in 1.53

**Comment by hpinkos** [comment] 2019-02-14 16:31
- Left down on the point to drag it
- Press a key on the keyboard (like `z`)
- Left up to stop dragging the point.  The left up event does not fire because the key is pressed

Likely broken in #7258

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider: Cesium.createTileMapServiceImageryProvider({
        url : Cesium.buildModuleUrl('Assets/Textures/NaturalEarthII')
    })
});

var point = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
    point : {
        pixelSize : 10,
        color : Cesium.Color.YELLOW
    }
});

var aggregator = new Cesium.CameraEventAggregator(viewer.scene.canvas);
var handleLeftUp;

var pickedCartesian = function() {
    var scene = viewer.scene;
    viewer.scene.screenSpaceCameraController.enableInputs = false;
    var ray = scene.camera.getPickRay(aggregator.currentMousePosition);
    return scene.globe.pick(ray, scene);
};

var leftDownFunction = function(movement) {
    var pickedPoint = getPickedPoint(movement.position);
    if (pickedPoint !== undefined) {
        viewer.clock.onTick.addEventListener(movePointFunction);
        handleLeftUp = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
        handleLeftUp.setInputAction(releasePointFunction, Cesium.ScreenSpaceEventType.LEFT_UP);
    }            
};

var movePointFunction = function() {
    var cartesian3 = pickedCartesian();
    if (cartesian3) {
        var cartographic = Cesium.Cartographic.fromCartesian(cartesian3);
        point.position = Cesium.Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude);
    }
};

var releasePointFunction = function() {
    viewer.clock.onTick.removeEventListener(movePointFunction);
    handleLeftUp = handleLeftUp && handleLeftUp.destroy();
    viewer.scene.screenSpaceCameraController.enableInputs = true;
};

var getPickedPoint = function(windowPosition) {
    var scene = viewer.scene;
    var drillPickObjs = scene.drillPick(windowPosition);

    for (var i = 0; i < drillPickObjs.length; i++) {
        var pickedObj = drillPickObjs[i];
        if (pickedObj.id) {
            return pickedObj;
        }
    }
};

var handleLeftDown = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
handleLeftDown.setInputAction(leftDownFunction, Cesium.ScreenSpaceEventType.LEFT_DOWN);
```

**Comment by hpinkos** [comment] 2019-02-14 16:32
I labeled this `next release` because it's a regression.

@chris-cooper Do you have time to look into this in the next few week?

**Comment by kteneyck** [comment] 2019-02-14 17:17
I should also clarify that this example breaks without pressing a key. You should be able to left down to move the point and left up to release the point in the example.

**Comment by hpinkos** [comment] 2019-02-25 16:28
@kteneyck taking a closer look at this, you're using `ScreenSpaceEventHandler` in a rather unusual way.  I'm not sure why you're creating a new one to handle `mouseup` each time you `mousedown` to drag the point.  Instead, I would use the same handler for both.  See this updated example: 

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider: Cesium.createTileMapServiceImageryProvider({
        url : Cesium.buildModuleUrl('Assets/Textures/NaturalEarthII')
    })
});

var point = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
    point : {
        pixelSize : 10,
        color : Cesium.Color.YELLOW
    }
});

var handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
var aggregator = new Cesium.CameraEventAggregator(viewer.scene.canvas);

var pickedCartesian = function() {
    var scene = viewer.scene;
    viewer.scene.screenSpaceCameraController.enableInputs = false;
    var ray = scene.camera.getPickRay(aggregator.currentMousePosition);
    return scene.globe.pick(ray, scene);
};

var leftDownFunction = function(movement) {
    var pickedPoint = getPickedPoint(movement.position);
    if (pickedPoint !== undefined) {
        viewer.clock.onTick.addEventListener(movePointFunction);
        handler.setInputAction(releasePointFunction, Cesium.ScreenSpaceEventType.LEFT_UP);
    }            
};

var movePointFunction = function() {
    var cartesian3 = pickedCartesian();
    if (cartesian3) {
        var cartographic = Cesium.Cartographic.fromCartesian(cartesian3);
        point.position = Cesium.Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude);
    }
};

var releasePointFunction = function() {
    viewer.clock.onTick.removeEventListener(movePointFunction);
    handler.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_UP);
    viewer.scene.screenSpaceCameraController.enableInputs = true;
};

var getPickedPoint = function(windowPosition) {
    var scene = viewer.scene;
    var drillPickObjs = scene.drillPick(windowPosition);

    for (var i = 0; i < drillPickObjs.length; i++) {
        var pickedObj = drillPickObjs[i];
        if (pickedObj.id) {
            return pickedObj;
        }
    }
};

handler.setInputAction(leftDownFunction, Cesium.ScreenSpaceEventType.LEFT_DOWN);
```

If this doesn't fix your use case, let me know and we can look into this further.

**Comment by cesium-concierge** [comment] 2019-02-25 16:28
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/Iv86c72Yq5g

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7571 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed** 2019-02-25 16:28 UTC
Labels: priority - next release, type - bug

**Comment by kteneyck** [comment] 2019-02-28 18:59
@hpinkos That worked! Thanks!
