### ISSUE TITLE
Ellipse receives unwanted shadow when created with height=0

### ISSUE THREAD

**Issue by tomermoshe** [AnalyticalGraphicsInc/cesium#5732] opened 2017-08-08 06:23 UTC
When creating an ellipse entity with height=0 the ellipse receives what appears to be a shadow:
![image](https://user-images.githubusercontent.com/11088090/29058713-7951cda6-7c1a-11e7-95e9-5b15e758cc3f.png)

When not defining a height or setting it to undefined the shadow is gone but performance drops significantly:
![image](https://user-images.githubusercontent.com/11088090/29058775-cf86ecc4-7c1a-11e7-81ac-02c9053df203.png)

Ive created a simple example in sandcastle that demonstrates the issue:
http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=a82de61d54d42a87288835acd7f76c56

**Comment by ggetz** [comment] 2017-08-08 14:05
Thanks for submitting this @tomermoshe! I believe this may be a duplicate of #1825. Please comment in that issue if you have any additional thoughts. Thanks again!

**Closed** 2017-08-08 14:21 UTC
