### ISSUE TITLE
Cesium Load big data to crash

### ISSUE THREAD

**Issue by 1wobuzhidao** [AnalyticalGraphicsInc/cesium#8459] opened 2019-12-12 02:57 UTC
Load big data to crash.I have a Data that 12G b3dm.when i use Cesium load it ,the chrome hava crash。Do you hava good solution?

**Comment by OmarShehata** [comment] 2019-12-13 18:41
How did you create this tileset? Do you have one b3dm file that's 12 GB large? If your tiles are larger than your system resources then there's no way to successfully load that. 

Closing since we can't debug/fix an issue without a reproducible test case showing a problem with the library. For general questions, or if you're unsure if it's a bug, you can always ask [on the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev).

**Closed by OmarShehata** 2019-12-13 18:41 UTC
