### ISSUE TITLE
The problem was closed without being solved. Hope to get help.

### ISSUE THREAD

**Issue by simonasdmd** [AnalyticalGraphicsInc/cesium#8391] opened 2019-11-14 01:56 UTC
Seriously, I don't want to submit this question again. But this problem hasn't been solved. Hope not to be closed before resolution. Thank you to the cesium community.
Problems that have not been solved [8181](https://github.com/AnalyticalGraphicsInc/cesium/issues/8181)
Everything's in it.

**Comment by OmarShehata** [comment] 2019-11-14 13:01
I'm closing this because I confirmed this is a duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/8053. You'll find a fix here with an explanation of why it's happening: https://github.com/AnalyticalGraphicsInc/cesium/pull/8392

**Closed by OmarShehata** 2019-11-14 13:01 UTC
