### ISSUE TITLE
Sandcastle completely broken in IE

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/cesium#6146] opened 2018-01-23 20:51 UTC
Hello World example in 1.41 doesn't even work.

![image](https://user-images.githubusercontent.com/1652382/35300001-2804405e-0055-11e8-92a1-c8d8ef36b90b.png)

**Comment by pjcozzi** [comment] 2018-01-23 21:23
Sandcastle works for me in IE 11.0.96 on Windows 7 with both Cesium 1.41 and master.

**Comment by mramato** [comment] 2018-01-23 21:47
I can confirm the breakage for me, IE11 on Windows 10, fully patched.

**Comment by tfili** [comment] 2018-01-23 22:06
I'm also on Windows 10.

**Comment by hpinkos** [comment] 2018-01-24 14:30
Works fine for me. Windows 10 IE 11.0.49 Cesium 1.41

**Comment by tfili** [comment] 2018-01-24 14:37
Also failed for @GatorScott. He was the one who originally discovered it.

**Comment by GatorScott** [comment] 2018-01-24 14:37
Fails on Windows 10, IE 11.192.16299.0

**Comment by GatorScott** [comment] 2018-01-27 15:34
I found that performance.now() is returning Infinity in Core/getTimestamp().  I changed Core/getTimestamp() to call Date.now() when this happens and now Sandcastle and Viewer work.  Maybe someone can investigate further as I'm no JavaScript expert.

**Comment by mramato** [comment] 2018-01-27 18:37
Thanks for tracking this down @GatorScott, that's really weird and definitely sounds like a browser bug.  I can't reproduce on my personal laptop, but when I'm back in the office I'll take a look and open a PR that adds some extra validation for calls to performance.now so that we don't use it if it's return value is invalid.  Will be part of the Cesium release on 2/1.

**Closed** 2018-01-29 18:50 UTC
Labels: category - sandcastle, priority - next release, type - bug
