### ISSUE TITLE
{"bug_type":"288","timestamp":"2019-10-10 09:14:23.10 +0800","os_version":"iPhone OS 12.4 

### ISSUE THREAD

**Issue by tyit** [AnalyticalGraphicsInc/cesium#8270] opened 2019-10-10 01:26 UTC
Hello, I have the same problem.
![image](https://user-images.githubusercontent.com/31933126/66531904-04a70600-eb40-11e9-85b8-98a301cb317b.png)

**Comment by OmarShehata** [comment] 2019-10-10 02:08
I see you posted this in response to this issue: https://github.com/AnalyticalGraphicsInc/cesium/issues/4279#issuecomment-540281614

* What example is giving you this error? Do any of the examples on Sandcastle (https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) work for you?
* Can you post the output of WebGL Report https://webglreport.com/ ?

**Comment by OmarShehata** [comment] 2019-12-13 18:54
Closing since we don't have a reproducible test case and enough information to take any action here.

**Closed by OmarShehata** 2019-12-13 18:54 UTC
