### ISSUE TITLE
Imagery feature picking only works in 3D

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2115] opened 2014-09-06 13:45 UTC
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Web%20Map%20Service%20(WMS).html&label=Beginner

**Comment by tlpinney** [comment] 2015-02-11 20:43
This occurs because the pickedPosition is coming back undefined in 2D mode. 

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/ImageryLayerCollection.js#L365-L370

It may also be related to the issue #2480

**Comment by mramato** [comment] 2015-07-23 14:05
This recently came up [on the forum](https://groups.google.com/d/msg/cesium-dev/8o52AWvOh-o/E9q6J0l9T38J)

**Comment by kring** [comment] 2015-07-24 01:40
I'm happy to look at this if it's specific to imagery layers, but it seems pretty clear it's a general `globe.pick` doesn't work in 2D, as described in #2480, right?

**Comment by hpinkos** [comment] 2015-07-24 02:16
@kring yeah, I was looking at this a tiny bit earlier today, and `globe.pick` is definitely the problem.  It returns `undefined`.

**Comment by mramato** [comment] 2015-10-14 22:38
Closing since this is a dupe of #2480

**Closed by mramato** 2015-10-14 22:38 UTC
Labels: bug
