### ISSUE TITLE
Error using Ionic Capacitor on iOS

### ISSUE THREAD

**Issue by stripathix** [AnalyticalGraphicsInc/cesium#8405] opened 2019-11-18 19:14 UTC
On iOS i get thi error.

<img width="214" alt="Screenshot 2019-11-19 at 12 42 16 AM" src="https://user-images.githubusercontent.com/8480351/69082161-8b1b0580-0a65-11ea-834f-dfddab93dc2a.png">

To load in my index.html i have below files
```
<script src="https://cesium.com/downloads/cesiumjs/releases/1.63/Build/Cesium/Cesium.js"></script>
    <link href="https://cesium.com/downloads/cesiumjs/releases/1.63/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
```

Vue component looks like:
```
Cesium.Ion.defaultAccessToken = 'eyJhbGciOiCI6IkpXV*************eD6J--cH1eE28r6gE';
                       var viewer = new Cesium.Viewer('three-globe');
```

In web it renders fine but on iOS it crashes.

**Comment by OmarShehata** [comment] 2019-11-19 00:35
I wasn't able to reproduce this on the latest iOS, testing on an iPhone and an iPad pro.

Are you able to reproduce this on your iPhone using [Sandcastle](https://sandcastle.cesium.com/index.html?) ?

**Comment by stripathix** [comment] 2019-11-19 12:44
I am running it as a hybrid mobile application. Using a capacitor which is similar to Cordova.

https://github.com/ionic-team/capacitor

**Comment by OmarShehata** [comment] 2019-11-19 16:40
@stripathix can you confirm that CesiumJS loaded on the web on your iOS device does not crash? 

Additionally, it would be helpful to test the crash again loading the unminified Cesium source instead:

```
https://cesium.com/downloads/cesiumjs/releases/1.63/Build/CesiumUnminified/Cesium.js
```

Which will produce a more meaningful stack trace.

**Comment by stripathix** [comment] 2019-11-20 04:15
@OmarShehata using minified cesium I get below stack trace
![image](https://user-images.githubusercontent.com/8480351/69208666-711f1700-0b7a-11ea-928b-408acd55da55.png)

**Comment by OmarShehata** [comment] 2019-11-20 14:05
@stripathix it sounds like it may be a specific issue with how Capacitor is wrapping the web view for iOS. Did you get a chance to test if this was a recent problem? For example, if you load CesiumJS version 1.61 or 1.60 does it also crash?

Can you share a minimal template with a Cesium viewer in Capacitor we can use to reproduce this issue?

**Comment by stripathix** [comment] 2019-11-20 19:15
@OmarShehata I am seeing this on iOS Simulator also.

Here is the minimal code required that contains Cesium example with a bug wrapped with capacitor
https://github.com/stripathix/ionic-vue

After debugging more I found that if we install any plugin in capacitor for example in package.json (`"cc.fovea.cordova.purchase": "7.4.3",`)then cesium crashes. If i remove plugin and do `npx cap sync` then cesium runs fine. I dont understand what a cordova plugin does to cesium. It is not related to specific plugin i think because i have tried few other plugins also. Then also cesium crash.

**Comment by stripathix** [comment] 2019-11-23 11:10
Hi @OmarShehata, did you got a chance to look into this.

**Comment by boozedog** [comment] 2019-11-28 22:32
I'm interested in a resolution to this problem as well please!

**Comment by OmarShehata** [comment] 2019-12-14 19:17
Thanks for the additional information @stripathix . I wasn't able to run the supplied project because it looks like it requires Xcode, but based on the finding here:

>  If i remove plugin and do npx cap sync then cesium runs fine

It sounds like this is an issue with the Ionic/Cordova environment, not with CesiumJS itself. I'm going to close this since we don't have enough information to take an action on the library side here, but if you can isolate it further/or have a suggested fix we'd happily review a pull request here. Feel free to also continue the discussion [on the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) as well.

**Closed by OmarShehata** 2019-12-14 19:17 UTC
Labels: category - tooling, type - bug

**Comment by stripathix** [comment] 2019-12-15 19:20
I have reported it to the capacitor.

**Comment by stripathix** [comment] 2020-06-03 00:27
Ref: https://community.cesium.com/t/is-anyone-able-to-make-latest-cesium-work-with-cordova-or-capacitor/9601/4
**Solution**: Thanks @OmarShehata 
var viewer = new Cesium.Viewer('cesiumContainer', {
                fullscreenButton: false, 
            });
