### ISSUE TITLE
Entity API can't control material translucency

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2871] opened 2015-07-07 02:04 UTC
For example, all image materials are translucent and there's no way to specify you want a solid image.

via [the forum](https://groups.google.com/d/msg/cesium-dev/FiF_xXJShLE/SOk5bUpRzkMJ)

**Comment by hpinkos** [comment] 2015-10-14 21:15
duplicate of #2484

**Closed by hpinkos** 2015-10-14 21:15 UTC
Labels: bug
