### ISSUE TITLE
Alpha texture is extra bright in IE

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#3651] opened 2016-03-01 14:33 UTC
The screenshots here are Chrome first then IE. 

![alpha2](https://cloud.githubusercontent.com/assets/915398/13429847/2d54219c-df90-11e5-9a12-40bfdf44b4ca.JPG)
![alpha1](https://cloud.githubusercontent.com/assets/915398/13429845/2c21903e-df90-11e5-832f-f47e58ec0ff7.JPG)

**Comment by mramato** [comment] 2016-03-01 14:35
This is a long standing issue and dupe of #2106 (I don't think anyone has ever looked that closely into it, maybe it's an easy fix).

**Closed by mramato** 2016-03-01 14:35 UTC
