### ISSUE TITLE
Tilt map scroll wheel zoom in, sometimes jump

### ISSUE THREAD

**Issue by bicealyh** [AnalyticalGraphicsInc/cesium#3672] opened 2016-03-06 03:54 UTC
In the eastern hemisphere with terrain data, when  tilt the map， and then  scroll wheel zoom in, it will jump sometimes.

**Comment by hpinkos** [comment] 2016-03-08 21:10
Hi @bicealyh.  Can you please provide some more details?  I'm not able to reproduce this problem.
Thanks!

**Comment by hpinkos** [comment] 2016-10-12 21:12
I think this is a duplicate of #3037.  If not, feel free to comment with more information so we can look into this.  Thanks!

**Closed by hpinkos** 2016-10-12 21:12 UTC
