### ISSUE TITLE
Reprojected ImageryLayers cause a crash if show is toggled before the tiles have loaded

### ISSUE THREAD

**Issue by denverpierce** [AnalyticalGraphicsInc/cesium#3832] opened 2016-04-12 16:50 UTC
![image](https://cloud.githubusercontent.com/assets/5432027/14468259/88bd0d8e-00a4-11e6-86cd-efade0a0ac4c.png)

To reproduce, run the below in sandcastle 1.20, and zoom/pan until you get an uncached tile:

[https://gist.github.com/denverpierce/72179dce5bbfd850df3c356f9df07ba6](
https://gist.github.com/denverpierce/72179dce5bbfd850df3c356f9df07ba6)

This only happens with layers that require reprojection from webmercator and retrieving tiles from a 'slow' server and toggling the ImageryLayer's show property quickly.

**Comment by hpinkos** [comment] 2016-04-12 17:03
Thanks for the code sample @denverpierce!   
I can confirm that this crash happens in 1.20 but it looks like it has already been fixed in master.  
If you are still seeing this problem in 1.21, please reopen this issue.  Thanks again!

**Comment by denverpierce** [comment] 2016-04-12 18:58
Still happens in 1.21 7fc81f7 consistently.

![image](https://cloud.githubusercontent.com/assets/5432027/14471789/cb0ecf86-00b5-11e6-9472-7bcb11f3fd13.png)

I mainly get it when loading tiles that are not in the browser cache, and it's very easy to trigger when loading tiles from a server that is particularly slow. 

P.S. gist loading is great.

**Comment by denverpierce** [comment] 2016-04-12 19:04
Not sure if I can reopen this, but here's a gif of it in 1.21:

![ss](https://cloud.githubusercontent.com/assets/5432027/14472140/58b960ca-00b7-11e6-8a27-e38dbcb2bcff.gif)

**Comment by hpinkos** [comment] 2016-04-12 19:06
Thanks @denverpierce.  I didn't let it run for long enough.  It insta-crashed for me in 1.20 but not in master.  I can confirm this is a still a problem though, so I re-opened the issue.

**Comment by hpinkos** [comment] 2016-09-09 20:31
@denverpierce are you able to still reproduce this one?  I think we may have actually fixed it this time.  I let it run for like 2 or 3 minutes and it didn't crash for me.  In 1.21 it crashed in like 20 seconds

**Comment by mramato** [comment] 2016-09-09 20:36
@hpinkos that's caused I fixed this in #4258 :smile: Didn't realize this bug existed since it is a dupe of #4083

**Comment by mramato** [comment] 2016-09-09 20:36
Of @denverpierce if you are still having an issue, please re-open this.

**Closed by mramato** 2016-09-09 20:36 UTC
Labels: bug

**Comment by denverpierce** [comment] 2016-09-09 22:52
Yeah I haven't checked it, but fairly certain its the same as #4083
