### ISSUE TITLE
Core/GoogleEarthEnterpriseMetadata missing ThirdParty/pako_inflate

### ISSUE THREAD

**Issue by EvaldasVasiliauskas** [AnalyticalGraphicsInc/cesium#5278] opened 2017-05-03 16:22 UTC
After upgrading cesium to 1.33 on existing angular project I get an error, and map does not load:
 
Core/GoogleEarthEnterpriseMetadata missing ThirdParty/pako_inflate

**Comment by hpinkos** [comment] 2017-05-03 16:56
Hello @EvaldasVasiliauskas,

I'm not sure what would be causing that problem, but it looks like `GoogleEarthEnterpriseMetadata` wasn't actually using that function anyway.  I removed this require in this pull request: https://github.com/AnalyticalGraphicsInc/cesium/pull/5280

If you're still having issues after that is merged you can re-open this issue.  Thanks!

**Closed by hpinkos** 2017-05-03 16:56 UTC

**Comment by EvaldasVasiliauskas** [comment] 2017-06-05 10:33
After updating to 1.34 I get kind of similar error (probably somewhere else than before):
Cesium missing ThirdParty/pako_inflate

**Comment by mramato** [comment] 2017-06-05 13:28
@EvaldasVasiliauskas can you provide a complete example that demonstrates the problem? We are unable to reproduce this on our end.
