### ISSUE TITLE
Matrix4 inverse fails on render

### ISSUE THREAD

**Issue by adday** [AnalyticalGraphicsInc/cesium#7923] opened 2019-06-07 21:29 UTC
I am using Cesium 1.49.0 in an application that renders many primitives. In the course of rendering these items I sometimes (not easily reproducible) encounter the runtime error thrown when the determinant of the Matrix4 is zero (<epsilon) "RuntimeError('matrix is not invertible because its determinate is zero.')".

I have traced this error to find that inverse is being performed through AutomaticUniforms, called from Shader.js. As such, I believe this is a fairly deep webGL issue and is not simply the result of the data that I am presenting but also depends on the view that I have in Cesium.

Can anyone shed any light on this? In particular, have you encounter this or similar issues and what was the resolution? Do you feel this is something I could circumvent by checking my data (again I am not calling the inverse)? Would it be appropriate to return a pseudo-inverse from Matrix4.inverse()? Would updating to the latest Cesium (1.59.1) fix this?

Any input would be greatly appreciated! Thank you!

**Comment by OmarShehata** [comment] 2019-06-10 13:23
> Would updating to the latest Cesium (1.59.1) fix this?

This would be worth trying just to rule this out. Another thing that would be helpful is providing a full unminified stack trace. Ideally a reproducible code example, but the stack trace may at least help narrow this down.

It would also help if you explain a bit more what's happening when the crash errors. Is it always when the camera is moving? When adding/removing primitives? When the primitives are moving? What matrix exactly is non-intervible? Is it always the same matrix?

**Comment by Farrelltg** [comment] 2019-07-04 22:02
We are getting something very similar after attempting to upgrade from Cesium (1.43) to Cesium (1.59), however it happens reliably and is not the result of moving the camera. The weird thing is that I can't reproduce it with the unminified build, but I am able to track it down to a call from the `GeometryPipeline.transformToWorldCoordinates` function to the Matrix4.inverse function when the determinant is zero (< epsilon). The error happens every time we call the Cesium.Viewer constructor and it is always the same: "RuntimeError('matrix is not invertible because its determinate is zero.')"

@OmarShehata I am new to Cesium and am only trying to perform the upgrade, so I don't know a whole lot about how things work. Here is the minified stack trace that gets dumped (though that may not help):

> Cesium.js:558 An error occurred while rendering. Rendering has stopped.
RuntimeError: matrix is not invertible because its determinate is zero.
Error
    at new t (http://localhost:52382/lib/Cesium/Workers/combineGeometry.js:59:137)
    at Function.l.inverse (http://localhost:52382/lib/Cesium/Workers/combineGeometry.js:59:13337)
    at Object.te.transformToWorldCoordinates (http://localhost:52382/lib/Cesium/Workers/combineGeometry.js:61:26760)
    at d (http://localhost:52382/lib/Cesium/Workers/combineGeometry.js:62:1753)
    at m (http://localhost:52382/lib/Cesium/Workers/combineGeometry.js:62:2524)
    at Object.O.combineGeometry (http://localhost:52382/lib/Cesium/Workers/combineGeometry.js:62:5282)
    at r (http://localhost:52382/lib/Cesium/Workers/combineGeometry.js:62:10140)
    at http://localhost:52382/lib/Cesium/Workers/combineGeometry.js:62:9606

@adday Did you ever figure out what was causing this?

Thank you ahead of time for your time and help.

**Comment by OmarShehata** [comment] 2019-07-05 14:53
@Farrelltg I appreciate you reporting this and adding the additional information here. It's good news that you're able to easily reproduce it now. Are you able to trace this back to what line in your application causes it? I think you won't be able to identify the line from a stack trace because the geometry is created asynchronously in a worker. 

But you can either remove chunks of code until you can isolate which one's presence causes the issue, or set your geometry to be synchronous. This is a constructor flag if you're using the Primitive API or you can replace `this._asynchronous = defaultValue(options.asynchronous, true);` with `this._asynchronous = false` in [Primitive.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/fbc4a02c85dd4e03f2616c06eaab92e3694f3836/Source/Scene/Primitive.js#L291) and [GroundPrimitive.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/GroundPrimitive.js#L271) to force all created geometry to be synchronous.

**Comment by Farrelltg** [comment] 2019-07-05 23:29
@OmarShehata Thank you for your help! I was actually able to narrow it down today. Our app is offline and uses Natural Earth textures for rendering. The problem was on our end. We refactored some typescript code and the relative path that was being used to resolve the textures for the TileMapServiceImageryProvider url stopped working. After switching the relative path out for the Cesium buildModuleUrl function (which the @types\cesium typings won't pick up some reason), everything resolved itself. 

For future reference, it appears to be related to a subtle issue where--at least in offline scenarios--the TileMapServiceImageryProvider looks for .png files by default. So even though the path and file names were being resolved correctly via the relative path url, they failed to render because they had .jpg extensions.  Hopefully this helps someone in the future.

**Comment by hpinkos** [comment] 2019-09-19 20:41
I'm going to close this issue, but if you're still having trouble, feel free to post on our forum and we'll be happy to help https://groups.google.com/forum/?hl=en#!forum/cesium-dev

**Closed by hpinkos** 2019-09-19 20:41 UTC
