### ISSUE TITLE
Cesium Loads Too Many Tiles

### ISSUE THREAD

**Issue by bbehling-trimble** [AnalyticalGraphicsInc/cesium#7042] opened 2018-09-14 18:22 UTC
When in 3D mode, Cesium requests > 300 tiles per aoi, where as in 2D mode, the same aoi requests 6 tiles.

Our concern is that this will get quite costly for ALK and Digital Globe tile requests. Sean said this may have been a bug introduced in a pull request.

**Comment by bbehling-trimble** [comment] 2018-09-14 20:01
@hpinkos yes

**Comment by lilleyse** [comment] 2018-09-14 20:02
This is the PR I was referring to: https://github.com/AnalyticalGraphicsInc/cesium/pull/4969.

It would be interesting to get the before and after numbers. It will also be helpful to measure how many tiles are loaded vs. how many are used for rendering at some point to see if any are loaded unnecessarily.

@kring has also been working on adding LOD skipping to the globe loading code. This has the potential to save a large number of tile requests.

**Comment by hpinkos** [comment] 2018-09-14 21:04
@lilleyse I'm not sure, but I don't think that would effect imagery requests.  It was more for terrain.

**Comment by pjcozzi** [comment] 2018-09-15 18:55
@bbehling-trimble thanks for the report and the concrete numbers.  Could you please try this before and after #4969 as @lilleyse suggested?  I _think_ that will image the number of imagery tiles loaded.

It is still very much a work-in-progress, but you could try the LOD skipping that @lilleyse mentioned in this branch to get some early numbers: https://github.com/AnalyticalGraphicsInc/cesium/tree/fill-tiles

You can, of course, also increase the `maximumScreenSpaceError` to load fewer tiles, but it will also decrease visual quality. https://cesiumjs.org/Cesium/Build/Documentation/Globe.html#maximumScreenSpaceError

By the way, what is ALK?

Finally, if you are concerned about paying per imagery tile.  Check out Cesium ion, which uses Bing imagery, which is billed per session (basically creating a Cesium Viewer widget): https://cesium.com/pricing/

**Comment by bbehling-trimble** [comment] 2018-09-17 17:11
Just to make sure we are on the same page, the extra tile requests I'm referring to are imagery tiles, not terrain tiles.

**Comment by NaderCHASER** [comment] 2018-09-20 17:33
At zoom-level 6 with the same viewport location and size, we see 16 requests instead of 46. This is a huge improvement for us given our tiles are generated on-demand from massive meteorological datasets.

![dnejcvcu8aat3vv](https://user-images.githubusercontent.com/913068/45835830-59bf7200-bcc8-11e8-8c93-d8cf8d317414.jpg)

**Comment by hpinkos** [comment] 2018-09-20 17:35
@NaderCHASER this is with the change from #4969?

**Comment by NaderCHASER** [comment] 2018-09-20 17:39
@hpinkos I meant to clarify that this is from the fill-tiles branch. My apologies.

**Comment by bbehling-trimble** [comment] 2018-09-20 18:05
@NaderCHASER Have you tested that fork in 3D mode and looked at Bing tile imagery requests?

**Comment by NaderCHASER** [comment] 2018-09-20 18:07
@bbehling-trimble My screenshot is from 3D mode, albeit zoomed in quite a bit (zoom-level 6). I do not use Bing at all, so I can't test that. Otherwise, my imagery tile requests should be pretty similar on this branch. However, this branch breaks on zoom / pan (fatal error), so this isn't ready for use outside of development.

**Comment by kring** [comment] 2018-09-21 07:30
@bbehling-trimble you can try the `fill-tiles` branch yourself here:
http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fill-tiles/

The problem @NaderCHASER mentioned where it crashed when panning should be fixed (I believed it only occurred when using heightmap terrain or the ellipsoid instead of a quantized mesh terrain source). 2D and Columbus View won't work at all, and there are likely to be other bugs, but if you see a crash just browsing around in 3D, please let me know.

**Comment by NaderCHASER** [comment] 2018-09-21 14:06
@kring It locks up with CesiumEllipsoidTerrainProvider. Cesium World Terrain appears to work fine.

![screen shot 2018-09-21 at 8 04 44 am](https://user-images.githubusercontent.com/913068/45885988-1e2eb180-bd75-11e8-9876-7dab9042975b.jpg)

**Comment by bbehling-trimble** [comment] 2018-09-21 15:40
@pjcozzi ALK is one of the a map providers we get our imagery and road layers from

**Comment by bbehling-trimble** [comment] 2018-09-21 19:15
@pjcozzi experimenting with the maximumScreenSpaceError, I really don't see a difference in the amount of tiles loaded until a setting of about 8. At that point, the tiles are start to get quite blurry and 100-200 requests are made, which are still very many requests. Thats looking at a mountains area. Flat areas seem to make ~50 requests.

**Comment by bbehling-trimble** [comment] 2018-09-21 19:27
Using the fill-tiles branch, navigating around a mountainous area such as Vail at an oblique angle, the max tiles loaded are ~150. Average tile requests seem to be 60 - 120. Nadir view 10-20 requests.

**Comment by kring** [comment] 2018-09-22 01:54
@NaderCHASER that was a bug early yesterday, but I thought I had fixed it. I certainly can't reproduce it now. Are you sure you're in sync with the latest in the `fill-tiles` branch? Are you doing anything in particular when it happens?

**Comment by NaderCHASER** [comment] 2018-09-22 13:58
@kring I re-based and everything seems to be working fine now. Thanks and please accept my apologies for the false alarm!

**Comment by mramato** [comment] 2019-08-16 14:08
fill-tiles was merged a while ago so this is OBE

**Closed by mramato** 2019-08-16 14:08 UTC
