### ISSUE TITLE
Imagery Layers Split has IDL issues in 2D

### ISSUE THREAD

**Issue by gongzk** [AnalyticalGraphicsInc/cesium#5106] opened 2017-03-15 11:03 UTC
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Imagery%20Layers%20Split.html&label=Showcases

If you scroll the 2D map so the IDL is in the center of the screen, the split imagery no longer lines up with the screen divider

**Comment by hpinkos** [comment] 2017-03-15 12:31
Hello @gongzk, the demo worked fine for me in 2D.  What OS and browser are you using?

**Comment by gongzk** [comment] 2017-03-16 03:02
Google Chrome 56.0.2924.87 m
to 2D mode is ok,but 
after pan and drag the map(as 180 E line in map) ...





在 2017-03-15 20:31:43，"Hannah" <notifications@github.com> 写道：


Hello @gongzk, the demo worked fine for me in 2D. What OS and browser are you using?

**Comment by hpinkos** [comment] 2017-03-16 12:41
Ah, thank you @gongzk.  I updated the comment for this issue.  The layer splitter seems to have trouble with the international date line, which is where we stitch the 2D map together for infinite scrolling

**Comment by pjcozzi** [comment] 2017-03-18 00:31
@jasonbeverage if you have time, this one could be of interest to you.

**Comment by jasonbeverage** [comment] 2017-03-18 01:20
I see that.  I didn't realize that the 2D view did this multiple viewport infinite scrolling thing :)  On first glance it looks like you might be able to adjust the imagerySplitPosition in execute2DViewportCommands based on the offset before you actually execute the commands.

**Comment by jasonbeverage** [comment] 2017-03-20 01:30
@pjcozzi the issue is that I'm using the width of the viewport to scale the imagerySplitPosition to fragment coords.  This assumes that the viewport width is always the same width as the full canvas.  This is the offending line:
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/GlobeFS.glsl#L102

If I change the czm_viewport.z to be the hardcoded width of the canvas in the sandcastle example (1135.0 for me) then it works correctly in all cases that I can see.

A couple of ways to fix this:
1)  Require that imagerySplitPosition is in absolute coordinates and just use it directly.
2)  Have two different split positions in UniformState.  A relative 0 to 1 that is settable and a computed one that feeds the actual uniform value based on the relative one and the canvas width.
3)  Pass a uniform with the canvas width to the GlobeFS shader.

I'm more of a fan of 1, what do you think?

**Comment by pjcozzi** [comment] 2017-03-27 23:37
Thanks again for the report, @gongzk!

Fixed in #5151 by @jasonbeverage.

**Closed** 2017-03-27 23:36 UTC
Labels: bug
