### ISSUE TITLE
KML sandcastle demo really slow in IE

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4415] opened 2016-10-07 17:53 UTC
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/ko8w1DEhjgU

This is especially slow in loading the second GDP example.  The user says when toggling between the first and second example he expeienced an out of memory error after a few times.

http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=KML.html&label=DataSources

**Comment by mramato** [comment] 2016-10-07 18:00
IE11 has known memory leaks that Microsoft has officially closed as "won't fix" since IE is in the barest of support mode.

Same issues with performance, while the KML demo overall could use performance improvements, IE will always be significantly slower than other browsers.  Our official recommendation is don't use IE11 unless you absolutely have to.

That all being said, we can do a pass here to see if any obvious problems pop up, but I don't expect any miracles to happen and more likely than not; it's just IE being IE.

**Comment by mramato** [comment] 2016-10-19 20:01
Looking into this the core of the problem is that the clampToGround code basically takes forever.  This is partially because IE is incredibly slow and partially because our code has some inefficiencies and bugs which are covered by other issues and will get addressed this wee at the bash.

However, clampToGrond shouldn't even be happening for this demo because it defaults to false.  It turns out that we are not taking this setting into account when handling KML labels and billboards, so I'm going to open a PR to fix that issue which will allow us to close this.

**Closed** 2016-10-20 15:26 UTC
Labels: bug, bug bash
