### ISSUE TITLE
HDR colors polylines with PolylineColorAppearance and PolylineMaterialAppearance differently

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7920] opened 2019-06-07 20:01 UTC
[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1VZRT9swEP4rVl/aSp0DhQqNFTQoCB6AVh3bHpY9uMm1sXDsyHZaBcR/3zkJtJQM0gEP81Nyvu9y933ni+dMkzmHBWhyQCQsyAAMT2P6I7e1mkH+OlDSMi5BN9tffOl5BYKaACTQiM+ik0yymAdjJmeAgaZMGEBPX84xvobwAsFoL3EgLbccDGVh2LrzJcGFeCD7pDmGkAjnrSSxoDV+ttkpXBIlsnxrn5SgwmowmJIGzWXyA6YtPjG5Q6daxScw0wDmCINlrV+f9nodstPrLCNsuj5td/MQv9srQRY8tBGmsBo4ZlgBZ2IlMyWUpsPx0dXZ6YpjIFicXKszrVIZorfVKRS79768bz8y6eqQ4yiNJ/UJPXMYoh0oJ/a/ZZPp4DpLYJnYUWGg4/Pvl8e1aa/kVagFl7MNSC0AZCJSWLZrBMSkesqCDyF57+0k71WSvL1VTd7KOBiVdbi6L0uPkVYJaJu17p7m5cgcKTdR9skW7a5lbRmCltvrnRM4pV4SLhevXSWi0m76DFPrEg3r6TjMMYWCC45sTAQLbogqghBmSQQ43ixheC6nSpSyf5DS5/m3zIPgnzuk29vC9Qbhn+r/GHGT0VXRBiXJr3XCC2KulVQS/rPMpFu9Pfj35khSnQhAltWiXmeMcgAxFv9AeQPk0MeG+DjZd3c6JNfo3WRfRnz9+P91yF4Nr05r90fO87PuqJCtUquQmWiTK8OxG8IF6N3/cGva9N5dm96L2uzWpvwE6691Hjc/PoUCt0rF16q1podzaXQafWMzAYcF9CuPE6UtSbVoUepZiBOBmRlvkgY3YGlgcljfewD1Qz4nPDzwG2vXTb/hrkbG4M40FeIbvwW/cdj30P8JTCgW4lwezkELljmXaPvwojBSSvsevj5HWaXEhOmViH8A)

highDynamicRange = true:
![image](https://user-images.githubusercontent.com/3451886/59130308-1c297480-893d-11e9-8127-17b858cd4950.png)

highDynamicRange = false:
![image](https://user-images.githubusercontent.com/3451886/59130331-2481af80-893d-11e9-8b38-486a7c9ac1a2.png)

I kind of feel like HDR shouldn't be hitting primitive types like this where the user is defining a color.  If I tell a polyline to be white, I want it to be white, not gray.

**Comment by mramato** [comment] 2019-06-07 20:30
You labeled them both as HDR=false.

**Comment by hpinkos** [comment] 2019-06-07 20:36
> You labeled them both as HDR=false.

Shhhhhhhh.....

I updated the initial comment. The first one is with hdr enabled

**Comment by emackey** [comment] 2019-06-07 21:15
Not sure I understand.  Did we want them to be the same?  I think HDR enables tone-mapping of colors almost across the board.

That said, the current look of PBR-enabled models is pretty bad these days.  The glTF sample "Water Bottle" model looks plastic instead of aluminum.  It wasn't that way a couple releases ago, not sure when it changed (I could bisect it, but I'm sure it would be some recent intentional HDR upgrade).  I think the problem there is that people are fine-tuning the lighting/color balance to be optimal for a bunch of solid-white 3D Tiles buildings, and not testing with full PBR models.  The two are almost mutually exclusive, they probably should have different shaders or render paths.

Anyway I'm way off topic here.  Do we expect the lines to be exactly the same color, with and without HDR?  I think they would need to be always excluded from tone-mapping in such a case.

**Comment by hpinkos** [comment] 2019-06-07 21:27
From the perspective of someone with little to no idea of how HDR actually works, I think it's weird that the line I'm setting to `Color.ORANGE` doesn't look orange when HDR is enabled.  I know it has also confused users with billboards wondering why they're a completely different color on the globe than in their .jpg files.  But that's a slightly larger scoped problem than I meant to bring up in this issue.

The main problem here is that I set `Color.ORANGE` to all the polylines in the picture, but when HDR is enabled the bottom two polylines are a completely different color than the other polylines.  I don't understand why the arrow material and the dashed line aren't the same color as the regular polyline color material.

**Comment by emackey** [comment] 2019-06-07 21:36
Oh I see, with HDR enabled the ones on the ground are not the same as the ones at altitude.  I was comparing HDR with non-HDR and I didn't spot that before.

That does seem like a bug.  I wonder if tone-mapping is only applied to one set and not the other?  That particular shade of orange is susceptible to having its hue changed by both tone-mapping and gamma correction, because only one of the three color channels is in a middle range, the others are zero and one.

**Comment by hpinkos** [comment] 2019-06-07 21:45
The ones on the ground are using a `PolylineColorAppearance` and the other ones are using a `PolylineMaterialAppearance`.  My guess is it's something related to that.

**Comment by lilleyse** [comment] 2019-06-08 14:57
This was a case of missing `czm_gammaCorrect` in those polyline shaders. Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/7924.

As for HDR, IBL, PBR for models, part of the problem is the procedural lighting is just too bright: https://github.com/AnalyticalGraphicsInc/cesium/issues/7803.

**Closed** 2019-06-10 20:46 UTC
Labels: category - graphics, type - bug
