### ISSUE TITLE
Polyline flickering when there is only one in the collection

### ISSUE THREAD

**Issue by tangtony** [AnalyticalGraphicsInc/cesium#7872] opened 2019-05-28 14:05 UTC
When updating the position of an entity (with a polyline) in a collection that contains only one entity, the polyline will flicker when updating.

This goes away if a second entity (with a polyline) is added to the collection.

Sandcastle example: 
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=5VNNT+MwEP0ro1xI2eC0qjgAabWrUnFBIJWPC+HgJtPWwh+V7aQqq/53xkmrBriw5/XJ8zLved7TpOYWaoEbtDACjRuYoBOVYs8NFp8UTTkx2nOh0Z70rnKd65pYFstbgojW8hlqL7xAx3hZxn9zDXTWRm5l6LqEPdKijjqNdgTv35tw6+nG9ZAtrFHXuLSI7o+1fBu/nF30ExieJ0eFfz1ng34j8drriGxE6Vc0QldYcY9WcNmZzEhj2Wx63Tbtcr1rQ0hTeNKFUSoY10vwK+HAebN2dMWQDzTWgx9YSFG8kbJeEvE05BcM6tmqUvP/KMab2XR61w3yNG32qbX+box6NPGXII4rJyil4TmVi0oXwTkoU2OIL+4dgtmvJTtExo4pjX6ekkj2XsWvUZ8NXsMMQd2hfxQKTeXjw9MJUGM/NOzCnMeJCImSKHN+K3Hc0n8LtTbWQ2VlzFjqUa0lJeXSeUXb4VnhGrdZeiBlpahBlKM8+vIj5hEUkjtHXxaVlA/iHfNonKXU/4kmDS9p6e5rtJJvQ8tqML5tQcZYllL5neWNkXNuO4of

Browser: Chrome 74.0.3729.169 (Official Build) (64-bit)

Operating System: Windows 10

**Comment by OmarShehata** [comment] 2019-06-05 20:17
The flickering is coming from the fact that the entity geometries get re-computed asynchronously. I would say this is a feature, not a bug. (Whether or not we should expose a flag at the entity level to let the developer control whether they want to keep it async or sync is a different question). I wrote a bit more about this in the forum thread here:

https://groups.google.com/d/msg/cesium-dev/5N1P_qPmbPo/rbnHNKFoAQAJ

If you use a CallbackProperty, this will mark the entity as dynamic, and you'll get no flickering. Although I'm not sure why the second entity there makes the flickering going away.

**Comment by cesium-concierge** [comment] 2019-06-05 20:17
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/5N1P_qPmbPo/rbnHNKFoAQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7872 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed** 2019-06-05 20:17 UTC
