### ISSUE TITLE
TypeError: Cannot set property 'geometry' of undefined

### ISSUE THREAD

**Issue by CHBaker** [AnalyticalGraphicsInc/cesium#5947] opened 2017-10-30 18:22 UTC
I'm rendering Cesium with Angular-Cesium. But this problem also occured when just running Cesium.js, which is Why I'm also posting here.

I'm rendering a kml stream and updating it every 1.5 seconds. Sometimes, it loads perfectly, no errors, and sometimes I get the error below. this is with no code changes. Also, If I set the interval to 10 seconds, It seems to solve the problem as far as I can tell... But of course, I'm trying to get an interval of 1.5 seconds.

![screenshot from 2017-10-30 12-13-59](https://user-images.githubusercontent.com/14304935/32188114-8939314e-bd6c-11e7-8c04-d911216f468b.png)

My code is really simple, here is my Angular code. Notice the **`AfterViewInit`** hook.
```
export class GlobeComponent implements OnInit, AfterViewInit {
    cesiumViewer;
    options;
    kml$;

    constructor(private viewersManager: MapsManagerService,
                private globeService: GlobeService) {}

    ngOnInit() {
      // console.log(this.cesiumViewer);
    }

    ngAfterViewInit() {
        const viewer = this.viewersManager.getMap('main-map').getCesiumViewer()

        this.options = {
            camera: viewer.scene.camera,
            canvas: viewer.scene.canvas
        };

        this.kml$ = new Cesium.KmlDataSource(this.options);

        viewer.dataSources.add(
        this.kml$
        );

        setInterval(() => {
            this.kml$.load('http://..../rest/kml/accept/all', this.options);
        }, 1500);

    }
}
```

**Comment by hpinkos** [comment] 2017-10-30 18:24
@CHBaker Can you give us an example KML file that causes the error?  Otherwise it's going to be really difficult for us to reproduce

**Comment by CHBaker** [comment] 2017-10-30 18:29
@hpinkos the problem is it's a kml stream, when it was static it worked fine

**Comment by hpinkos** [comment] 2017-10-30 18:41
@CHBaker Gotcha.  It's likely an async problem.  The previous `load` didn't finish by the time you called the next one, and some kind of race condition is happening.  As a workaround, you could try waiting for the previous load to resolve before calling the next one:
``` js
function loadKml() {
    this.kml$.load('http://..../rest/kml/accept/all', this.options)
        .then(function() {
            setInterval(() => {
                loadKml();
            }, 1500);
        }
}
```

It would be really helpful for us to debug if you could share 2 sequential KML files that cause the crash.  Thanks!

**Comment by CHBaker** [comment] 2017-10-30 19:02
@hpinkos hmmm. I tried that, and no error would occur but the kml would not load. I could get it working by  setting a time out of 10 seconds before starting the interval, but that's pretty inconvenient. I'm sorry I do not have permission to share the kml. All I can say is that it plots lines on the glob :/

**Comment by CHBaker** [comment] 2017-11-08 16:15
Is there a better way to lad kml updates than setting an interval, maybe?

**Comment by hpinkos** [comment] 2017-11-08 16:18
@mramato @tfili any ideas here?

**Comment by CHBaker** [comment] 2017-11-08 17:36
hmm, @tfili no I've actually never seen network link functionality, I suppose I could give it a shot.

**Comment by hpinkos** [comment] 2019-09-19 18:38
Closing this since we don't have a way to reproduce the error.  @CHBaker if this is still a problem for you feel free to reopen the issue.

**Comment by NichijouCC** [comment] 2019-10-15 11:58
![image](https://user-images.githubusercontent.com/19320089/66829392-daad7380-ef85-11e9-89b9-48265db547c4.png)
createGeometryResults.length  is > the instances.length ,so alert error.in my debug

**Comment by hpinkos** [comment] 2019-10-15 13:14
@NichijouCC do you have [Sandcastle](https://sandcastle.cesium.com/) code example that reproduces the crash?  I think this might be a geometry error, not an error in PrimitivePipeline

**Comment by arimbey** [comment] 2019-12-17 12:44
I get this too https://github.com/AnalyticalGraphicsInc/cesium/issues/5947#issuecomment-542176295

**Comment by shunter** [comment] 2020-01-23 22:22
Note that this crash has nothing to do with KML or CZML, so much of the above commentary is a distraction.

Here is a Sandcastle that reproduces the crash using the entity layer directly:

[Sandcastle](https://sandcastle.cesium.com/#c=lVPBjtMwEP0VK5d11NbZLiCk3bQCCgckJJBWcGl68CaTdIRjR7aTVUD99x0nbbZlhRA+VOPn92bezDSdtKxDeATLVkzDI9uAw7YWPwaMX+XDdWO0l6jBXsV3mc50RyrQHj2CI912N6FIUWks40j49R1DlrLlNQWzGcbsd6YZnZNUNK3b87G8mEBZFPxIDKcxqldU+5ZdgI7IRjt2e3K8kdZTJPUrUVpTf4TKArj31sqebxdv38wZJjfz5xT/exbLmyHH6138nOQwhoc4zOUQhlC2Og/OmIXadPApdNXzY+s5OTYKhDLVi7ZH/of+c8FP2HZ6VKArv18sdwILqhVqHuuFoRuLFWqpvlmsid/B96aQHmgDx9lMD6KxxhvfNyDagTMtbrxuTKv9sLmA/1NNzFO/vLSyhntP6LTnv/gSsmlUz/0e3ZxJW7U19enCBMe+wi+WjF9YWpGp+PwvcDnfo3jcxxifyWezsJ6hp2gepc73CtYj6x3WjbGetVZxIRIPdaNI5pKHNv8JXuRucJYmJ1FaYMewWGXRH99GFrFcSefopWyVusdfkEXrNCH+hUwZWaCuvnZglewDZb9cfxlBIUSa0PWlyhujHqQ9y/gE)

Now, before you get worked up about how I'm injecting code into `Primitive.update`, let me explain myself...

The root of the crash here is that we are creating geometry on the worker, but while the asynchronous creation is in flight, we delete one of the entities.  Deleting the entity causes the batch to remove the geometry instance here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/3f3576443c700533a978ebd3e3e8c94f0fbb9179/Source/DataSources/StaticGeometryColorBatch.js#L84-L86

Because `Primitive.geometryInstances` is the same array as the batch is modifying, this delete takes effect immediately.  Then, all geometry creation completes for the primitive, and it moves to the next step and asynchronously combines the `createGeometryResults`.

However, the lengths are mismatched - we have more `createGeometryResults` than `geometryInstances` at this point.  `pack` does no validation on the data that it packs, so it ends up sending packed data that crashes `unpack` when it blindly assumes that `geometries` and `instances` are the same length here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/3f3576443c700533a978ebd3e3e8c94f0fbb9179/Source/Scene/PrimitivePipeline.js#L610-L625

So, to reproduce this in the Sandcastle, I need to make sure that the delete happens while it's in the `CREATING` state but before `COMBINING` starts.  Patching `Primitive.update` is a reliable way to make sure it happens after the first time `update` is called.

**Comment by shunter** [comment] 2020-01-23 22:33
I'm not sure which is the right fix.  It seems dangerous for the batch to be directly manipulating the `geometryInstances`.  I'm not sure from reading it whether the batch code was written with the awareness that the array is actually being shared or not.  @mramato any recollections here?

Alternatively we could change `packCombineGeometryParameters` to just discard `createGeometryResults` for which we no longer have a `geometryInstances`.  I guess they are correlated by index in the arrays.  Maybe it needs to be smarter than that, since presumably adding new entities during `CREATING` could happen to, or we could delete then add and end up referencing the wrong geometry instance.  This goes back to the danger of directly manipulating `Primitive.geometryInstances` externally from the batch, I guess.

**Closed** 2020-01-28 20:36 UTC
Labels: category - data sources, type - bug
