### ISSUE TITLE
draw a polygon to clippingPlanes terrain not work sometime

### ISSUE THREAD

**Issue by hemincan** [AnalyticalGraphicsInc/cesium#7999] opened 2019-07-15 07:19 UTC
Sandcastle example: s

[https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=pVhtUxs3EP4rKjMdnyfuYZLQFyCZEuMmTKF4ghOmDRkQd7KtiU66kXQYt8N/7+rtfDobA62/2JZ2V492n12tdIsluqVkTiR6gziZowFRtCrSz3Ys6WT270BwjSknstND6J9LjuCjCCOZpoIf85xmWAuJ9tAEM0V6ToDyiXgn7lqjmkgJpkZS3NKcGB2/YiYJ1uRCSJaPnUzSveT33f1L7gCmDssFzadEpwrkCT8vcUaGt4TrD5jnDIQkKcQtOeZlpQ8tvMTbP28pjBclSU+Gv42vjs4+vTsZXg1Ojge/m+UmFbeayEEaCcp1MjfARkJRM9MNTrgF95VmHrznUYJpkCEqxXmeeDHzKb0u7Diy1WuKGEt7qKFlPplgouGogfmbXnw4Hg97sWBJ7wg7p38TEN5tzc0Inc70RzIhkvCM1NY+xOPp4OTwdHQ1Prt6//Hs0x9HSyP37qcNiPkhia4kd5hhCKaNM3KJ55RPT0VOwCUdBqTpNF1q5s9nuCRJ8McR1jjypzLTfhE6QUlk8k0w2m16yao8HgLnY7YwBlbd3AySgukmwN6qaMZwUY7FeykqnoO4lhVZIzanuZ7B9Kt46r7h2OBRP0YgWdZv3GCfCv6/9g76a3c+o0Rimc0Wj268gJyQFLO9Zr2wpDz1M5DcJZF6kawyNp1TPTtk5Qwn/fSnbvfJXvF0C+TwdMPAqltiCWXTVIEjvnzdX5n0IxMmsAaXjjxpzdjMFY64/J2vry5JqEQYVJVB6LVTRXSz5gS+J8Ro1/EyUf3OLzE0gVqkqipLIbUaeV6qMx7Kn19MZYSTbhTzDBgqGEmZmCad8YwqdCPFXMEuckEU4kIjb7fmu0KQfb74pp3g3KVnY29vb6MLgiog4nUTRVrS7FsoXNdQUyQwlStNcI7EpJbNcAFkssJDxmipBM2vkRJIz7CuF5gTBIUcxgjsR0o4THwBnM8IR4WoFEQKQTGXNe5lkSBY6llAsmT/KkoXgTRwOmwc1r+ObFxDpjKGbmDXPCcT8FhuwiUqaaHAPp1fHR7APGXihqTLuPqwet0kMh5Hz0ivEDdlhE+hUphE73fbGRoRF7bbPJnilfZjxdV1ykrNNuvYOr7guKDZqK6HUXoMMGM3GJwcEr2u70l3XXHxybsCprXwfc+1Chs2ATiWR0gbZFOvUUqe64NHnQu2AeqjfUXdUPyXMtGiU0SAmE4mXBCbZyQD4fm6fa9ZtmG3u5mUdYaZPX7GrCKR8uO0FGXyRPI+YPf+qcE5Pft0Prw6Pfs8NOpQCT4Swymb1e40hVJFdcclvCcZgggi11xawTBsFdJGhwO1qqAcCOQ4umxtWuezs3XIWL3tzU5Z0n5FLohkUGtHDPMNIutRtOi1WbZhO0i2y1NdQld3tnk2PsTvn5s4bd/vP8qFj8fvP0SZarJJlKHmfVlavjOdeefIEGXk+ijV8d0R/LSXIXPVCcCibFmDK0y1GubQ4jUqzdfoSlKHuHRxrVdp9gR+zuwnuqWoE3/I+L/+0NkPgpALA1v8EJQOAO3F0ESYEzeb2eVLcyyXBsPSehi30Or4WWqAamJEKIz29+HrIMKyj168oGvq2R3EOyd3oJRQ9ALtdNH3sV6sUNA83MPqM0pq+IX5K9sKO90v9GvPm/lSrwFD0dkW9JJuM1AbVygqpmnJFu8W5xlmWCZBuof66W6vVu7Wrg7Aq3KtQS5kgRlc5RqWngDSWJTmQrfWqKputIRsS9Z44FnLPLzEEreV6TnR1W07ubUmMimUCupV+SRAG8wtEblfPS8cYzLMFwUUGKjsVGkMV2F0s0AldC5wWhrGm6JvWW86Qez6VgEoaWtnbmxg84fkNiHi5smlbwDTT/vtANYA3kQqKXTLtj4e+flkzVIPUS1O0Pocrf3VnK6xBSDd1l0s6i9cH7xSAB4yDndB/24UPY44tb0Wzsbtk+RTcmHu0is3bTNjb5iPvJAQjm8YCVf1xmuGPWjO4aDJsNJQQaFcjIWABleeEl4l/jTwvcJfQhRw50FaQEeAMFRLZK605pJg38jU8rnK3YKYEN8OdbJKzIkUxRGZwqGkkh92Xr5MX/Z3f+6h1z+mO7/sQs3Y6fcNOR7i/66d7qH4u9t8L2sCGEvMFRTjIiCBy7qkd6/T46PhH+Pj8Z/OE1u9rQOlF4y8dQ76lRb2GllJlqTptiYFhAogbN9U2Tei00xZxxxsB6WDnN4imr+53Go9HV5umScTpWBmUjH7THW59fZgG+QjNWglTL6dwT2L4YURme28PXGDaZoebMPfVS3tAtaw+C8](url)

![image](https://user-images.githubusercontent.com/32860032/61200280-7e7f4d00-a713-11e9-8d1f-394f810217e8.png)

![image](https://user-images.githubusercontent.com/32860032/61200297-87701e80-a713-11e9-9dab-6792f3311ca1.png)

![image](https://user-images.githubusercontent.com/32860032/61200305-8c34d280-a713-11e9-8117-e9275374aef1.png)

**Comment by OmarShehata** [comment] 2019-07-15 13:09
From first glance it looks like the coordinates or model matrix may not be correctly set up for the clipping plane(s). There's some forum threads that have examples of drawing a clipping plane area, see https://groups.google.com/d/msg/cesium-dev/rRNeE6vQb7g/dOLhS6LXAwAJ and https://groups.google.com/d/msg/cesium-dev/Jgc8BSoCAfc/MSAaJxDJCgAJ.

Feel free to start a new forum thread if you're still having issues and I'd be happy to take a look there. We  try to keep GitHub issues specifically for bug reports and feature requests.

**Comment by cesium-concierge** [comment] 2019-07-15 13:09
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/rRNeE6vQb7g/dOLhS6LXAwAJ
https://groups.google.com/d/msg/cesium-dev/Jgc8BSoCAfc/MSAaJxDJCgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7999 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed** 2019-07-15 13:09 UTC

**Comment by hemincan** [comment] 2019-07-16 01:34
I am so sorry I cant find my answer from your link，Look at the example below, the same code has different polygons, but one can clip, one can't.
[see this Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lVftb5s4GP9XrEqnES1zwLwYsm66ra22SrtdtUY3nZZ9cMFJrDkYGZM2m/a/3wOGFNK0l/IlYD/vz+95yYZptBH8lmv0BuX8Fp3xUlRr/E9z5rxIm88zlRsmcq5fjBH6Nc8RPCWXPDVC5Zd5JlJmlEZTtGCy5GNLIPKFeq/u9k4N1xpEXWm1ERmveVqNqebM8K9Ky2xmaZzRPP89ej3P5/miyhtdKJWiuJIs506hRG7KUWsNQqnKSyU5lmrZ3XVX1kHMcyOM4CXWfK02/J2UTi39IAnLMmcn+vBTKLldqnyK/oeuoeX6SpWiduEjF8uVGQblqWcyQaoyEqI/RUZXz2M5U1LpXYibL/zl4vwIGa2AryIzqyny3CNYVoJrptPVdopsAo7gSSVbFzP1Qasqz452cA1I0YLJaR+yjXd/tTeAL4i52ToD1z98ubj4jG+FWb2TxYo5Lo5Ho6fV/X78+neHng0UkfX4E8+XZgWlZD+xbL4bCLeJOWtgjlJAGu+40AKKh7N01cC7EPkSFTXG76V35w30S5D/7Xuru2Z1ahIBp+5r+Dkd2PIavXwpRn2M1sQ5vzNQt/wOmByBXiJvhP4Y8g0Z1iJrboG+iyjTBt5Y7jfFYnm/ie/jVsy3nQ446qdpx+eMRj0tT2pYV9KIQm7fb69TJpl2OuoxcnE43jGPdqHuDK+KgwJzpddMip+8J+kII2uJuq7fg0LL6sZolhrnQASepeZxFfd2NzRjS/rQbUt3UESqVVl27FVxlEFPiLu3yL6NW+KhTTXy1bqoAPqZKA3LU45utqjQ3HCYH4B4s+IW9UiUiJnmW4GVYs8ze3bW1A/PmoIYji47HjpjXOzuJ3BnwJsBC15yc1Wn6Ly9dw6oegxqwwLFRVWunH5c+9c72zpDdqFum007jEpoEmCVVDccP2gAjwmHRtfO5f78KizbdM/OXqvl2bJr9ntNuL45NEe+frycXfTpcnYjeYasgNYhGyXwqw78QujShrhpYXud9TAMXxE/DJIoxEkcJL5PqeuP0SufBiQgMXY9msQ08ZMxCsLYIx7FQZLQJCDUG42PVhBS38MeCTzquy6x8uE9xJRGBB6XRlaBH8c4cCmJ/NiPnqOA+BQUhGEUBJRaBW4URdhPvDgGXxrxJHQpTmjshoQk5BniAy+KcewlbuzFSWd/4Lo4IiEJ3DgIrf0kCCmOQxLWMQtGfQDXTz1T6jyVHJap7HCinvAxiAgmXhLENAy9yFrhhy7BcUSihHqR3xjhuomHIzCBxMQfOvmUhyHBiQsuhoCDFgERyE4I6PI80G4zFCTgdRi5oe+H0bHSw8hPMPVrUbXxbQAhcpANSuv0h1Y6ZB0HEM2YxsQ7VnpEIw8DXGs1kd/BFzKDwWqAL2ilNjJBQDCNAcckCYL7xeT7vL/49qrIVtc1y7OUlQaWX5jEM7VcSv6+MgZawItrWHZgr2h3VVjfm+JG3T7tpCue/uDZbkEQi93Rr2F3O6i8qXEOi+xB4j6Oei2uaQptj0vZGpZGWNrVj3fGeThdFlqtz/lSc146ryAumAAAIFgR9pI6UZ7r1h3+sSEWNtdjNPwdPWbATLO8hI1q3VkC66QWdwG+PL/4PLuc/WsDfjI+OS3NVvK31qc/xbpQ2qBKSwfjieFr6LdgwuSmgkganJaN+6eTjuk0Exsksjfzk73/V/OTeiMuS7hZVFJew1idn7w9nQD9gE0qVg/NvzdcS7atSVbe20/2EGN8OoHPh1xGKXnDdE/ifw)

![image](https://user-images.githubusercontent.com/32860032/61259314-40823780-a7ac-11e9-9837-3e56894f8958.png)

**Comment by OmarShehata** [comment] 2019-07-16 02:28
Thanks for following up with the additional code example @hemincan . It looks like the issue is that the winding order for the polygon that doesn't work is reversed.

You can see this more clearly in this [modified Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=zVhbb9s2FP4rRIChMuoyEnWhlKbF0iRrA/QSJN6KoQ4KRqJtYrQoUFQar+h/35EoOZLjZE6fqhdL5Ll+5+Mh6Rum0Y3g37hGr1DOv6FjXopqif9qxpxnafN5rHLDRM71szFC36c5gqfkkqdGqPwsz0TKjNLoAM2YLPnYCoh8pt6o241Rw7UGU+da3YiM1zqtx1RzZvhnpWU2sTLOaJr/GL2c5tN8VuWNL5RKUZxLlnOnUCI35aiNBqFU5aWSHEs17+a6KZsg5rkRRvASa75UN/xISqe2vlWEZZmzNr39KZRczVV+gP5HrpHl+lyVok7hHRfzhRmC8tizv49UZSSgf4CMrp6mcqyk0muImy98cXqyg43WwGeRmcUB8twdVBaCa6bTxeoA2QLsoJNKtiwm6q1WVZ7tnOASmKIFkwd9yjbZfWhngF+AuVk5g9TfXpyefsTfhFkcyWLBHBfHo9Hj7n48PP2jY88NLCKb8Xuez80ClpL9xLL5bijcFua4oTlKgWm800IzWDycpYuG3oXI56ioOX5nvRtvqF+C/S9Xre9a1alFBIy6L+HncBDLS/T8uRj1OboD1YuWq10hv4irjapIds3lVuobfgvsvjQawnXEaEs1F80KuOAzrnme8jU93w3H8fH7ow/nXyefvr69+PTnx5P7hoYjvUqtKzOUqmHKITzoWPwW4HIEeo68EfptiNhQYSmyZhbkOy4xbeCN5X6D3R1EHVprHzDUJ+hazxn1A3zUw7KSRhRy9WZ1mTLJtNNJj5GLw/FaebQmWRd4VWw1mCu9ZFL8y3uWdgiytqjr+mw1WlbXRrPUOFsQeJKbh13cxd3IjK3o/bSt3FYTqVZl2alXxU4BPWLuLiL7Nm6FhzHVa14tiwoWfSZKw4DZ6HqFCs0Nh50T1rpZcLvekSgRM823gijFRmZ27LjpHDxrWsFw07YbYxeMi93NAq4DeDVQwXNuzusSnbTzzhZXD1Ft2JpwUZULp49rf3odWxfIGup28ba9qYT2CFFJdc3xvdb3kHFo8e2JpN/OCqt2sBFnry3xbN5tcxvbTz2zbQf9/O5sctqXy9m15BmyBtqELEqQVw38TOjSQtw0741Wtp2GL4gfBkkU4iQOEt+n1PXH6IVPAxKQGLseTWKa+MkYBWHsEY/iIEloEhDq3Wu6DzsIqe9hjwQe9V2XWPvwHmJKIwKPSyPrwI9jHLiURH7sR09xQHwKDsIwCgJKrQM3iiLsJ14cQy6NeRK6FCc0dkNCEvIE84EXxTj2Ejf24qSLP3BdHJGQBG4chDZ+EoQUxyEJa8yCUZ/A9XPVFMtW6pZnf/yq5frJdH+Zcv0k3ab5XYFKDif9bHtxHnEcRAQTLwliGoZeZD37oUtwHJEooV7kN45dN/FwBLCRmPjDxB6rSkhw4kJZQqh9W/UIbCcEfHkeeLdZBQlUKozc0PfDaFfrYeQnmPq1qTr4FjSoNlSA0hqy0FoHpHAADIhpTLxdrUc08jBQtHYT+R1lgU0YogbKgldqkQkCgmkM3CVJENydmq+m/VtZr9HZBnjJ8ixlpYGbGRyWJmo+l/xNZQx06WeXcBKHQ297kYK7ZdN/UXfZc9IFT//h2fr0Kmbroe/DDahzPly7682Fw1Vrq0afTL2tqGne7V6UsiVca+Baqf45Ms79U8BMq+UJn2vOS+cFgIMJsAAQi7CX1NXyXLfeiR86bITN9BgNf0cPBTDRLC/hzL/sIoELjxa3AT47Of04OZv8bVHfG+8dlmYl+Wub0+9iWShtUKWlg/G+4UvYFyGE/esK4DQ4LZv0D/c7pcNM3CCRvZrubfwDMN2r72xlCTOzSspLOP5M914f7oP8QE0qVh9uPt1wLdmqFll4r9/bQYzx4T583tcySslrpnsW/wM). I've labelled each point so you can compare the order of the vertices between the polygon that works and the one that doesn't. If you replace the points with the new `fixedFirstPoints` I created there, it should work.

I wonder if it would be worth having CesiumJS at least throw a warning or error of some kind to let the user know about this.

**Comment by hemincan** [comment] 2019-07-16 07:25
@OmarShehata Thank you very much for your reply and helped me solve the problem that confuses me.
I thought it was a bug. I think this may need to throw a error or write on the document. because it is very confusing.

thank you very much again.

**Comment by OmarShehata** [comment] 2019-07-16 14:12
Actually, I thought about a little more, and the confusion here is coming from treating the "clipping plane" as if it were a "clipping polygon", which it isn't. CesiumJS itself does not require any particular winding order for polygons, the problem is the function you wrote assumes a specific winding order to create the planes in the right direction.

 So if you were to draw the planes you're creating, I think you'll see that they're pointing the wrong way when the winding order is reversed.

It does seem like a common use case, so perhaps building some helper tools to make this easier would be really useful here. I opened an issue on the Cesium ion repo for that here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/198
