### ISSUE TITLE
Cesium Inspector broken

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2448] opened 2015-01-30 17:17 UTC
Run the [website demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Cesium%20Inspector.html&label=Showcases) or the [local demo](http://localhost:8080/Apps/Sandcastle/index.html?src=Cesium%20Inspector.html&label=Showcases).

There are at least two bugs.
1. Click Show Frustums for an insta-crash.
2. With the default view, pick a terrain tile and then hit any of the quadrant buttons, you'll get exceptions in the console output.

**Comment by pjcozzi** [comment] 2015-02-01 16:08
1. I can't reproduce with master or 1.5.
2. CC #1665

**Comment by pjcozzi** [comment] 2015-02-01 17:53
1. I can reproduce it now.  Using the simple CZML link from main index.html, click a satellite then check `Show Frustums` and the shader fails to compile.

I most likely will not be able to look at this for 1.6.

**Comment by mramato** [comment] 2015-02-01 20:27
This looks like it only happens in Chrome (at least on Windows) I get the error in OpenGL mode as well, so I don't think it's ANGLE.  Next time I boot into Linux, I'll try it there as well.

Because it's Chrome only, I'm okay with post 1.6

**Comment by mramato** [comment] 2015-05-22 20:54
See #2747 for some additional details on 1

**Comment by hpinkos** [comment] 2015-07-28 17:56
This crashes in Chrome and Firefox now.  `Show Frustums` gives the error message @kainino0x reported in ##2747.

This was also reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/EH5YNRdhqOQ

@pjcozzi @bagnell

**Comment by austinEng** [comment] 2017-01-11 17:14
2. Seems to be happening because the child tiles have yet to be loaded so the data for them does not exist yet. I'm not sure if we want to allow forcibly loading tiles as it seems like that determination is done automatically based on screen space error and visibility. Furthermore, even if we did load that selected tile, clicking any quadrant button twice would again fail because upsampling more than 1 level is not supported.

**Comment by pjcozzi** [comment] 2017-01-11 18:37
@austinEng it would be OK if you are just able to fix (1) above.

For (2), does the inspector know what it needs to have those buttons disabled when clicking them would cause a crash?  If not, is it reasonably easy to expose that?  If not, it could be insufficient priority to take the effort to fix it.

**Comment by austinEng** [comment] 2017-01-11 19:52
(1) I was unable to reproduce this crash where you click a satellite and then `Show Frustrums` . It seems to work for me in both Chrome and Firefox.

(2) I believe this should be possible to initially disable the buttons if the data is not immediately available. However, without modification of the GlobeSurfaceTileProvided, the inspector wouldn't be able to know when to re-enable the buttons when the data becomes available. This is potentially problematic because the crash only occurs when you click a quadrant button before zooming in (which loads the tile). If we were to disable them if the data is not immediately available, then you still wouldn't be able to select a quadrant after zooming in.

**Comment by pjcozzi** [comment] 2017-01-11 21:43
For (2), I suggest we skip it.  For (1), just click "Show Frustum" as soon as you open the Sandcastle demo, I get:
> RuntimeError: Fragment shader failed to compile.  Compile log: WARNING: 0:? : '
' : extension directive should occur before any non-preprocessor tokens 
ERROR: 0:3: 'gl_FragColor' : cannot use both gl_FragData and gl_FragColor 

If you don't get it, it is because you don't have the MRT extension; check http://webglreport.com/.  Could be worth a few minutes googling about that Mac, GPU, and WebGL support.

I'm pretty sure the problem is this code that adds setting `gl_FragColor` to the shaders: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Scene.js#L1446-L1461

It worked, but then we added OIT using MRT so the shaders getting modified stopped writing to `gl_FragColor` and instead write to `gl_FragData`.  For example, see:

* https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/AdjustTranslucentFS.glsl#L14-L19
* https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/OIT.js#L401-L402

We may have to modify the shaders differently based on if they write to `gl_FragColor` or `gl_FragData` or just not modify some of the shaders used for OIT.  Investigate and ask @bagnell if needed.

**Comment by pjcozzi** [comment] 2017-01-16 23:04
(1) was fixed in #4864.  (2) is insufficient priority for the amount of work.

**Closed by pjcozzi** 2017-01-16 23:04 UTC
Labels: bug, onramping
