### ISSUE TITLE
FlyTo: complete

### ISSUE THREAD

**Issue by tproduit** [AnalyticalGraphicsInc/cesium#3890] opened 2016-05-02 06:43 UTC
The complete function doesn't wait the flight to be completed. It is directly executed.

**Comment by hpinkos** [comment] 2016-05-05 15:16
Hello @tproduit, Do you have a code example that reproduces this? I wasn't able to reproduce this.
Thanks!

**Comment by tproduit** [comment] 2016-05-10 05:52
Hello Hannah,
Thanks for your reply. Here is a Sandcastle that reproduce the problem.

`require(['Cesium'], function(Cesium) {
    "use strict";

    var ellipsoid = Cesium.Ellipsoid.WGS84;

    function doSomething(){
        console.log('Happens at the time of the click on the button and not after the flight');
    }
    
    function flyToMyLocation(scene) {

        Sandcastle.declare(flyToMyLocation); // For highlighting in Sandcastle.
        
        var cartLoc = new Cesium.Cartesian3.fromDegrees(7.65869, 45.97625, 3000);
        var camera = scene.camera;
        camera.frustum.fov = 0.5;

        camera.flyTo({
            destination : cartLoc,
            orientation: {
              heading : Cesium.Math.toRadians(0),
              pitch : Cesium.Math.toRadians(-45),
              roll : Cesium.Math.toRadians(0)
            },
            complete: doSomething()
        });

    }

 
    function reset(scene) {
        scene.primitives.removeAll();

        var camera = scene.camera;
        if (camera.transform.equals(Cesium.Matrix4.IDENTITY)) {
            return;
        }

        Cesium.Matrix4.clone(Cesium.Matrix4.IDENTITY, camera.transform);
        camera.constrainedAxis = undefined;
        camera.lookAt(
                Cesium.Cartesian3.multiplyByScalar(Cesium.Cartesian3.normalize(new Cesium.Cartesian3(0.0, -2.0, 1.0)), 2.0 * ellipsoid.maximumRadius),
                Cesium.Cartesian3.ZERO,
                Cesium.Cartesian3.UNIT_Z);

        var controller = scene.screenSpaceCameraController;
        controller.ellipsoid = ellipsoid;
        controller.enableTilt = true;
    }

    var widget = new Cesium.CesiumWidget('cesiumContainer');

    var scene = widget.scene;

    Sandcastle.addToolbarButton('Fly to My Location', function() {
        reset(scene);
        flyToMyLocation(scene);
        Sandcastle.highlight(flyToMyLocation);
    });


    Sandcastle.finishedLoading();
});
`
Best regards,

tproduit

**Comment by hpinkos** [comment] 2016-05-11 14:43
Thanks for the example @tproduit!

The problem is that instead of setting the function to the complete property, you are calling the function.
This can be fixed by removing the `()` after `doSomething`

Here's the updated example:

``` javascript
camera.flyTo({
        destination : cartLoc,
        orientation: {
          heading : Cesium.Math.toRadians(0),
          pitch : Cesium.Math.toRadians(-45),
          roll : Cesium.Math.toRadians(0)
        },
        complete: doSomething
    });
```

**Closed by hpinkos** 2016-05-11 14:43 UTC
