### ISSUE TITLE
3dtiles was disappear at some angles

### ISSUE THREAD

**Issue by caipeng-hrv** [AnalyticalGraphicsInc/cesium#7859] opened 2019-05-22 05:50 UTC
Can someone tell me what happened in the below pictures?
![appear](https://user-images.githubusercontent.com/7042328/58150176-64d40300-7c98-11e9-96a2-19236cc70bd0.png)
![disappear](https://user-images.githubusercontent.com/7042328/58150185-6a314d80-7c98-11e9-8cfc-92341cb21d56.png)

**Comment by OmarShehata** [comment] 2019-05-22 11:44
@caipeng-hrv hard to tell without seeing the application or at least an animation, but my best guess is that this tileset is actually underneath the surface, but it's visible because globe depth testing is off by default. 

You can try turning it on with:

```
viewer.scene.globe.depthTestAgainstTerrain = true;
```

You can also move your tileset above the surface either with CesiumJS like in this example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Adjust%20Height.html

Or with the Cesium ion location widget if your 3D Tiles are hosted on ion. Please let me know if that fixes your issue!

**Comment by caipeng-hrv** [comment] 2019-05-25 13:00
@OmarShehata thank you very much, I am sorry to reply you so long.
I will try  your method , and tell you the result.

**Comment by OmarShehata** [comment] 2019-06-03 20:36
I'm closing this because I believe it's caused by the same issue here: https://github.com/AnalyticalGraphicsInc/cesium/issues/7879

**Closed by OmarShehata** 2019-06-03 20:36 UTC
