### ISSUE TITLE
Kml containing Style tags with namespace doesn't load styles correctly

### ISSUE THREAD

**Issue by vrittis** [AnalyticalGraphicsInc/cesium#3588] opened 2016-02-17 10:09 UTC
Trying to load the same kml in Cesium, I'm observing that the style tag is not loaded correctly and the component is loaded without a style (kml file loaded as text file)
[Areas.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/134004/Areas.txt)

In the GEarth plugin the style is applied correctly.

**Comment by vrittis** [comment] 2016-02-17 10:15
I already have a correction for this issue, which consists of changing the `queryNodes ` method in the `KmlDataSource.js` file, and more specifically the `node.getElementsByTagName(tagName);` which doesn't take the namespace into account.

I will try and add tests for this behavior, however I wanted to know whether or not I could add an example of the kml that poses problem to the Samples Area in order to prove the validity of the correction

**Comment by mramato** [comment] 2016-02-17 14:55
Hi @vrittis.  Sounds like a great pull request, thanks for reporting the problem and even more for trying to fix it.

SampleData is reserved for demo data that is used in Sandcastle, we have two ways of handling data for the tests.

1. If the snippet to reproduce the issue is really small (like < 10 lines) then you can embed it right in the test itself.  Here's an [example](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/DataSources/KmlDataSourceSpec.js#L262)
2. If the file is larger, then you can place it in the [Specs/Data/KML](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Specs/Data/KML) directory, but please keep the file as small as possible to reproduce the issue (the largest file in that directory is 1.55KB.

There's also a fairly large KML pull request about to come (see #3538), there's a chance that this addresses your particular issue already (I know @tfili fixed some styling bugs).  I'm expecting that to get merged into master today, so you can either try it out once that happens, or sync up to @tfili's fork that already has the code.

**Comment by vrittis** [comment] 2016-02-17 15:31
Thanks @mramato but I don't see anything in @tfili pull request that changes style management. Maybe we can push this issue into his pull request?

**Comment by mramato** [comment] 2016-02-17 15:55
That PR was just merged, so you can branch off of master to make and test your changes.  Thanks.

**Comment by vrittis** [comment] 2016-02-18 13:21
Please be advised that this issue only happens on Firefox / IE, not chrome. Sorry for the PR name, I made a mistake submitting it

**Closed** 2016-02-25 02:15 UTC
