### ISSUE TITLE
RIGHT_DOUBLE_CLICK does not fire callback

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2773] opened 2015-06-02 14:35 UTC
For example, the following Sandcastle example never outputs "right."
```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
handler.setInputAction(function(movement) {
    console.log('right');
}, Cesium.ScreenSpaceEventType.RIGHT_DOUBLE_CLICK);
```
`LEFT_DOUBLE_CLICK` and `MIDDLE_DOUBLE_CLICK` work.

**Comment by mramato** [comment] 2015-06-02 14:49
This is dupe of #2631 Long story short, don't use `ScreenSpaceEventHandler` see that issue for details.

**Closed by mramato** 2015-06-02 14:49 UTC
Labels: bug
