### ISSUE TITLE
Globe not showing

### ISSUE THREAD

**Issue by hijazikaram** [AnalyticalGraphicsInc/cesium#8590] opened 2020-02-04 20:02 UTC
I had Cesium working on my system previously, but today, the globe is missing. I have made no changes to my project since it last worked. I downloaded cesium again and the globe is missing even when I view HelloWorld and Sandcastle. I only see a black sreen.

**Comment by OmarShehata** [comment] 2020-02-05 14:25
@hijazikaram I'm closing because there isn't enough information here to determine if this is an issue with the library or with your setup. Feel free to open a thread on the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) and we can discuss in more detail there some debugging steps you can do. Make sure to include:

* What browser and browser version you're testing on
* If there are any errors in the browser console or network tab
* What CesiumJS version you're using
* Your OS
* If the issue is only present when testing locally or also on https://sandcastle.cesium.com/index.html?

**Closed by OmarShehata** 2020-02-05 14:25 UTC

**Comment by nprasad2077** [comment] 2023-02-15 00:02
I am having the same issue. Was working before but now all of a sudden it is not. Using in React, same result on all browsers across multiple systems.

**Comment by Samdosi** [comment] 2024-02-15 16:14
> I am having the same issue. Was working before but now all of a sudden it is not. Using in React, same result on all browsers across multiple systems.

I am having the same issue, I have upgraded all my packages including react, cesium, and resium and globe is not showing anymore. I have no error on the console. Were you able to fix it?
