### ISSUE TITLE
Points rendering issue on Linux Chrome

### ISSUE THREAD

**Issue by chris-cooper** [AnalyticalGraphicsInc/cesium#2828] opened 2015-06-23 00:37 UTC
This issue shows up in Chrome on Ubuntu 14.04 running Intel onboard graphics on a Dell XPS 14 laptop.  The below screenshot shows Chrome and Firefox both rendering [the points development example](http://localhost:8080/Apps/Sandcastle/index.html?src=development/PointPrimitives.html&label=Development).

![points](https://cloud.githubusercontent.com/assets/484870/8296328/a39fc6a4-1992-11e5-9f22-ad3b83ae853f.jpg)

Here's a WebGL report from the same Chrome.

![points-webglreport](https://cloud.githubusercontent.com/assets/484870/8296329/aad29b54-1992-11e5-8173-a8e1f7b0b43f.jpg)

**Comment by nmschulte-aviture** [comment] 2015-06-30 21:39
Where's the issue?  I assume the left rendering is Chrome, and it should look like the right rendering (Firefox)?

Running the example on my machine in Chromium (v43.0.2357.130) on Debian Sid via the integrated Intel HD Graphics 4600 adapter (using the mesa/i915 driver), I see a rendering that looks like the one on the left.

**Comment by chris-cooper** [comment] 2015-07-01 02:07
Yes, in Chrome (left) it looks like the points are rendering as a single pixel rather than a small quad that's being shaded to look like a ball in Firefox (right).  Also, it looks like a vertex shader issue as I did a test making the fragment shader red and the points remained small.

**Comment by mramato** [comment] 2015-07-01 03:39
I can reproduce this as well (Intel 4000 under Linux Mint 17)   Works fine in Firefox, breaks in Chrome.  @emackey is unavailable until July 6th, but I'm sure he'll want to look at this (since he wrote the new primitive).  I agree that it looks like the points are stuck at size 1.  WebGL is reporting a max point size of 5, so maybe there's an issue with our clamping (or there could be a bug in Chrome).

**Comment by mramato** [comment] 2015-07-07 14:02
I just stumbled on this Chrome bug: https://code.google.com/p/chromium/issues/detail?id=503608 which makes this look like a general Chrome issue (that may already be fixed in the next version).  I would recommend people chime in on that issue with your own experiences since that's probably the best bet to ensure this is fixed.  We'll keep this open until the problem is gone either way.

**Comment by chris-cooper** [comment] 2015-07-09 00:49
Good find!  This is now fixed for me in chrome beta.

**Comment by mramato** [comment] 2015-07-09 00:54
Awesome.

**Closed by mramato** 2015-07-09 00:54 UTC
Labels: bug
