### ISSUE TITLE
Clustering doesn't work well in 2D and CV

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4538] opened 2016-10-27 19:53 UTC
When in 2D or Columbus View, the left side of the screen does not show any billboards if clustering is enabled.  Here's a sample from a large CZML file of air traffic.  With clustering disabled, everything is fine.  Once it's enabled, lots of stuff on the left side disappears. (Even stuff that's clearly not part of a cluster).

![clustering](https://cloud.githubusercontent.com/assets/1495196/19782722/113d2b36-9c5d-11e6-87d8-805772ec3d3d.gif)

I ran into similar oddness when using the default clustering example, lots of stuff disappearing in 2D that shouldn't be.

**Comment by jeffwhitty** [comment] 2016-10-28 02:45
I noticed a similar behaviour, my entities are all loaded manually from a web service (20,000 calls to getOrCreateEntity()) and with clustering on the numbers are nowhere near the right total for all of my entities and the left side was largely blank or very thinned out.

No CZML or dynamic time happening, just a bunch of entities (some billboards, some points).

**Comment by pjcozzi** [comment] 2016-10-28 16:10
@bagnell what is the level of effort here?  If it's reasonable, seems like we should fix this soon or disable in 2D/CV until we have time to fix this.

**Comment by rutsky** [comment] 2016-10-28 17:30
This issue also reproducible in [Clustering demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Clustering.html&label=Showcases), almost no features are inside Atlantic ocean: 

![2016-10-28_20 28 49_1](https://cloud.githubusercontent.com/assets/46573/19815808/a0c8145c-9d55-11e6-8c65-6c982a870413.png)

however if I switch to 2D lots of feature will appear there:

![2016-10-28_20 29 24_1](https://cloud.githubusercontent.com/assets/46573/19815811/a41edfb4-9d55-11e6-8baf-bd617fe98ad0.png)

**Comment by mramato** [comment] 2016-10-28 17:31
I previously thought this was 2D/CV only, but @rutsky's screen shots above make it looks like a general problem.

**Comment by rutsky** [comment] 2016-10-28 17:34
@mramato my comment was about issue in 2D/CV only: there are no features in Atlantic ocean (which is correct), but they appear if I switch to 2D/CV. So I *don't* assert that clustering is not working in 3D.

**Comment by mramato** [comment] 2016-10-28 18:08
Ahh, okay.  Is that in master?  You might be running into a separate issue if it's 1.26.

**Comment by rutsky** [comment] 2016-10-28 18:14
@macoda I'm observing appearing items not on their place when clustering in 2D in 1.26 release.
So my issue should be fixed in master and this bug report is about different issue?

**Comment by corygehr** [comment] 2016-11-01 20:33
Just wanted to toss another vote in here for this issue - I'm seeing the exact same thing in the 2D view. My pins disappear until I zoom in to certain points. When I'm zoomed in super close it seems to be fine.

**Comment by tfili** [comment] 2016-12-01 00:51
@bagnell what's the pan for this?

**Comment by pjcozzi** [comment] 2016-12-01 13:34
Pushing to 1.29 to not hold up the release.

**Comment by hpinkos** [comment] 2016-12-08 15:07
Also reported here: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/JrZ60d1r_zk

> I find it will be nothing to show at the moment when I convert to 2D from 3D, but move the camera ,it will show these entities

**Comment by pjcozzi** [comment] 2016-12-19 17:58
@bagnell this is an important one.  What is the level of effort?  Is it reasonable to aim to fix it soon or just disable it?

**Comment by pjcozzi** [comment] 2016-12-31 17:39
Pushing this to 1.30.  Leaving it labeled `next release` since there is so much interest.

**Comment by hpinkos** [comment] 2017-02-01 14:07
Guess we're pushing this to 1.31.  Should we leave this labeled 'next release' or is it not as critical anymore?

**Comment by pjcozzi** [comment] 2017-02-01 14:13
Let's leave it `next release`; I also added it for the bug bash, #4897.

**Comment by lilleyse** [comment] 2017-02-28 01:33
@bagnell Is there time to get this in before the 1.31 release?

**Comment by bagnell** [comment] 2017-02-28 19:08
@lilleyse No, we'll need to push this to the next release.

**Closed** 2017-03-24 19:03 UTC
Labels: bug, next release
