### ISSUE TITLE
Modifying show on multiple polylines

### ISSUE THREAD

**Issue by drakej** [AnalyticalGraphicsInc/cesium#3598] opened 2016-02-18 16:54 UTC
When I attempt to change the polyline.show attribute on two entities at once, only one of the changes is actually visualized.

I recently found this issue when instead of setting the show attribute to true on multiple polylines inside of an event handler. I also set billboard.show on multiple other entities and the changes are propogated and displayed accordingly. I attempted to debug this which lead me to PolylineGeometryUpdater.prototype._onEntityPropertyChanged() which according to the stack trace, showed the changes going through. So I don't believe it's getting missed. I setup my own event handler on the entity collection via the collectionChanged property. This showed the setting of the show properties as being processed as two change events. I did suspendEvents() and resumeEvents() and this ended up showing one change event with both entities. Either way I still only see one polyline visible.

My hunch is that this is some sort of drawing issue that I haven't tracked down. If this is hard to reproduce, I'll try to setup a sandbox example to help.

**Comment by drakej** [comment] 2016-02-18 16:55
Just to clarify, only the first one I change goes through. It's the second polyline I update with show = true; that ends up not being displayed.

**Comment by hpinkos** [comment] 2016-02-18 17:03
Thanks for investigating this @drakej!  The extra details are helpful.
Yeah, if you're unable to figure out the problem, please do put together a Sandcastle example so we can reproduce it =)

**Comment by drakej** [comment] 2016-02-18 17:35
`var czml = [
  {
    "id" : "document",
    "name" : "CZML Geometries: Polyline",
    "version" : "1.0"
  },
  {
    "id" : "redLine",
    "name" : "Red line on the surface",
    "polyline" : {
      "show": false,
      "positions" : {
        "cartographicDegrees" : [
          -75, 35, 0,
          -125, 35, 0
        ]
      },
      "material" : {
          "polylineOutline": {
              "color": {"rgba": [255, 0, 0, 255]},
              "outlineColor": {"rgba": [255, 255, 255, 255]},
              "outlineWidth": 2.0
          }
      },
      "width" : 5
    }
  },
  {
    "id" : "purpleLine",
    "name" : "Purple straight line at height",
    "polyline" : {
      "show": false,
      "positions" : {
        "cartographicDegrees" : [
          -125, 35, 0,
          -170, 35, 0
        ]
      },
      "material" : {
          "polylineOutline": {
              "color": {"rgba": [148, 0, 211, 255]},
              "outlineColor": {"rgba": [255, 255, 255, 255]},
              "outlineWidth": 2.0
          }
      },
      "width" : 5
    }
  }
];

var viewer = new Cesium.Viewer('cesiumContainer');
var dataSource = new Cesium.CzmlDataSource();
dataSource.load(czml);
viewer.dataSources.add(dataSource);
viewer.zoomTo(dataSource);

var handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
handler.setInputAction(
    function () { 
        dataSource.entities.getById('purpleLine').polyline.show = true;
        dataSource.entities.getById('redLine').polyline.show = true;
        
    },
    Cesium.ScreenSpaceEventType.LEFT_CLICK
);`

Run this code in place of the CZML Polyline example code and you should see the issue. I noticed that the bug is more specific than I thought. Solid color polylines don't seem to exhibit the problem, however polylines with outlines do, but only if they are not the same color. For instance if you take the example above and change the color (not the outlineColor) to be both red [255,0,0,255],  they will both show up.

**Comment by hpinkos** [comment] 2016-02-18 18:12
Hmm, that is oddly specific. haha.
We'll definitely have to take a closer look at this.
Thanks again for all of the information!

**Comment by mramato** [comment] 2016-02-18 22:19
It looks like this bug may be specific to the per-material batching code used by GeometryVisualizer.  Might be an easy fix.

**Comment by hpinkos** [comment] 2016-02-22 15:16
Likely related: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/Dr4Go1LiEys

**Comment by hpinkos** [comment] 2016-09-09 20:23
Hi @drakej 
This issue appears to be fixed, so I'm going to close this issue.  If you can still reproduce it, let me know.
Thanks!

**Closed by hpinkos** 2016-09-09 20:23 UTC
Labels: bug
