### ISSUE TITLE
Entity not being rotated about its origin

### ISSUE THREAD

**Issue by Juanelm** [AnalyticalGraphicsInc/cesium#7961] opened 2019-06-24 22:36 UTC
I find that when I apply an orientation to an entity, the 3D model is rotated around a point which is not the origin of the 3D model. 

I modded the 3D Model sandcastle example to rotate the aircraft model around the roll axis.  Here you can see that the aircraft is rolling around a point above the wings.  However, the origin of the model is below the wing; so it is not rotating around the origin. 

[Sandcastle Example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVbvb9s2EP1XCH+x0qm0HDvtFrvBUqdYAyzoDwf9Ug8FI50jwhQpkJSTrPD/viMpybICbC0wC4ZBnh7vPb47UdoyTbYcHkCTN0TCA1mA4VVBv/hYNEz9dKGkZVyCHsbk+0oSvLhcq7fqkZyTNRMG4hA1ICC1XMlrmfGUWaX7gJxl6sFg1OpqH1SVyC4lL5iF+tZK7k5mK7mSW1QI0nL75BRWQsxCTCvLHBNGEw9cV9JTk1QD5rlRGYio0iImOfD73J400sN+qU/KwVANhdrCpRBRYPQYZCiV4TVD7cqCaYsjJid0rVVxBfcawEQvx6cTmryeTl+Nf4vJdEqTs2TyOnnVMs/2SXNgGZf3+5w3zObUqs8YZtJE48lZF15ym+b1FpuYVkL0QnnZq9/7QPPRLf+M+KjmjUPG2CfpEinN0RB2uN9bjZLWSheG5r2Enyr0WEuER41PsZOxt7AtWt9vlmVRXQp3SVa4ortK7YOt9+ftsHO3K/a8O+tgCld/vNthclel+TMyD+fYflXxkT+CWPK/naLx6a99EHt0oGXKhAOcJnjtEbsw3LW2hn1bzdINZO8aO4IviNkddK3v57pr21YN/51Wb4e/kFOavJjQ8fRFQpPk7Hl/NNCfahPMFRP/12+Q/+FpGKNdx+q51qym8WhHcDOc9SCHAjqzWWP/rjmCuETqLRPXV4g0YK/redQUMDr5flDC2c5vODwPIYcqHdBggq91fS08Wmyk4SXXqWZrO6wbDlH+JHWnZ5u/28rdM25I6aj9XZalGS1ZUQq4YpaN/GNgRsFcpKlH33BI78UdHuhnWBXa1gU3vGsP+UbeH1pVMiNfIOepgKOJDDQ1y+Gs1vrvMt8rS3Bf5C0TQil5ZDNrlsNZrXP8357ecLEht7pKN0fW6Yg8T3/+clOkP+TrcsOlhIwscoZnmXWfAcdVzBpXv+HwhyReoTBFFqooNRiDWj3n0XR6uj1b31mUbNd9zX/5k2DJZJYyY7Gl8T14q5S4Y/oGZBXVp4NbMogHc2OfBFyE5b/zolTautdWhKIsoB7Ua0Z3SAaWpsYvm4+aRfOMbwnP3qwGvQ+41YCkghmDd9b4LeXedKvBxXyE+INlQvmj98MWtGBPDpKPL/4MQUrpfITT56ts2E4n4z8 )

If you upload the Cesium_Air.glb here, and activate the RenderGrid, you can see that the model origin is below the wing. 

https://sandbox.babylonjs.com/

**Comment by OmarShehata** [comment] 2019-06-27 12:55
I have a rather peculiar fix for your issue. All you have to do is double click somewhere on the ground.

In the GIF below, the plane starts off rotating what seems to be off-center. If you double click away, it instantly changes and rotates correctly!

![plane_optimized](https://user-images.githubusercontent.com/1711126/60267523-6c4e8380-98b8-11e9-853e-34d9fc854abb.gif)

Another way to fix it is to replace:

```
viewer.trackedEntity = entity;
```

With:

```
viewer.zoomTo(entity);
```

What's actually happening is that the camera is following the entity, based on its bounding sphere (which I guess moves when the entity rotates). So the issue is the camera is actually moving up and down. I discovered this by adding a plane entity as a reference [and noticing that the plane was moving too](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVZ/b9s2EP0qhP+xgqmUHSftll+Y6wRNgKb1YiPbMA8BI50twhQpkJSTdPB335GSbFkpugCDhSAgj3f3Ht8dSa+YJisOT6DJOZHwREZgeJHRe28LurGfjpS0jEvQ3ZD8M5MEPy7n6qN6JidkzoSBsLQaEBBbruSNTHjMrNJth5Ql6smg1epia1SFSIaSZ8xCtTST64PTmZzJFTIEabl9cQwLIU5Lm1aWOSS09rzjvJAemsQaMM+tSkAEhRYhSYEvUntQUy/3S31SDoZqyNQKhkIEJaL3QYRcGV4hVKqMmLY4YnJA51pll7DQACZ41z8c0N6Ho6P3/V9CcnREe8e9wYfe+w3y6TZpCizhcrHNectsSq26QzOTJugPjpvuObdxWm2xtmklRMuU5q36XZcwYxd+h/5BhRuWGUOfpAmkNEdB2O5+pxopzZXODE1bCX8rUGMt0T2odQodja2Em6K19WZJElSlcJ9kmSu6q9TWuNH+ZDNsrDbJnpDmvkdMiEcWL8da5aDtS1B3RWB5BrhtMIXYtkL9tcpdUqe1hS7A3jNRgE9Sq1Z/uGnqS/IT1oT2W6sabKHl/xS0TrYOy8N00NAic32OKrR2VGj+SlTvzvGYFdmYP4OY8G9O+f7hz20n9uycJjETzuGwh1+DRTlcb9qnrK/VqDskV3XZSxErnyiqvL4plU1VUC7WGRr9LpiEqzd2zo+bxKd6LUyCJZQGXd0ltNM51dk+DAY92guJ+3/wShisEWdO7zpMCaXp79c30yv6xG06FHnKAuyDdmhNp4obuyn9enfz6ebLwx9/Pow/D79ctUJUYQWXsHtZthY9/nfpfL9ga3c8yxtU5dbLcE7+qjSy8GwxV3fIdazZ3HYrTPTyF7u7zOvztHOGmldul9Jo8zfMcxNNWJYLuGSWRb5bTVSyRZhq9IBDuhCP+L4cY6+h8FVnIN315s2p6X3SqpAJuYeUxwL2RrKEqVB2ZxXXH9O8VpbgvshHvJOUknsWs0LZnVU8+/+t6S0XSzLVRbzcM08H5HHa83fLLH6TrpMllxISMkoZXjnW/SrZL2NWq/qAwzdRvERiioxUluODY5Crx9wbTw+3RWsri5TtvM35b/9QT5hMYmYstjRerlOl8PXUtyCLoLodXEgn7JwZ+yLgogz/lWe50ta9LgGSsoB8kK+JHhEMLI2NDzuL6qCzhK8IT85nndbvyVmHxIIZgytz/GnnHqRZ5+IsQv+dMKH8Y/l1BVqwF+eS9i8+l0ZK6VmE09dRttxOI+O/).

Feel free to follow up with any similar issues in the [forum](https://groups.google.com/forum/#!forum/cesium-dev)!

**Closed by OmarShehata** 2019-06-27 12:55 UTC

**Comment by OmarShehata** [comment] 2019-06-27 15:55
Yes, I'd recommend creating an invisible point entity to mark the exact location you want the camera to follow. 

In general I think the default camera follow is useful for common use cases, but you may want to write your own logic of how to follow your entities for finer control (this is a useful [forum thread on computing an entity's bounding volume](https://groups.google.com/d/msg/cesium-dev/BSXl9QhzlXs/KMQ_1rXzBwAJ)). 

I'm not sure if the bounding sphere/volume changing as the entity rotates is expected or not here. @lilleyse do you know?
