### ISSUE TITLE
Rendering has stopped. Normalized result is not a number

### ISSUE THREAD

**Issue by mholthausen** [AnalyticalGraphicsInc/cesium#7585] opened 2019-02-20 09:06 UTC
On my desktop application of CesiumJs and in the Sandcastle i run into the same problem:
When moving the camera beneath the earth surface (to watch geological subsurface layers) the rendering stops at at irregular intervals and the app crashes. I have attached a Screenshot of the error in an empty sandcastel. It is the same error report (except that my cesium is stored in node_modules). I am using in my app CesiumJs in Version 1.54, the same as in the Sandcastle.
Error Messaage on screen in the Sandcastle (and in my application):
![rendering_sc](https://user-images.githubusercontent.com/43119593/53079535-f34cb300-34f6-11e9-9885-a6c5c8001d9e.png)
In the latest Firefox the App just stops without any message.

Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/

Browser: Chrome 72.0.3626.109 (Official Build) (64-Bit)

Operating System: Linux Mint 19

**Comment by OmarShehata** [comment] 2019-02-20 15:20
I believe this is the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/6783

**Comment by hpinkos** [comment] 2019-03-12 18:45
Closing as duplicate of #6783

**Closed by hpinkos** 2019-03-12 18:45 UTC
