### ISSUE TITLE
Shading issue in instanced 3dtiles format

### ISSUE THREAD

**Issue by LHolst** [AnalyticalGraphicsInc/cesium#7655] opened 2019-03-15 14:35 UTC
1. A concise explanation of the problem you're experiencing. 

shading issue with i3dm 3dtiles, since IBL the shading changes in comparison to b3dm with the same materials. 

as seen in the sandcastle, with 1.55 there is a shadow at the corners of the cubes 

2. A minimal code example. If you've found a bug, this helps us reproduce and repair it. 

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=zVj/T+M2FP9XPDRdEl1JgTvE1ha0UdiODQ50VLcfAE1u8iAerp3ZTkvvxP++58T5Vop2HVRahIhrvy+fZz8/f5wpVWTKYAaK7BMBMzIEzbJJ+Dnv870o/zmUwlAmQHkd8vVaEHx0QmM506RHjMrgWjwG/WtRWArhwYCIfWeq6Cx+vDsaMQ76ROgUIiPVGXtgItdEHKzstc7PZAwcMTmT0VL13HYuiSYq9xGX0X0YZUqBMCM2gXZov2WcUXFEDfg773f3dnd2wu3d93s/7gSFEUSiIxBQO89/OpDGAgBTiU4bWN3UOBHdI1dFh32+1k37CDqBHvFGhajXaY8q0DJTkZUIw27193Oa6u4lnaQcED7ttua062xVja7DEf6lpfBqB4+d58AoKjTPMNjXAXRITZRAXL4b5l8CrXue0r8zWDPCwgmm58pQzzJu2GYkuVTrwDi0hvXKqD4BhqMN+Sx5NoG15NsfzCRF2XDOCl8rQ3WBrmPyLMS8OaJjvjoyrDuGiuiVsFXW6tZr4eueK4ZJTA1DxTVhbbhYGehQTlKpmXmdRKysNVqrIrqQTJghl9nrrG1trtH89OvhC3DhGWxn3gxfrbIsBdly8wK4H6WaUK7XB9Q5eAHE1yw0SyGW1ee/QzxSNJLrA5ibfxZe0bxx3jVw5Fx4SBbSPZKJGG6RFMadFiOsCGFOkRznuhdIyWRmQoMe7/2KNNWUy0jJx9Sy0FhGeGwIE96BOeZgm4fzk9j3nIhnlRbt0jTl80MmYibudG2/U9oNlqJBD+djDWpqy21Ty3PBeEGos7GOFBuDf5uJyJY7H4SVj4Ny+Uqa6CjxPnECfUeLV3LcnublAGRqX7oCwG5JybbdmvhuUYOgmWM5kQ1TxSbMsCnoUMFETqES7heij7XV7xbMlp5bZp8S99BZxLmo0qRfKygwmRK1txZvXuDdTbg0jv0Gk29lOBi/ASlTHK8mDm1Y7hjnMCgWpeETJWg8v1BywjSEJgFRT/a3h1rfDUpxF8gXKScjWU5zp3kb+YCOMWcvGJaKT1Tcgb/VIZs7If4/oyYJJ/TB397aCrfIZgV2LLM80S/TBBSECi1kukNQKGiElvvHHZUqmYIyDHQNMaw7G2iXpFEtF5A3b8izoxgHu0sW0q05wdrM+cJFrLl8l3bYX9C1T06ke2TJSDGKE5Gvceuytfhced9/LQA+koN98sM7vMdeb+SmfS/NFJZMz87fbnC9cdP5djtbTTsKj5LV9Pda+lLZ5V/RxPZO08QcOJezVVE0LXC8Lq8Koakfzan4d317QjS1xjwrvC5XWtL92O56DPpPDq7HIJS4k9UMt3SjdislVStLTaLkzPWXJSmoS3dVnMOF0uzqVKsI6Ku9m+pIS6iI+eKHlctIAYjLlEZwPMWj7UMh5JffLiiq6sKz00e/5kSkmfm5iKAKxZZuezrW5xA6vQWKtdXutCWlyg32nz01nEB7GzeKyPwjMhRbR5ygPcgumkN+cyGsIgdxZxLUaFkIi+6G7K1UxM+/AqHsVh9fA6fbJ2/fsid1ZRHUoocrdtNva2Ct0JJDyOWd39J8SzykUvhaElRLMliWZZgonecWdzRPITw9/mX05/D0ZPj7/2tZy2h1Imd2RZFMQ/9bgzo7OTo6Pa7D2uhsDPISf1BY+InhTUwZew77yE0NIC2lBnnoOIvu8TiIdJ7kg26pNIjZlLB4H2tC+5Pj9QaJONUaR24zzi/ZF7jeOBh0Ub6lxmV+kJ5PQXE6tyLJ9sFp0RmG4aCLP59qOXqI4gXuQbHJSYwMenOMfBJlHIvoVR/2OiWxGMEDEmHP0nYsZ1OKZay3SJQr4SHN3/b6m0ipgVDiRBCel8dUqJZQLNYBsylCDM65nZoEovuxfMA5aQLMuyHulRQcbZHLollF7N7/AA 

3. Context. Why do you need to do this? We might know a better way to accomplish your goal. 

i think its a bug. same issue when i  create my own b3dm and i3dm examples with the same pbrMetallicRoughness material. 

4. The Cesium version you're using, your operating system and browser. 

cesium 1.55, ubuntu nvidia 1050, chrome v71 and firefox

Forum https://groups.google.com/forum/#!topic/cesium-dev/jr3HMTDgoJE

**Comment by OmarShehata** [comment] 2019-03-16 09:30
This is certainly a bug. I think this is the same issue @lilleyse and I just recently ran into. Screenshot from the forum post:

![sandcastle_instances_shading](https://user-images.githubusercontent.com/1711126/54473319-6c64c080-47ac-11e9-927b-512be49f66b5.png)

**Comment by hpinkos** [comment] 2019-03-18 14:40
It sounds like this is a regression so I'm marking it `priority - next release`

@lilleyse @bagnell can one of you take a look at this?

**Comment by lilleyse** [comment] 2019-03-18 15:04
It's probably better for @OmarShehata to look into this.

**Comment by lilleyse** [comment] 2019-04-01 13:49
This won't make it for today's release but I'll keep the label so we fix it for the next.

**Comment by hpinkos** [comment] 2019-04-01 14:56
@OmarShehata please keep this on your radar so this doesn't slip another month

**Comment by OmarShehata** [comment] 2019-04-24 01:57
I think this has always been a problem, but it's just a lot more obvious with IBL. The problem is that materials on instanced models are lit differently than non-instanced models, despite using the exact same material (and exact same fragment shader). This is a lot more obvious using the models @LHolst provided in the forum thread, which I have [in this Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html#c=XZJhb9owEIb/isUXgjQ5hEHXrhStoh0zIjAgg4IiTcY5isGxqe0AYdp/nyF06+ovjn3vc/f6Lr6POppKi9pgeJZ2x4gyBsYgq1CuMo24kogaA9bEstBgoiROYEkzYe/P4khtQKI7VIa8u1p0GB/wLvlxJEGfE0PkqMHa5Ipstk+TdvcGO9FL0tk4ETnMpo+NwcNqNR8HIjwO671oxMM1s7N1P52Nq8Es7W/CadjoR6PNfE14r93dzl2yMJrlYb7ndPq1Stbq0I9IIzyGtXA9zJdDvHgKyIT/HMA38UlPb3g1qMqDZo/X4VW7SxeDXdaZLr4P5vtavXwby1juqEY7DnvQ7hkS9pd24Mn5ziuz87GtpKVcgi5X/lKWC3DdcVjBY8NAAt5qnnLLd2AwTRIvlsitN4mL7eNDVODer0JxWpkWn9G/Vo/AuDkwwEut0vvTJEji1YJ69bpSML/dfvFTODgqlUbKuzi7qLCyK9B7bsBbZpLZ01w90FrpCnpTnClplAAs1PMlevtaxX2UPpSaxuYCWsXlF55ulbYnyx7GvoV0K6gF4y8ytgGLmTEnrOm/Qs2E7xBP7uLSu47GJcSE+89cZJkJMeZHiEutpu/0/2FC0YTL58EOtKC5kxRGmqug1StCGOOm746nsu9pq5RYUP0m8x8).

![broken](https://user-images.githubusercontent.com/1711126/56626786-26074a80-6611-11e9-8bc1-002eab795008.png)

The cube on the left is b3dm. The cube on the right is i3dm. They are using the same PBR material, with all the same settings, but they look very different. 

If we hardcode instancing support to be off by adding `viewer.scene.context._instancedArrays = false`, then it works perfectly:

![fixed](https://user-images.githubusercontent.com/1711126/56626782-21db2d00-6611-11e9-8727-c9fa917cbd48.png)

I discovered this while debugging the PBR shader in `processPbrMaterials.js`. The `LdotZenith` computation seems to be off for the instanced model. This value should be the cosine of the angle between sun and the zenith. When moving the timeline slider, you can see the b3dm is always a solid color, and goes to black when the sun goes below the horizon. Whereas the i3dm has a gradient..which doesn't make sense.

![LDotZenith](https://user-images.githubusercontent.com/1711126/56626971-ebea7880-6611-11e9-8c75-cbaf67e1110e.gif)

_This was visualized by adding `fragmentShader += 'color = vec3(LdotZenith);\n';` in line 759_.

This angle is computed using the world position of the vertex, so I visualized that too by adding `fragmentShader += 'color = vec3(normalize(v_positionWC * -1.0));\n';` instead:

![v_position](https://user-images.githubusercontent.com/1711126/56627114-7af79080-6612-11e9-87d6-cfb29dc7eb34.png)

I would expect this to be constant across the model. The fact that it varies so much implies it's not really the world position? I'm not familiar enough with WebGL instancing, but I'm guessing this isn't

**Comment by cesium-concierge** [comment] 2019-04-24 20:46
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/jr3HMTDgoJE

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7655 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed by cesium-concierge** 2019-04-24 20:46 UTC
Labels: category - 3d tiles, priority - next release, type - bug
