### ISSUE TITLE
Cesium polygon entities display with missing vertex

### ISSUE THREAD

**Issue by jionghui** [AnalyticalGraphicsInc/cesium#6335] opened 2018-03-15 09:48 UTC
There are 4 vertices created for the polygon entities, however, there are only 3 vertices displayed as shown below.
![capture](https://user-images.githubusercontent.com/1123051/37455299-b64e4b12-2877-11e8-81a9-cbe00287f177.JPG)

**Tested on 1.43.0 :** 
```
var viewer = new Cesium.Viewer('cesiumContainer');
var entities = viewer.entities;
var arrPosList = [116.71705, 2.44717966, 18.6,
                  116.71705, 2.44717966, 7.1,
                  116.71704, 2.44719318, 7.1,
                  116.71704, 2.44719315, 18.6];
entities.add({
	polygon : {
		hierarchy : Cesium.Cartesian3.fromDegreesArrayHeights(arrPosList),
		perPositionHeight : true,
		material : Cesium.Color.fromRandom({alpha : 1.0})
	}
});
viewer.flyTo(viewer.entities);
```

**Comment by ggetz** [comment] 2018-03-15 13:47
Hi @jionghui, the polygon primitive is designed to conform to the curvature of the ellipsoid, so it doesn't work for arbitrary polygons in space. See more discussion in https://github.com/AnalyticalGraphicsInc/cesium/issues/5907

Closing as a duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/3349

Since you are trying to create a vertical polygon, maybe a [wall](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Wall.html&label=Geometries) will work for you.

**Closed by ggetz** 2018-03-15 13:47 UTC
