### ISSUE TITLE
Image trails in the sky when using 1.10

### ISSUE THREAD

**Issue by mike-mcgann** [AnalyticalGraphicsInc/cesium#2811] opened 2015-06-15 18:53 UTC
This problem can demonstrated in this application here:

http://nasa-gibs.github.io/data-curtains/index-1.10.html

Click on the red or blue ring around the Earth to bring up a profile image. Spinning the globe around should leave a ghost trail in the sky regions. This does not occur with version 1.9 which can be found here:

http://nasa-gibs.github.io/data-curtains/index-1.9.html

This occurs in Firefox and Chrome.

**Comment by mramato** [comment] 2015-06-15 19:20
I have seen this randomly with 1.10 as well.  It might be related to #2790, in either case it's a pretty bad regression so I'm marking this as a showstopper.

**Comment by pjcozzi** [comment] 2015-06-15 21:00
Thanks for writing this up @mike-mcgann.

@kainino0x let's look at this when we finish #2782 or by next Monday, the 22nd, whichever comes first.

**Comment by emackey** [comment] 2015-06-15 22:04
This is a dup of #2790, because there is picking on every frame.

**Closed** 2015-06-21 17:32 UTC
Labels: show stopper
