### ISSUE TITLE
Fix inconsistency in result parameter 

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7444] opened 2018-12-29 18:50 UTC
It sounds like the intention is to force users to supply a result parameter to prevent accidental bad performance (based on the discussion here https://github.com/AnalyticalGraphicsInc/cesium/issues/1161).

There's still a lot of functions that have an optional result parameter (were these added after that issue was resolved?) For example, all the methods below have an optional result in Cartesian3:

* [Cartesian3.fromSpherical](https://cesiumjs.org/Cesium/Build/Documentation/Cartesian3.html?classFilter=Cartesian3#.fromSpherical)
* [Cartesian3.fromRadians](https://cesiumjs.org/Cesium/Build/Documentation/Cartesian3.html?classFilter=Cartesian3#.fromRadians)
* [Cartesian3.fromElements](https://cesiumjs.org/Cesium/Build/Documentation/Cartesian3.html?classFilter=Cartesian3#.fromElements)
* etc.

Similarly for all the functions here:

https://cesiumjs.org/Cesium/Build/Documentation/Transforms.html

I _personally_ like it when it's optional because I usually just end up throwing an inline `new Cesium.Cartesian3()` since it's usually something that runs only once, but I think regardless of my personal preference the library should be consistent. It's very annoying to try to remember which methods required a result and which didn't.

**Comment by mramato** [comment] 2019-01-02 15:07
* `fromXXX` elements are almost always used to create new instances so they intentionally do not require a result parameter.  This shouldn't change.

* I think `Transforms` was just missed the first time around and it would be a hassle to update everything to enforce it (since it's a breaking change).

I think everyone would love to get rid of result parameters completely, but they are an unfortunate requirement for writing performant JS.  We could probably just close this unless there are lots of other examples of non-fromXXX functions that have it as optional.

**Comment by hpinkos** [comment] 2019-01-02 15:10
Yeah, I agree.  The API is this way by design.

**Comment by OmarShehata** [comment] 2019-01-02 15:11
Thanks for the context. I'm fine with closing. I (or anyone else) can re-open if more functions like that are found that were missed.

**Closed by hpinkos** 2019-01-02 15:10 UTC
