### ISSUE TITLE
Polyline Dash can not display

### ISSUE THREAD

**Issue by WanghuiShmily** [AnalyticalGraphicsInc/cesium#7943] opened 2019-06-17 07:47 UTC
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=xZZtb9owEMe/isUbgkTNc1cxisYAbZVYQeyhQstemOSaWHNsZBtQWvHddyRMQIYGlaC9vIh9vv/p7n6KlQXTZMFhCZrcEglL0gXD5xH9kficvJdsu0paxiXofOG9K125QJUGf4AulKV6CtJyy8FQ5vvOsysJmmQRkCbJj8EnPjMhvgSK8sX0eKZEvN5jyEaQeg0mUtKge1NOl2mLKyZr9FGrqAeBBjAdrVn8GXgQWuP8vHrXKJLaTZFUG2W04jbhS+2qUt1L9auwk2zJfRtiZY0dX8QsaM4EundmONp018PGv2wiRlrNQNvYed4vz1NC6W276x0d93vboFUhXa9cudpCmIo5nE7hgfuQSHZZYEPYDyMBm6VVXA5OvXw2ONtUB+HUyuenQzJ4Pg6+9zN94Ay7B0BO+oPB8OEYS6WZDF5Ac5jEH0JpQqVtckAEyMCGF0RaPQPSfbLV1/7ssmCH4879pyza9TQHyTCb5IaWj8H0YiZPR9nF6EMgE4QzZrEJSS8IsX52iPX/Qqy8wufZnXTuDzAcpdNs4li1gTtpnXylUk6sgpbHugvH4MYghFqejneSxL8l4OuzA75+c8DprXoi4vL+cxxzSvVJqeibcjKM1yG5Yq5lbCygnUo/8Gi2vnXnWjiUlixEM4FdmdJ07v0GSz2TyFqlv6KWzxeE+7duLvOP5eaIJ5gxePI4F+IrfwI3126VMH5PJhTzuQyGC9CCxeuQsNIepE5KaauE239VVikxZXon4x8

**Comment by OmarShehata** [comment] 2019-06-21 00:30
Please provide a bit more context to the issue. Specifically, what the expected result is vs what actually happens. Screenshots help here as well as stating what browser, device and OS you're using.

**Comment by WanghuiShmily** [comment] 2019-06-21 08:47
I find Polyline Dash can not display when I using WIN7 and Chrome, There is borwer warning.
[.WebGL-000000000B5B5AD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: GL_BLEND with floating-point color attachments requires the EXT_float_blend extension
bucket.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.
Polyline Dash can be rendered When I using WIN10.

**Comment by OmarShehata** [comment] 2019-06-21 12:46
I think you may be running into the same issue as described here: https://github.com/AnalyticalGraphicsInc/cesium/issues/7798

Do you also see the transparency problem on the cylinders? What version of Chrome are you using? Can you try Chrome Canary 77.0.3820.5?

**Comment by WanghuiShmily** [comment] 2019-06-24 06:49
you are right, [#7798](https://github.com/AnalyticalGraphicsInc/cesium/issues/7798) issue and the transparency problem on the cylinders I can see. Set the orderIndependentTranslucency value to false can solve this problem.

**Comment by OmarShehata** [comment] 2019-06-24 18:48
Thanks for confirming @WanghuiShmily ! I'm going to close this as a duplicate of the above issue, and it should work once Chrome 77 is officially out.

**Closed by OmarShehata** 2019-06-24 18:48 UTC
