### ISSUE TITLE
reload the same geojson data  for the second time, the points don't display

### ISSUE THREAD

**Issue by diversoft** [AnalyticalGraphicsInc/cesium#7829] opened 2019-05-10 14:21 UTC
I load points and polylines from geojson,
setting point display as point or billboard, 
at first time load the data , they can display and fly to the extent, but the second time polyline can display , point or billboard can't.
the code below:

```
loadLayer (flyTo) {
      if (this.mapViewer.dataSources != null) {
        this.mapViewer.dataSources.removeAll()
      }
      const geojosndata = this.mapGeoJson
      const that = this
      const promise = Cesium.GeoJsonDataSource.load(geojosndata, { clampToGround: true }) 
      promise.then((dataSource) => {
        that.mapViewer.dataSources.add(dataSource)
        const entities = dataSource.entities.values

        for (let o = 0; o < entities.length; o++) {
          const r = entities[o]
          // console.log(r)
          if (r.properties && r.properties.id) {
            r.nameID = r.properties.id.getValue() 
          }
          if (r.polyline) {
            r.polyline.width = 1.5 
            r.geotype = 'trackline'
          } else {
            r.geotype = 'intrestedpoint'
            r.billboard = undefined
            if (r.properties) {
              let txtLabel = null
              if (r.properties.label) {
                txtLabel = r.properties.label.getValue()
              }

              r.point = {
                pixelSize: 16,
                color: Cesium.Color.CORNFLOWERBLUE,
                // outlineColor: Cesium.Color.BLUE,
                heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
                outlineWidth: 0,
                show: true
              }

              if (txtLabel) {
                r.label = {
                  text: txtLabel,
                  font: '16pt Helvetica Neue, Helvetica, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Arial, sans-serif',
                  fillColor: Cesium.Color.GOLD,
                  style: Cesium.LabelStyle.FILL,
                  backgroundColor: Cesium.Color.CORNFLOWERBLUE,
                  heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
                  outlineWidth: 2,
                  outlineColor: Cesium.Color.BLUE,
                  pixelOffset: new Cesium.Cartesian2(0, -22),
                  show: true
                }
              } 
            }
          }
        }
        if (flyTo) {
          that.mapViewer.flyTo(promise)
        }
        that.mapViewer.scene.requestRender()
      })
```

 

Sandcastle example: 

Browser: chome 74.0.3729.131

Operating System: windows 10

**Comment by diversoft** [comment] 2019-05-11 00:47
when rotate the map, the points will float to other position

**Comment by OmarShehata** [comment] 2019-05-13 19:08
Can you share a full example I can run in Sandcastle? (https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) 

My best guess is that the points are underground, that's why they shift when the camera rotates. You can confirm this by running: 

```
viewer.scene.globe.depthTestAgainstTerrain = true;
```

**Comment by OmarShehata** [comment] 2019-06-03 20:58
I'm closing this for now since this looks like it's not a bug. @diversoft if my suggestion doesn't work feel free to post on the forum and I'd be happy to take a look: https://groups.google.com/d/forum/cesium-dev

**Closed by OmarShehata** 2019-06-03 20:58 UTC
