### ISSUE TITLE
Labels running over the date line are being cropped in 2D view

### ISSUE THREAD

**Issue by jeffwhitty** [AnalyticalGraphicsInc/cesium#4717] opened 2016-12-05 04:12 UTC
When I mouse over a point I write an identification label to the same location with a small pixeloffset to the right. When the point is near the date line (eg 179' E) at any latitude, the text in the label stops at the date line. I have seen the effect happen between letters or in the middle of a letter, as though the base map on the West side of the line is rendered on top.

I'm in 2D mode and the base map correctly wraps continuously. Browser is Chrome, Cesium is the December '16 release but I believe this is a long term bug.

**Comment by hpinkos** [comment] 2016-12-05 17:44
Thanks @jeffwhitty.  This looks like a duplicate of #3960, so I'm going to close this issue

**Closed by hpinkos** 2016-12-05 17:44 UTC
