### ISSUE TITLE
Tile rendering error when switching 2D/3D with Terrain

### ISSUE THREAD

**Issue by maikuru** [AnalyticalGraphicsInc/cesium#2841] opened 2015-06-26 13:10 UTC
When using STK Terrain and starting in 2D mode there are issues rendering tiles when you switch to 3D mode.
https://groups.google.com/forum/#!topic/cesium-dev/ewfM4857CkU

![l3gx0e0](https://cloud.githubusercontent.com/assets/1457734/8377848/d385a88c-1be2-11e5-8cf6-77bcff73ca6c.png)

**Comment by mramato** [comment] 2015-06-26 13:14
This is a duplicate of #2474

**Closed by mramato** 2015-06-26 13:14 UTC
