### ISSUE TITLE
Terrain in 3d-tiles branch constantly refreshes

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/cesium#3690] opened 2016-03-09 16:26 UTC
If you load a buildings tileset on Terrain, the terrain constantly reloads/unloads. I'll send the tileset offline. Just load that tileset in the Sandcastle 3dTiles example and enable terrain.

**Comment by pjcozzi** [comment] 2016-03-09 16:36
@lilleyse can you look at this?  Perhaps also test the request scheduler branch off of master.

**Comment by lilleyse** [comment] 2016-03-09 16:43
Yes I'll look into this.

**Comment by tsmith717** [comment] 2016-03-09 18:07
please ping me when this fix is in - we have 3 customers that need this. Thanks!

**Comment by lilleyse** [comment] 2016-03-09 20:08
It looks like this is actually a bug in master, not 3d-tiles or `RequestScheduler` related. If you turn terrain on while the flat terrain is still loading, you may run into this issue.

**Comment by lilleyse** [comment] 2016-03-09 20:10
Test with the following Sandcastle code:

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.camera.setView({
    destination : Cesium.Cartesian3.fromRadians(-1.7057552114756511, 0.5283611246285218, 825.9580134720799)
});
```

Then quickly turn terrain on before the globe fully loads.

**Comment by lilleyse** [comment] 2016-03-09 20:27
The problems are starting with: https://github.com/AnalyticalGraphicsInc/cesium/pull/3593 @bagnell You may have a better idea here.

This code should reproduce the problem:

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.camera.setView({
    destination : Cesium.Cartesian3.fromRadians(-1.7057552114756511, 0.5283611246285218, 825.9580134720799)
});

var cesiumTerrainProviderMeshes = new Cesium.CesiumTerrainProvider({
    url : '//assets.agi.com/stk-terrain/world',
    requestWaterMask : true,
    requestVertexNormals : true
});

window.setTimeout(function() {
    viewer.terrainProvider = cesiumTerrainProviderMeshes;
}, 1000);
```

**Comment by bagnell** [comment] 2016-03-09 20:45
I found the issue and am working on a fix.

**Comment by pjcozzi** [comment] 2016-04-13 13:55
Fix3d in #3696.

**Closed by pjcozzi** 2016-04-13 13:55 UTC
