### ISSUE TITLE
Transparent objects flicker when using scene.pick

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#5307] opened 2017-05-10 20:32 UTC
When moving the mouse around in an app that uses scene.pick, translucent objects flicker. The gif capture is not best, the flickering is much faster.

![flickery](https://cloud.githubusercontent.com/assets/915398/25919671/5f8dec7e-359d-11e7-833d-033419285a50.gif)

Sample code:

http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=eaae1407cd39601a2c3ba62b30f00a1f

**Comment by emackey** [comment] 2017-05-11 17:37
This brings back bad memories of #2790.  That bug was caused by a stray scissor test preventing the frame from being cleared at the start, causing OIT to blend with the previous animation frame.  It was fixed, and I don't know if this new problem is some way related, but the symptom looks suspiciously similar.

**Comment by pjcozzi** [comment] 2017-05-11 21:20
Could someone track down what version/commit this was added?  It could be a fix we want soon.  I'm surprised it hasn't come up on the forum and in other issues.

**Comment by mramato** [comment] 2017-05-26 17:48
This does not happen in 1.32, so it was introduces recently.  It's really annoying so I marked this for next release, someone needs to at least triage this.

**Comment by mramato** [comment] 2017-05-26 17:49
I'm also running into cases where picking randomly stops working until the canvas is resized, but that could be an unrelated issue.  Unfortunately it's hard to reproduce.

**Comment by pjcozzi** [comment] 2017-05-26 18:18
@emackey do you want to help @klingerj track this down?

**Comment by klingerj** [comment] 2017-05-26 18:33
Git bisect says that the first bad commit is: a9a275f8e6286ae509633d00cc622d195ad4e29b

**Comment by bagnell** [comment] 2017-05-26 19:26
Thanks for finding the commit @klingerj. I have a fix for this. I'll open a PR soon.

**Closed** 2017-05-26 21:41 UTC
Labels: bug, next release, priority
