### ISSUE TITLE
Awkward touch camera tilt in Chrome on Dell Venue 8

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1851] opened 2014-06-23 15:23 UTC
Using Chrome on the Windows 8 Dell Venue 8 Pro tablet, all the touch events work, but two-finger swipe up and down to tilt the view makes the globe wobble slightly as it tilts.  Perhaps we can filter out some of the events to smooth this.

There are also nine test failures that we can look at separately.

CC #1847

**Comment by mramato** [comment] 2015-01-30 21:30
This is still an issue, perhaps related to #2122

**Comment by mramato** [comment] 2015-10-14 21:51
@emackey do you think this is just a dupe of #2122?  Should we close this one?

**Comment by pjcozzi** [comment] 2015-10-14 22:12
Up to you guys, but I am OK closing this.

**Comment by emackey** [comment] 2015-10-15 13:15
I don't have a Dell Venue 8 to test on.  You could show it to me when you get back, or just close it, I'm fine either way.

**Comment by mramato** [comment] 2015-10-15 13:19
@emackey I guess you'll just have to drive up to the Poconos today for the sprint, since it's sitting next to me :wink:

If not, I'll stop by next week to confirm it's the same thing and we'll close this.  Thanks,

**Comment by mramato** [comment] 2015-10-23 18:53
Me and @emackey looked at this and think it's a dupe of #2122 that happens on all touch devices.  It may also be related to framerate issues and the speed to which we can respond to events on lower-powered devices, either way I'm closing this and we can address it in the linked bug.

**Closed by mramato** 2015-10-23 18:53 UTC
Labels: mobile
