### ISSUE TITLE
Labels don't show for individual entities in datasources when clustering is enabled

### ISSUE THREAD

**Issue by thw0rted** [AnalyticalGraphicsInc/cesium#6087] opened 2018-01-04 14:36 UTC
## Issue ##
Entities won't show a label if their owning datasource has clustering enabled

## Reproduction ##
Open [this Sandcastle example](https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=feffb215b113ede4b0279105c94eec0a), slightly modified from the basic Clustering demo, then toggle the "Enabled" checkbox. Be sure to zoom in enough that some entities are not clustered.  Observe that individual (non-clustered) entities show a label when clustering is disabled, but the label disappears when `clustering = true`.

----

I'm not sure if this is a recent regression or not, as I've updated Cesium a number of times in the last 2 months and just started noticing the problem recently.  In the example, the entities are created from a KML source, but in my application I observe the same problem with entities I create manually and control with a CustomDataSource.

**Comment by ggetz** [comment] 2018-01-04 20:03
Thanks @thw0rted for the report! I bevel this may be a regression, I see the labels were applied correctly [during the initial PR](https://github.com/AnalyticalGraphicsInc/cesium/pull/4240#issuecomment-242932864). If you have the bandwidth to look at this, we'd greatly appreciate if you could contribute a fix or track down the cause.

**Comment by ggetz** [comment] 2018-01-05 14:31
We already do: http://cesiumjs.org/releases/1.39/index.html

I believe the share button will export a URL that uses the same build as well.

**Comment by thw0rted** [comment] 2018-01-05 14:59
Holy cow, this has been around for a while.  I didn't think to check, but the points did in fact have labels in the Sandcastle example as it was originally implemented, so you can just load the "stock" Clustering demo and toggle Enabled to test.  I tried as far back as 1.26, which worked as shown in the PR screenshot you linked.  Then I tried 1.27, and it's already broken (!).  So, I guess it "never" worked except for the one original release.

I guess clustering must not be too popular since I seem to be the first to notice this?  That, or nobody uses labels and clustering for the same data...

**Comment by ggetz** [comment] 2018-01-05 16:09
Thanks for tracking this release down @thw0rted! As far as I've seen, clustering is used mostly just billboards which is why it may have gone unnoticed. 

@bagnell Do you know what may have happened between these releases?

**Comment by emackey** [comment] 2018-01-08 21:13
https://github.com/AnalyticalGraphicsInc/cesium/issues/4919#issuecomment-353085337

**Comment by thw0rted** [comment] 2018-01-09 11:35
Thanks @emackey , I saw that issue but didn't notice your comment about missing un-clustered labels further down the thread.  Up to you if you want to track both problems under the same issue # or keep this one open.

**Comment by emackey** [comment] 2018-01-09 16:27
Let's keep this one open, it's much clearer that this is one specific issue.  I'll close the old one.

**Comment by ggetz** [comment] 2018-01-09 20:56
Moving relevant forum thread here: https://groups.google.com/forum/#!topic/cesium-dev/9jEuuGdzmbU

**Comment by emackey** [comment] 2018-01-09 22:02
Hi @ggetz, sorry, that thread is not relevant.  This issue is exclusively for clustering non-empty strings.

**Comment by hpinkos** [comment] 2018-08-08 17:17
Also reported by @ollazarev in #6897  (see #6897 for a great minimal code example)

`EntityCluster` might need a sizable overhaul to get this to work.  The main problem is that it's working too much at the primitive level and incorrectly assumes that each entity has either a label, a billboard, or a point (not a label and a point).

**Comment by OmarShehata** [comment] 2018-11-13 18:20
I think this is the same issue described in this forum thread:

https://groups.google.com/forum/#!topic/cesium-dev/urW44wpGJZk

**Comment by thw0rted** [comment] 2019-01-07 11:36
First, @OmarShehata , is this maybe related to #7446?  Second, I haven't messed with clustering in a while but now find myself needing it, and need the labels to work properly -- is there any chance that this will get addressed in an upcoming release?  If it isn't fixed soon, I will have to look at "burning in" the labels as part of the billboard image, which is pretty limiting.

**Comment by OmarShehata** [comment] 2019-01-07 13:44
@thw0rted it seems like that's the issue. When applying the suggested fix from that issue I can see the labels in your original example. Here's my diff:

https://github.com/AnalyticalGraphicsInc/cesium/commit/a809398f15162cd926c13f8a8c11891a15f852d6

I don't know that we have someone actively working on this, but I think if there's a community PR open I'm sure it'll make it in for release.

**Comment by thw0rted** [comment] 2019-01-10 17:11
In case it helps I can confirm that the linked patch resolves the issue.  I've been begging my management for approval to sign a CLA for well over a year now, but I'll go ahead and ask again in case they forgot :-/

**Comment by emstrabala** [comment] 2019-04-11 14:49
Is this issue going to make a build anytime soon?

**Comment by hpinkos** [comment] 2019-04-11 16:14
@emstrabala sorry, this hasn't been a priority for us.  We would be more than happy to review a pull request though if anyone has time to look into the issue

**Comment by bbehling-trimble** [comment] 2019-07-15 20:29
Are we waiting on a merge conflict? 

We need to have this feature working too.

**Comment by OmarShehata** [comment] 2019-07-16 00:08
@bbehling-trimble I think the PR https://github.com/AnalyticalGraphicsInc/cesium/pull/7744 just hasn't had a reviewer yet. Can you test that branch and confirm that it fixes the issue? That'll help a lot in getting it out by the next release!

**Comment by hpinkos** [comment] 2019-09-19 15:15
Fixed in #7744

**Comment by cesium-concierge** [comment] 2019-09-19 15:15
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/urW44wpGJZk

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/6087 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed** 2019-09-19 15:15 UTC
Labels: category - graphics, type - bug
