### ISSUE TITLE
Inspector 'Show Frustums' breaks with OIT

### ISSUE THREAD

**Issue by kainino0x** [AnalyticalGraphicsInc/cesium#2747] opened 2015-05-22 20:10 UTC
It seems that OIT uses `gl_FragData`, but Show Frustums uses `gl_FragColor`.

```
An error occurred while rendering. Rendering has stopped.

RuntimeError: Program failed to link.  Link log: Cannot use both gl_FragColor and gl_FragData in the same fragment shader.

Error
    at new RuntimeError (http://localhost:8080/Source/Core/RuntimeError.js:42:19)
    at createAndLinkProgram (http://localhost:8080/Source/Renderer/ShaderProgram.js:181:19)
    at initialize (http://localhost:8080/Source/Renderer/ShaderProgram.js:367:23)
    at ShaderProgram._bind (http://localhost:8080/Source/Renderer/ShaderProgram.js:384:9)
    at beginDraw (http://localhost:8080/Source/Renderer/Context.js:1805:12)
    at Context.draw (http://localhost:8080/Source/Renderer/Context.js:1867:9)
    at DrawCommand.execute (http://localhost:8080/Source/Renderer/DrawCommand.js:185:17)
    at executeDebugCommand (http://localhost:8080/Source/Scene/Scene.js:1082:21)
    at executeCommand (http://localhost:8080/Source/Scene/Scene.js:1099:13)
    at executeTranslucentCommandsSortedMRT (http://localhost:8080/Source/Scene/OIT.js:507:13)
```

**Comment by mramato** [comment] 2015-05-22 20:53
This is actually a dupe of #2448, so I'm going to close it, but thanks for the additional info.

**Closed by mramato** 2015-05-22 20:53 UTC
