### ISSUE TITLE
Black terrain artifact

### ISSUE THREAD

**Issue by YousefED** [AnalyticalGraphicsInc/cesium#4032] opened 2016-06-20 15:56 UTC
See screenshot below:

![image](https://cloud.githubusercontent.com/assets/368857/16201091/5b486d2e-3710-11e6-85a3-703aff1d3974.png)

Steps to reproduce:
- http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Camera.html&label=Showcases
- change setHeadingPitchRoll to function below
- run
- click "Set camera with heading, pitch, roll" from dropdown to run code

```
function setHeadingPitchRoll() {
    Sandcastle.declare(setHeadingPitchRoll);

    var camera = viewer.camera;
    camera.setView({
        destination : new Cesium.Cartesian3(1288857.3292931253, -4338373.750901034, 4488506.669268853),
        orientation: {
            heading : 0.1765,
            pitch : -0.4667,
            roll : 0
        }
    });
}
```

OS: Windows 10
Browser: Chrome 51.0.2704.103 (also seen on firefox)

**Comment by hpinkos** [comment] 2016-06-23 20:36
Thanks @YousefED!  I was able to reproduce this based on the steps you provided

![weird-terrain](https://cloud.githubusercontent.com/assets/3451886/16319291/a2fc0480-3960-11e6-847b-d875e00f312d.gif)

**Comment by YousefED** [comment] 2016-09-17 11:15
Fyi, I',m seeing this bug for more locations, e.g.:

I'm open to looking into this, but have little experience with the internal 3d engine, so I'm not sure where to start

```

function setHeadingPitchRoll() {
    Sandcastle.declare(setHeadingPitchRoll);

    var camera = viewer.camera;
    camera.setView({
        destination : new Cesium.Cartesian3(4471707.323258337, 675395.3016673529, 4486939.158518577),
        orientation: {
            heading : 5.942565929933654,
            pitch : -0.4636476090008035,
            roll : 6.283185307179586
        }
    });
}
```

**Comment by pjcozzi** [comment] 2016-09-19 18:45
The culling volume may not be properly synced with the camera view.

@YousefED you are welcome to look into this, but it might not be easy first issue to track down (instead check out [these](https://github.com/AnalyticalGraphicsInc/cesium/issues?q=is%3Aissue+is%3Aopen+label%3Abeginner)).

Also, are you using Cesium for TweetBeam?  Do you have a demo?

**Comment by mramato** [comment] 2016-09-19 18:46
I swear we have a very similar bug opened for this already that involved flying the geocoder to specific locations, but now I can't find it.

**Comment by mramato** [comment] 2016-09-19 18:48
Nevermind, I was thinking of #3676, which is already fixed.  Sorry for the noise.

**Comment by YousefED** [comment] 2016-09-19 18:52
@pjcozzi Nope, for Relive.cc - I think you've already seen it on Twitter, and we're in touch with your team re. a showcase :)

**Comment by YousefED** [comment] 2016-09-22 08:55
@pjcozzi Sorry to "bug" you about this, normally wouldn't bring it up again; but the bug seems to affect one of our users on a ride with Richard Branson 😅  If a quick look from your side could help assess whether a quick fix could be possible (and where I should look), or whether it affects a large part of the render engine (in this case I probably can't help) - that would be extremely helpful.

**Comment by pjcozzi** [comment] 2016-09-24 20:28
@YousefED sorry, I am fully committed for quite a while to come; however, I labeled this as "bug bash" so perhaps someone will take a look then: http://cesiumjs.org/2016/09/19/Cesium-Bug-Bash/

**Comment by duvifn** [comment] 2017-01-11 12:41
@mramato you probably meant #4698 which is the same bug and they both happen in `lat` 45

**Comment by duvifn** [comment] 2017-03-26 17:17
Steps to reproduce:
    1.  Type `101 45` in the geocoder.
    2.  Zoom out until the scene level is 16 (as reported by Cesium Inspector's `Show Tile Coordinates`).
    3.  Move the camera slightly toward south .
    4.  The tiles north to the `latitude 45` should disappear.
 
![reproduce](https://cloud.githubusercontent.com/assets/17128619/24333396/e3333e64-125f-11e7-93df-6ec0f5197b9a.png)

Workaround:
    Turn off the fog:
    `viewer.scene.fog.enabled = false`

**Comment by duvifn** [comment] 2017-03-26 17:19
The problem is that the south plane of `TileBoundingBox` (in the northern hemisphere) is not bounding the tile, as in the following animation.
![level_2_before2](https://cloud.githubusercontent.com/assets/17128619/24333483/5478b580-1261-11e7-8395-f28696337c0c.gif)


As a result the distance that is reported by `TileBoundingBox.distanceToCamera` might be wrong by up to ~250 Kilometers with tiles of the lower levels.
Therfore the fog is culling them and so their descendants are not selected for rendering either. 

In the southern hemisphere the north plane is the problem.

[These specs](https://github.com/duvifn/cesium/blob/fix_tileBoundingBox2/Specs/Scene/TileBoundingBoxSpec.js#L74-L114) are failing in master.
This plane calculation first appeared in `Cesium-b10`.

For my own needs I fixed this in [this branch](https://github.com/duvifn/cesium/tree/fix_tileBoundingBox2). If you think this fix is good also for Cesium I'd be glad to open a PR.
My solution is to calculate the plane in a slightly different way.

**Comment by hpinkos** [comment] 2017-03-27 12:35
Thanks @duvifn! It would be great if you want to open a pull request with that fix.

**Comment by duvifn** [comment] 2017-03-27 14:52
Thanks @hpinkos!
I opened a PR.

**Closed** 2017-03-28 07:01 UTC
Labels: bug, priority

**Comment by YousefED** [comment] 2017-03-28 10:01
Great stuff, thanks @duvifn
