### ISSUE TITLE
flickered when addition any entity to 2D map in a small view area.

### ISSUE THREAD

**Issue by AnodoubleA** [AnalyticalGraphicsInc/cesium#8450] opened 2019-12-09 09:34 UTC
Do this :
1. Create a viewer;
2. Zoom to small view area (Must be);
3. Addition any entity in entities;
4. You will see that!

**Comment by OmarShehata** [comment] 2019-12-09 14:58
@AnodoubleA can you please provide a [Sandcastle example](https://sandcastle.cesium.com/index.html?) reproducing this? You can make the example there, click "share", then copy and paste that link here.

**Comment by OmarShehata** [comment] 2019-12-10 13:29
Closing since we can't reproduce this. Feel free to follow up here with a reproducible example or ask [for help on the forum](https://groups.google.com/forum/#!forum/cesium-dev).

**Closed by OmarShehata** 2019-12-10 13:29 UTC
