### ISSUE TITLE
KML Lines not clamped to ground

### ISSUE THREAD

**Issue by fironalia** [AnalyticalGraphicsInc/cesium#8404] opened 2019-11-18 12:52 UTC
i have a kml that i want to add it to cesium, this kml contains lines and polygones.
 polygones clamped to ground works fine, but lines are not working, is there any way to do it? or it is really a problem ??

**Comment by Crocsx** [comment] 2019-11-19 09:10
Might be related to https://github.com/AnalyticalGraphicsInc/cesium/issues/4326

**Comment by fironalia** [comment] 2019-11-19 15:32
this problem is related to kmldatasrouces.Only lines are not clamped.

**Comment by OmarShehata** [comment] 2019-11-19 16:54
@fironalia please share a Sandcastle example reproducing this issue. If you're not sure if it's a bug you can always ask [on the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev).

**Comment by fironalia** [comment] 2019-11-19 17:02
@OmarShehata i am sure it is a bug, points and polygones are clamped to ground, but lines are not.
if you load any kml file that contains lines you will see that these lines are not clamped.
Polygones and points works fine.
i am loading points and polygones the same way with the lines.so for sure it is a bug, or there is something else missing that i dont know it.

**Comment by OmarShehata** [comment] 2019-11-19 17:21
@fironalia submitting a complete bug report requires putting together a reproducible code example that shows the issue so we can test/debug it. Otherwise it's unclear whether the problem is in your code, or if it is a bug, where the issue may be.

For example, are you setting the clampToGround option when loading the KML as shown in the docs? https://cesium.com/docs/cesiumjs-ref-doc/KmlDataSource.html?classFilter=kmlData#.load

Here's a [code example that shows](https://sandcastle.cesium.com/index.html#c=fVVtj5s4EP4rVu5DEykFA7aBLaV36puq7l4jbXr3JR/qgLNBa3Bkm2TT0/33G3CSJdnm+AB4PM888+LxbLlG20rshEZvUSN26L0wVVt7f/Wy8auiX75XjeVVI/SrKfpn0SB4rNAaRDOttlUp9M0RWGjBrfhbaVnOncp4smj+nbxZNFvgUhtbqcYA2cFOwWuhObo5eOGZQjTCc9LpUQWg5qVKJz2qSF5v5uqzVm1T3iCrWwGkwOlYH2vZhSAaC8Q/sndPtURboQ248nYxCjy8GCHRFKqsmgcQfJ9/ep0sRu/yRZMBFIF6Y0C+tnZz4/u73c5TG9E8VMZrhPVBxQ+9cDHKO2eyD6poa6DKnWtZA7HkM27XJvP7/4O8FKbQVZ+P/OMT+C+FQWqFNp2qh/5UViC75hZe8COMEVLyTsYfUGXQco9KseKttM4eQkaArkLYQ19WaK9atONNL3E1GdgokYRqmmlneo/q1li0FIi3dq20KI/2xkojUVagPkFlpUVh5R5VDfp6d+tl/tD9Q0T3di8FqkpI1R6I1O4WWD5rIZqZkvtDfnrNbqPXPolAWCipdB6vMF7Bk/luPVDYVaVd5yTz3c/Jmv/SXNYx/i8DxpcMmX8Jyvyz1UzyQtRcPz5D+oL+sTRKtpDhj09w8kpRnhX6otRzzRuz4bo7jA9dbqBMUqJdZdfIZQ2p1vb1+VWSwZrpfPquZf7bL7Kc+afti2xrONzDZHBpKwve3qlS5GcNlPlnewPM8xHKg8wfrM6SrDQ0EkhNjl4HAbQGpThOaBTFcRpMI+bhOKUkpWFAKCPxNIxo/GwAHUEkDeMYR2kcJT0oCYIYJxGIgzC8BqIhxRSzFLPIgUKGYxZEOA7j9BqIEUpwQJMoZg4UpZQxTJMETF0DJTiMkjRmhKQORIMArGBCkiC6BuqCTkiSYojAgRISgdNRGqXkCohBEAGLSAx6DsSCENaUAPpaTCzEcUTChNFDSAzsBGnn5dWMsygKMaQ3gdocQQEN0oRhDIW7AoL4WZQQ+JIjKIa8pISG8dWQKEtZSinpAnAg4ExTDHUjDoQGR8ofnqnLth+ca+jgsxbN/MFlnHUXdf7jNBSgB81p7H34djfr1+PjpAJlAMO20/P6zyetasc4fp4pU7QYWfFkfZgTi1GPd4Pqp1L1XI0Pq5Jbfq9aDSPV42U5PgzMr8Bz2vGk4uXYUU+Pw3IymbwZTUeu7w+R/l7VG6UtarUcex50IoyPLjv+si0ehfUKYzpHDrdBF31Zbd3VfDHSYfRB85tuvq1aKe+rnwJuarh6qu0ZrPMM4v4Gc1Py7jLP1kF+64SeBwMBli9RVim55Hpg8T8) that shows a line from a KML file clamped to ground in CesiumJS.

**Comment by fironalia** [comment] 2019-11-19 17:48
i really thank you for your fast replies.
in the example, you are assigning to the coordinates an Altitude value (2357), i am not assigning an Altitude value to line coordinates same for the polygones. polygones without any altitude value, Clamped to ground works. but with lines it does not work.

**Comment by fironalia** [comment] 2019-11-20 04:41
@OmarShehata  this is an example for a kml file that conains one line and one polygon, if you want to try it. you will see that lines are clamped to ellipsoid and not to the terrain.
and the javascript code is :
var kml = kmlDataSrouce.load('http://examplehost/example.kml',
{
     camera : viewer.scene.camera,
     canvas: viewer.scene.canvas,
     clampToGround : true
});
viewer.dataSources.add(kml);

**Comment by fironalia** [comment] 2019-11-21 15:56
@OmarShehata am i right or wrong ?

**Comment by OmarShehata** [comment] 2019-12-02 12:40
@fironalia your line is not clamped because the tesselate flag is false by default. You can fix this by adding `<tessellate>1</tessellate>`. I'm closing this because it's not a bug. I opened a PR inhttps://github.com/AnalyticalGraphicsInc/cesium/pull/8428 to add a warning when the clampToGround flag is ignored or perhaps to document the cases when a line cannot be clamped.

**Closed by OmarShehata** 2019-12-02 12:40 UTC

**Comment by fironalia** [comment] 2019-12-05 15:51
@OmarShehata 
when i add <tessellate>1</tessellate> a message shows : An error occurred while rendering.Rendering has stopped.
i added tessellate to the same example i have sent right after the altitudeMode.

**Comment by fironalia** [comment] 2019-12-08 12:42
@OmarShehata 
i tried the file "example1" with `<tessellate>1</tessellate>`  in googleEarth and no error occured.
but in cesium the same message shows "An error occurred while rendering.Rendering has stopped.Undefined Object"
