### ISSUE TITLE
Definitely Typed

### ISSUE THREAD

**Issue by CHBaker** [AnalyticalGraphicsInc/cesium#5896] opened 2017-10-10 18:21 UTC
Hello, I was working through some 3rd party lib examples for Angular,
and I think it would be awesome if we could
get cesium into [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

I'm not sure exactly what it would take to do this, but I would love to contribute. I think it would be a good idea to get a **community** going to **strong type cesium with DefinitelyTyped for npm**.

Let me know what your thoughts are, and if anyone else would be interested

**Comment by ggetz** [comment] 2017-10-10 20:13
Hi @CHBaker, I'm not particularly familiar with TypeScript, so I'm not sure what all would be involved here. This looks like this might fall under the umbrella of #4434 (or maybe #5717 which is more recent), maybe we can close this and add more discussion there? 

It sounds like a cool idea, but I'm not sure if the core development team has the resources to invest in this right now. We'd definitely welcome any contributions to get things going!

**Comment by mramato** [comment] 2017-10-10 20:22
This is certainly a duplicate of #5717.  @CHBaker there's a bunch of discussion there and I think it's all still pretty relevant.  We'd love to have an automated process for generation of a ts file that we can publish with the release but no one on the core team has the bandwidth to implement it.

**Closed by mramato** 2017-10-10 20:22 UTC
