### ISSUE TITLE
PostProcessStage shader function czm_selected sometimes picks wrong selectedId from czm_selectedIdTexture for certain selection indices

### ISSUE THREAD

**Issue by ctr1key** [AnalyticalGraphicsInc/cesium#7850] opened 2019-05-17 21:29 UTC
PostProcessStage shader function czm_selected sometimes picks wrong selectedId from czm_selectedIdTexture for certain selection indices.

Expected: With the sandcastle below every billboard should have a white shadow billboard in front of it. Change value of 'limit' in the sandcastle to see different set of selected items being missed.

Seems to be caused by floating point issues. Changing the for loop in czm_selected to a float index starting from 0.5 or changing 'float(i)' to 'float(i) + 0.5' should resolve the issue.

Sandcastle example: 
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=hVVtb5swEP4rVr4EpsisVfulSatt6V46TWq1VNuHUkUOHMStsZFtkiYV/31nIJBkbEUJsu/uubvnfD5WTJMVhzVockkkrMkUDC8y+quSecOo2k6VtIxL0EN/HMpQrhAVM8tmqtARILJBfQX13Sh53aqoUCz2hpQG7e9jnptgxrJcgLMLDHdLYzf4oimoJ3RQhanTol0cQ1kce91+z2irVHavjnS7TBPN0gyknS1ZDLrNeUjCMJSF5InSGTFVRvr0msSQ2+U9vNhCw/gfNpESSvfaJMjYEgEytctDzQqisxpYy90f09twmTrdKVnNbe1xqpSOuWQWzLi1VDwmGR6C51a+E726F8GnQiMWBNJyG++EvicBibbZ3BUoV9rS7Yj0SNf+eOeFJ8RzOgMCIguxV3t8V3s8H537vk/amO5JxfwL1nbqOGHkmtu+gQakI1tRuZfwGVGat9CG+Om1t1/ZUW9JuoyP4rcOK4Ny2LaqsSwF42pTd4uJQALNlbF3WmFfmVllMG6suViqAqx1TVJDq8bbux13R1DvtePsnsOOu+jtwNEhpOkSc0GOfLmnKsrFLnrFkUZCSfAORL+/3dx/9g/hZbctfXcrOnp0d9LI8+GxrZbgGbcoOjk/Q1kTYL0ESZkQ3kN3xx5HJClkZLmSxPN3eTc11iCRquciOml/1NvFEy7pM2yMd3A2EQ4cPHg6z3n0XFuZhhhNuLDouQuNcH+/anXXkTcdPiDwkeba8eUrIFziacsIVLKr9CcuxEIxHTcsyv/lMEIHMbz0pVIpyKQu7bGvjOVvk3l1ed/E2B19vZBolf1MF6xCl2UboVkgeaOEG8ap13MQtJ5Wzrqs5+ZgNJhUE/mqdvABZzROC1Jo4eEIt4Bz0F3FYFFEz2BpZNytlJNgB5rEfEV4fBkOjj4g4YBEghmDmqQQYsa3EA6uJgHaH8DcdwMH4+0KtGAbZ7I8ufpRCymlkwC3f6OsUmLB9J7HPw

Browser: Chrome 64-bit 74.0.3729.131

Operating System: Windows 10

**Comment by OmarShehata** [comment] 2019-05-20 14:57
Thanks for reporting this and for the suggested fix! I can confirm that changing the line 

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/PostProcessStage.js#L559

to:

```
                '        vec4 selectedId = texture2D(czm_selectedIdTexture, vec2((float(i) + 0.5) * czm_selectedIdTextureStep, 0.5)); \n' +
```

Fixes this issue. If you want to open a pull request to fix this that would be awesome! You can see the [contributing guide](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request) here.

Otherwise, hopefully we can get to this in this upcoming release.

**Comment by emackey** [comment] 2019-08-11 18:16
@mramato The Sandcastle link above is giving me a 403 (from my home network).  Seems to be caused by the long hash on the end of the URL somehow.

**Comment by mramato** [comment] 2019-08-12 12:42
Thanks @emackey, this is now fixed.

**Comment by lilleyse** [comment] 2019-09-19 15:22
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/7929

**Closed by lilleyse** 2019-09-19 15:22 UTC
Labels: category - post-processing, type - bug
