### ISSUE TITLE
3D Tiles Adjust Height Sandcastle example throws exception

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6212] opened 2018-02-13 17:47 UTC
* Run https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Adjust%20Height.html&label=3D%20Tiles
* Drag the **Height** slider
* Console warning:
```
Uncaught DeveloperError: The tileset is not loaded.  Use Cesium3DTileset.readyPromise or wait for Cesium3DTileset.ready to be true.
Error
    at new DeveloperError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:540:19)
    at Cesium3DTileset.get (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:192285:27)
    at a.zc.jb (<anonymous>:35:66)
    at Function.notifySubscribers (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:228376:203)
    at Function.ha (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:228380:190)
    at Object.c [as height] (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:228379:472)
    at Object.value (eval at parseBindingsString (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:228407:398), <anonymous>:3:185)
    at Object.Ga (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:228401:294)
    at HTMLInputElement.l (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:228441:353) (on line 192285 of https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js)
```

**Comment by mramato** [comment] 2018-02-13 18:52
This is a dupe of #123, but we should definitely fix it for next release either way.  Sandcastle examples should not reference data in Specs.

**Closed** 2018-02-14 21:00 UTC
Labels: category - sandcastle, priority - next release, type - bug
