### ISSUE TITLE
glTF model appears with black shades 

### ISSUE THREAD

**Issue by michaelknave** [AnalyticalGraphicsInc/cesium#5835] opened 2017-09-18 09:03 UTC
I have glTF model of the mesh. I have used obj2gltf for conversion. After I loaded it to Cesium, it showed in black colors. 

I have tried to open it in different glTF viewers, it showed in correct colors.

I assume there is some bug in cesium.

**Comment by lilleyse** [comment] 2017-09-18 13:18
Could you send over the model you're testing?

**Comment by michaelknave** [comment] 2017-09-18 14:42
Hello,

sure. I am sending it in this mail.

Thank You.

Regards,
Michal
​
 Mocsa4_simplified_3d_mesh.gltf
<https://drive.google.com/file/d/0By2tH5pP-77Jd3UxN3JDYkhfQ00/view?usp=drive_web>
​

2017-09-18 15:18 GMT+02:00 Sean Lilley <notifications@github.com>:

**Comment by lilleyse** [comment] 2017-09-19 15:25
Thanks for sending the model over. The problem is we are not generating PBR shaders correctly for models that don't have normals. I opened an issue here: https://github.com/AnalyticalGraphicsInc/cesium/issues/5838.

In the meantime you can use the `--materialsCommon` flag with obj2gltf and this should look correct in Cesium.

**Comment by lilleyse** [comment] 2017-09-19 16:06
I also opened up this PR in obj2gltf to prevent transparency of 0, which is another problem I noticed with the glTF: https://github.com/AnalyticalGraphicsInc/obj2gltf/pull/107

**Comment by michaelknave** [comment] 2017-09-21 13:26
Thank You for the advice, but I am afraid it does not work good in cesium
with materialsCommon...

2017-09-19 17:34 GMT+02:00 Sean Lilley <notifications@github.com>:

**Comment by lilleyse** [comment] 2017-09-21 13:48
Hm.. would you mind also sending the obj model over?

**Comment by michaelknave** [comment] 2017-09-21 13:52
Sure not. My obj file including the textures are in attachment.

Thank You very much.

It would be really helpful if it will be resolved.

Thanks.

Michael
​
 Mocsa4_simplified_3d_mesh.mtl
<https://drive.google.com/file/d/0By2tH5pP-77JTFY0dnplVmxOVTA/view?usp=drive_web>
​​
 Mocsa4_simplified_3d_mesh.obj
<https://drive.google.com/file/d/0By2tH5pP-77JVXNzZlA2ME9mdUU/view?usp=drive_web>
​​
 Mocsa4_texture.jpg
<https://drive.google.com/file/d/0By2tH5pP-77JbFJsazAtckxsOHc/view?usp=drive_web>
​​
 Mocsa4_texture_1_1.jpg
<https://drive.google.com/file/d/0By2tH5pP-77JZGg5dXlweWc1TUE/view?usp=drive_web>
​​
 Mocsa4_texture_1_2.jpg
<https://drive.google.com/file/d/0By2tH5pP-77JN3pSa254cjdKZDg/view?usp=drive_web>
​​
 Mocsa4_texture_2_1.jpg
<https://drive.google.com/file/d/0By2tH5pP-77JNWZQMXBPTWZzY3c/view?usp=drive_web>
​​
 Mocsa4_texture_2_2.jpg
<https://drive.google.com/file/d/0By2tH5pP-77JZHdXVVVkaXFaUEE/view?usp=drive_web>
​

2017-09-21 15:48 GMT+02:00 Sean Lilley <notifications@github.com>:

**Comment by lilleyse** [comment] 2017-09-21 14:50
Ok I realized what the problem was in `obj2gltf` and opened a PR. Make sure to still use the `--materialsCommon` flag.

 https://github.com/AnalyticalGraphicsInc/obj2gltf/pull/108.

Let me know how it goes.

**Comment by michaelknave** [comment] 2017-09-21 14:52
Thanks.

And should it work now with --materialsCommon ? Because it doesn't...

2017-09-21 16:50 GMT+02:00 Sean Lilley <notifications@github.com>:

**Comment by lilleyse** [comment] 2017-09-21 14:56
Until the PR is merged make sure you're on the `constant-lighting` branch. It works for me with this command:

`node bin/obj2gltf.js -i test/mocsa4/Mocsa4_simplified_3d_mesh.obj -o test/mocsa/output/Mocsa4_simplified_3d_mesh.gltf --materialsCommon`

<img width="319" alt="model" src="https://user-images.githubusercontent.com/915398/30702640-7c8fcaae-9ebb-11e7-8196-f5b5fdc88ef3.PNG">

**Comment by lilleyse** [comment] 2017-09-21 14:58
It was just merged so being on master is fine too now.

**Comment by michaelknave** [comment] 2017-09-21 15:01
thank you. I am gonna try it right now and I will let you know.

2017-09-21 16:58 GMT+02:00 Sean Lilley <notifications@github.com>:

**Comment by michaelknave** [comment] 2017-09-21 15:38
I think there there is some issue with the latest master.
[image: Vnorený obrázok 1]

2017-09-21 17:01 GMT+02:00 Michael Knave <mr.kiso@gmail.com>:

**Comment by lilleyse** [comment] 2017-09-21 15:52
@michaelknave You may need to use the github interface to attach an image.

**Comment by michaelknave** [comment] 2017-09-21 15:55
![2017-09-21_1754](https://user-images.githubusercontent.com/11688073/30705536-015fc8b2-9ef6-11e7-9956-ec54fec3b153.png)

**Comment by lilleyse** [comment] 2017-09-21 16:01
Try running `npm run build`.

**Comment by michaelknave** [comment] 2017-09-21 16:35
problem has been fixed. But model is still black...even I followed your
recommendations

2017-09-21 18:02 GMT+02:00 Sean Lilley <notifications@github.com>:

**Comment by michaelknave** [comment] 2017-09-21 16:50
In sandcastle it doesn't apper lighter

2017-09-21 18:34 GMT+02:00 Michael Knave <mr.kiso@gmail.com>:

**Comment by lilleyse** [comment] 2017-09-21 16:56
I'm not sure what else could be the problem. Make sure you are running the latest `obj2gltf`. This is the Sandcastle code I'm using:

```
var viewer = new Cesium.Viewer('cesiumContainer');

function createModel(url, height) {
    viewer.entities.removeAll();

    var position = Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706, height);
    var entity = viewer.entities.add({
        name : url,
        position : position,
        model : {
            uri : url
        }
    });
    viewer.trackedEntity = entity;
}

createModel('../../SampleData/test/mocsa4/Mocsa4_simplified_3d_mesh.gltf', 5000.0);
```

**Comment by michaelknave** [comment] 2017-09-21 17:13
it is working finally ! Thanks for help

2017-09-21 18:56 GMT+02:00 Sean Lilley <notifications@github.com>:

**Comment by lilleyse** [comment] 2017-09-21 17:19
Good to hear!

**Closed by lilleyse** 2017-09-21 17:19 UTC
Labels: category - gltf, type - bug
