### ISSUE TITLE
Draco model crashes when only one primitive is draco compressed

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7495] opened 2019-01-21 16:11 UTC
Reported by Chris Wang [in this forum thread](https://groups.google.com/d/msg/cesium-dev/PiBCIg8HmHg/NfspaVdUEwAJ). The attached model will crash in CesiumJS 1.53.

[draco.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/2779635/draco.zip)

The error is:

```
TypeError: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at Object.ModelUtility.toClipCoordinatesGLSL (http://localhost:8080/Source/Scene/ModelUtility.js:705:20)
    at createResources (http://localhost:8080/Source/Scene/Model.js:3490:61)
    at Model.update (http://localhost:8080/Source/Scene/Model.js:4429:21)
    at PrimitiveCollection.update (http://localhost:8080/Source/Scene/PrimitiveCollection.js:368:27)
    at updateAndRenderPrimitives (http://localhost:8080/Source/Scene/Scene.js:2939:27)
    at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:2778:13)
    at updateAndExecuteCommands (http://localhost:8080/Source/Scene/Scene.js:2586:13)
    at render (http://localhost:8080/Source/Scene/Scene.js:3226:9)
    at tryAndCatchError (http://localhost:8080/Source/Scene/Scene.js:3246:13)
    at Scene.render (http://localhost:8080/Source/Scene/Scene.js:3295:13)
```

It seems like this happens because not all the "primitives" in this model are draco compressed. If you open the glTF, and delete the second primitive, it loads fine (I tested this in the VSCode glTF viewer).

@lilleyse is this intended/expected?

**Comment by lilleyse** [comment] 2019-01-21 16:48
Duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/7383.

**Comment by mramato** [comment] 2019-01-21 16:48
This is a duplicate of #7383

**Comment by cesium-concierge** [comment] 2019-01-21 16:48
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/PiBCIg8HmHg/NfspaVdUEwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7495 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed** 2019-01-21 16:48 UTC
