### ISSUE TITLE
Firefox GroundPrimitive bug

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4524] opened 2016-10-25 17:45 UTC
Reported in the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/p4BBdG6yu2Q

The user said this was a Windows 10 machine using Firefox 49.0.2 and Chrome 53.0.2785.143

http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=cba8726e99322257d7dc7e203df84842 

![image](https://cloud.githubusercontent.com/assets/3451886/19697329/f2790364-9ab8-11e6-800b-3113142d1666.png)

**Comment by mramato** [comment] 2016-10-25 17:49
Please have them share the result of going to `chrome://gpu` in the browser.  This is not a browser specific bug but probably something more specific to the video card or Firefox's version of ANGLE.  Unless we can reproduce this locally, there's no reason to keep this bug open and we need to know the GPU to do that.

**Comment by hpinkos** [comment] 2016-10-25 18:07
see this post for chrome://gpu output: https://groups.google.com/d/msg/cesium-dev/p4BBdG6yu2Q/PkBxFb6GBwAJ

**Comment by mramato** [comment] 2016-10-25 18:09
Looks like they aren't actually using the nvidia card they think they are using and instead it's an Intel HD4000.  I assume they have an optimus laptop and don't realize it.

**Comment by mramato** [comment] 2016-10-26 01:42
I can't reproduce this and posted some suggestions in the forum thread for camila to try.  I'm pretty certain this is not a Cesium bug and recommend closing it.

**Closed** 2017-01-02 20:30 UTC
Labels: bug
