### ISSUE TITLE
Why is the clipping plane different from the actual cut

### ISSUE THREAD

**Issue by PrUnSt** [AnalyticalGraphicsInc/cesium#8053] opened 2019-08-12 02:00 UTC
Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Clipping%20Planes.html

Browser: chrome 73.0.3683.86

Operating System: windows10

![image](https://user-images.githubusercontent.com/30542005/62842861-f1b2b980-bce7-11e9-83d5-7a41b7fd7c03.png)

**Comment by OmarShehata** [comment] 2019-08-12 19:00
I need to investigate a bit more to determine if the issue is in this tileset or not. It may be related to how we changed how we compute the origin point for the clipping planes: https://github.com/AnalyticalGraphicsInc/cesium/pull/7182.

Have you encountered this on your own tilesets, or just on this one? 

For anyone else looking at this, it becomes much more obvious when you set the alpha of the clipping plane to 0.7 or 0.8, it's clear that there's a discrepancy between the clipping plane itself, and the visual plane entity.

**Comment by PrUnSt** [comment] 2019-08-13 01:05
I have encountered this problem on many tileset

**Comment by likangning93** [comment] 2019-08-14 13:51
> It may be related to how we changed how we compute the origin point for the clipping planes

More supporting evidence, there doesn't seem to be a noticeable offset when clipping individual models or terrain.

**Comment by PrUnSt** [comment] 2019-08-30 00:45
how cesium compute the origin point for the clipping planes:

**Comment by OmarShehata** [comment] 2019-12-09 14:47
Just an update that I believe this is fixed in this draft PR: https://github.com/AnalyticalGraphicsInc/cesium/pull/8392

**Closed** 2020-01-19 23:49 UTC
Labels: category - graphics, type - bug
