### ISSUE TITLE
Changing from perspective -> orthographic causes artifacts 

### ISSUE THREAD

**Issue by kring** [AnalyticalGraphicsInc/cesium#8511] opened 2020-01-06 18:25 UTC
1. Run the Projection Sandcastle example (https://sandcastle.cesium.com/?src=Projection.html&label=All)
2. Switch from orthographic to perspective using the switcher in the top right.
3. Switch back to orthographic.

The model vanishes, and if you zoom out a little it looks like this:
![image](https://user-images.githubusercontent.com/924374/71838875-d75aed00-3087-11ea-8cb9-5a7cba16b07f.png)

Zoom and pan around a little and it rights itself.

Windows 10, NVidia GeForce GTX 1650, seen in both Chrome and Firefox.

**Comment by lilleyse** [comment] 2020-01-06 19:42
Duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/8346

**Closed by lilleyse** 2020-01-06 19:42 UTC
