### ISSUE TITLE
EllipsoidTerrainProvider with WebMecatorTilingScheme

### ISSUE THREAD

**Issue by chenfengxueheng** [AnalyticalGraphicsInc/cesium#7928] opened 2019-06-11 02:47 UTC
Sandcastle example: 

Browser:
Chrome 71
Operating System:
Win7

My CesiumJS version is 1.58.When I use EllipsoidTerrainProvider with WebMecatorTilingScheme,The black blocks appears on the globe.
Here is the code and screenshot.

```
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.terrainProvider = new Cesium.EllipsoidTerrainProvider({
    tilingScheme : new Cesium.WebMercatorTilingScheme()
});
```
<img src="https://i.loli.net/2019/06/11/5cff158b5e34181039.png"/>

**Comment by OmarShehata** [comment] 2019-06-11 12:07
This is a regression in 1.57:

[Sandcastle with 1.56](https://cesiumjs.org/releases/1.56/Apps/Sandcastle/index.html#c=ZVLBbtswDP0VwpckQGZh1ywtVhRdYaBZCyTbLr7IMh0TlSWDkpJlQ/99jJ2sySYIkETyPfJRVAo2LQWQrR3gT931FsE3kAK5LdxjoNRBmT03jSWHZTaHDrU7+moKxjuHJmINDfsOYoulU0poIrLTFgp3vGDMAYoIXQoRQiRroUIIyLszUIP1RuL3WI12nkOV4kBWewzgfARGewDvpE45UgxUo9iCT2wkwvOAJLlLti/y7DwjkGv8XDy4GMjaGPuwUGpLsU1Vbnyn7qTQQyRJ/8i6b8mEwhllBuFqT6+kTto/PCZJWbrS7TTDjnCPDDfgcH9qU/59sE0nI/jeu6gFx5M5/C4dyKJOb5EPL+x3QsWwOCMNo464IYsr3a9HHcV18PTEcVyJ7Tu2SmTrla+TxW9sp5O7EDAGtZFfSNIf9VXLqe2D5tgWxWQ20rzN5uOl0gGf9AH5hczrUFOjbcCTd4ve+PrdXLq32aehB4PWXP6XReRfRVf9eLCW+uCp3lxHnaXIKMggrU2LHUqCC+QPrFbIRkfPm4ug6WzIn82zZYgHi7cjz2fqes/x2JZpnquIMsTSzqCqJJJibkI4Fr1UZ9Cyph1QfVNm/3xVmYGxOgTxNMnaNf2Skb9dKom/glmva6nqWSbV6sMxpP14+zQa8zxfKnn+j4re20rzBeMf). Looks fine.

[Sandcastle with 1.57](https://cesiumjs.org/releases/1.57/Apps/Sandcastle/index.html#c=ZVLBbtswDP0VwpckQGZh1ywtVhRdYaBZCyTbLr7IMh0TlSWDkpJlQ/99jJ2sySYIkETyPfJRVAo2LQWQrR3gT931FsE3kAK5LdxjoNRBmT03jSWHZTaHDrU7+moKxjuHJmINDfsOYoulU0poIrLTFgp3vGDMAYoIXQoRQiRroUIIyLszUIP1RuL3WI12nkOV4kBWewzgfARGewDvpE45UgxUo9iCT2wkwvOAJLlLti/y7DwjkGv8XDy4GMjaGPuwUGpLsU1Vbnyn7qTQQyRJ/8i6b8mEwhllBuFqT6+kTto/PCZJWbrS7TTDjnCPDDfgcH9qU/59sE0nI/jeu6gFx5M5/C4dyKJOb5EPL+x3QsWwOCMNo464IYsr3a9HHcV18PTEcVyJ7Tu2SmTrla+TxW9sp5O7EDAGtZFfSNIf9VXLqe2D5tgWxWQ20rzN5uOl0gGf9AH5hczrUFOjbcCTd4ve+PrdXLq32aehB4PWXP6XReRfRVf9eLCW+uCp3lxHnaXIKMggrU2LHUqCC+QPrFbIRkfPm4ug6WzIn82zZYgHi7cjz2fqes/x2JZpnquIMsTSzqCqJJJibkI4Fr1UZ9Cyph1QfVNm/3xVmYGxOgTxNMnaNf2Skb9dKom/glmva6nqWSbV6sMxpP14+zQa8zxfKnn+j4re20rzBeMf). Appears culled as above.

The only thing related to imagery/terrain in the [1.57 changes list](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md#157---2019-05-01) is this PR https://github.com/AnalyticalGraphicsInc/cesium/pull/7769. I'm going to confirm if that is the issue and then hopefully it should be a straightforward fix.

**Comment by OmarShehata** [comment] 2019-06-11 20:27
I've isolated this to this commit https://github.com/AnalyticalGraphicsInc/cesium/commit/b96c5a7a0978888fe14e2d2c1bf16ab1cb4debfd. It's specifically this if statement that causes the issue:

https://github.com/AnalyticalGraphicsInc/cesium/blob/b96c5a7a0978888fe14e2d2c1bf16ab1cb4debfd/Source/Scene/GlobeSurfaceTileProvider.js#L906

If I remove that width check:

```
if (defined(rectangle)) {
```

It works fine. @kring can you explain why that check is there? Do you any thoughts on a solution? I'm happy to open the PR if you have any advice here.

**Comment by tfili** [comment] 2019-06-27 15:29
@kring Any chance you would be able to look at this in the next few days before the release?

**Comment by kring** [comment] 2019-06-29 11:14
@OmarShehata it was added for #7702 / #7769. I'll investigate.

**Comment by kring** [comment] 2019-06-29 11:46
Ok I checked it out, and turns out this is already fixed in master! Specifically it was this change that fixed it:
https://github.com/AnalyticalGraphicsInc/cesium/pull/7940/files#diff-b82d964ca6c373e9d1246973ec43c947R633

After #7769, we weren't computing an OBB for whole-world tiles, because `OrientedBoundingBox` generates bad bounding volumes in that situation. However, we still had an unreliable horizon occlusion point, and it was causing the tiles to be culled in the case described in this issue. The PR above fixed it by bailing the visibility check early with "partial visibility" when there's no bounding volume, and skipping the horizon culling check entirely. The only time we won't have a bounding volume is with a single worldwide root tile, so this fix should be good.

I'm closing this issue because it is fixed.

**Closed by kring** 2019-06-29 11:46 UTC
Labels: category - terrain and imagery, priority - next release, type - bug
