### ISSUE TITLE
ImageryProvider.loadImage bug about KTX/CRN image

### ISSUE THREAD

**Issue by progsung** [AnalyticalGraphicsInc/cesium#7979] opened 2019-07-03 07:31 UTC
I think found a bug:
Recently I tested ktx and crn image Imagery using UrlTemplateImageryProvider.
I reviewed cesium source code and I thought it's no problem to service.
But at runtime, It's not working. So I review cesium source especially about Imagery.
And found one! at ImageryProvider.js
https://github.com/AnalyticalGraphicsInc/cesium/blob/32fc04d9e7e3b26e78ca1ca4b607091846a68c1e/Source/Scene/ImageryProvider.js#L336

```javascript
    ImageryProvider.loadImage = function(imageryProvider, url) {

        var resource = Resource.createIfNeeded(url);

        if (ktxRegex.test(resource)) {  //=> it should be "resource.url"
            return loadKTX(resource);
        } else if (crnRegex.test(resource)) {    //=> it should be "resource.url"
            return loadCRN(resource);
        } else if (defined(imageryProvider.tileDiscardPolicy)) {
            return resource.fetchImage({
                preferBlob : true,
                preferImageBitmap : true,
                flipY : true
            });
        }

        return resource.fetchImage({
            preferImageBitmap : true,
            flipY : true
        });
    };
```

I hope it can help someone.
thanks.

**Comment by OmarShehata** [comment] 2019-07-03 13:22
Thanks for reporting this @progsung - it does look like a bug to me. Were you able to get it to load the KTX image by changing that line? If you want to open a pull request to fix this, that would be awesome! The contributing guide is a good place to start here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request

**Comment by ProjectBarks** [comment] 2019-08-15 00:16
@OmarShehata This seems to be working as intended. 

KTX takes in a resource, url or buffer and then loads it through our Resource API.
```javascript
function loadKTX(resourceOrUrlOrBuffer) {
        //>>includeStart('debug', pragmas.debug);
        Check.defined('resourceOrUrlOrBuffer', resourceOrUrlOrBuffer);
        //>>includeEnd('debug');

        var loadPromise;
        if (resourceOrUrlOrBuffer instanceof ArrayBuffer || ArrayBuffer.isView(resourceOrUrlOrBuffer)) {
            loadPromise = when.resolve(resourceOrUrlOrBuffer);
        } else {
            var resource = Resource.createIfNeeded(resourceOrUrlOrBuffer);
            loadPromise = resource.fetchArrayBuffer();
        }

        if (!defined(loadPromise)) {
            return undefined;
        }

        return loadPromise.then(function(data) {
            if (defined(data)) {
                return parseKTX(data);
            }
        });
    }
```

Same goes for LoadCRN
```javascript
    function loadCRN(resourceOrUrlOrBuffer) {
        //>>includeStart('debug', pragmas.debug);
        if (!defined(resourceOrUrlOrBuffer)) {
            throw new DeveloperError('resourceOrUrlOrBuffer is required.');
        }
        //>>includeEnd('debug');

        var loadPromise;
        if (resourceOrUrlOrBuffer instanceof ArrayBuffer || ArrayBuffer.isView(resourceOrUrlOrBuffer)) {
            loadPromise = when.resolve(resourceOrUrlOrBuffer);
        } else {
            var resource = Resource.createIfNeeded(resourceOrUrlOrBuffer);
            loadPromise = resource.fetchArrayBuffer();
        }

        if (!defined(loadPromise)) {
            return undefined;
        }

        return loadPromise.then(function(data) {
            if (!defined(data)) {
                return;
            }
            var transferrableObjects = [];
            if (data instanceof ArrayBuffer) {
                transferrableObjects.push(data);
            } else if (data.byteOffset === 0 && data.byteLength === data.buffer.byteLength) {
                transferrableObjects.push(data.buffer);
            } else {
                // data is a view of an array buffer. need to copy so it is transferrable to web worker
                data = data.slice(0, data.length);
                transferrableObjects.push(data.buffer);
            }

            return transcodeTaskProcessor.scheduleTask(data, transferrableObjects);
        }).then(function(compressedTextureBuffer) {
            return CompressedTextureBuffer.clone(compressedTextureBuffer);
        });
    }
```

So while passing a URL should work it is no different than what we are doing currently. Let me know if I missed anything; otherwise, we can probably close this issue.

**Comment by mramato** [comment] 2019-08-15 00:24
@ProjectBarks take another look at the issue original  description and sample code.  The issue here is that we are passing Resource objects to the ktxRegex and crnRegex regular expression to determine the file type, not that we are passing resources   This is happening in both ImageryProvider and Material

**Comment by ProjectBarks** [comment] 2019-08-15 00:26
@mramato ahh totally missed it! Fix coming soon.

**Comment by OmarShehata** [comment] 2019-09-06 01:22
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/8064

**Closed by OmarShehata** 2019-09-06 01:22 UTC
Labels: category - terrain and imagery, good first issue, type - bug
