### ISSUE TITLE
 Too many combined image uniforms, shader storage  buffers and fragment outputs

### ISSUE THREAD

**Issue by niuzhendong** [AnalyticalGraphicsInc/cesium#7271] opened 2018-11-19 14:28 UTC
Sandcastle example: 
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=rVhtT+M4EP4rFlqpqVTyniZlWe5YurpF2jdBdafVdj+4iUmtdezKdlp6iP9+4yQNKRSusORDSZyZeR57nnHGOA46RRkpBBJXiHJNJE41XRIUjNGEMqKQ0mtGeT7ljoMu63vEMM9LnBM0FmlZEK6xpoIfobnWC3XkODnV83Jmp6JwTjlma01TzP6SeDGnqTrnqRNkh9pEd7QkxCmwAmBHLUhKr8DUBHMuO7jvS8oyA5xhjVEqSqmJWhvKX76foa8LwsfmxUJIjVlNA1isVivP5uvUzsXSUVQTJxNUa4dyqik2s1SGyKwJbi9gRlO+xBItKVkRid4hTlbojChaFvbf1ZjVS6vHMwGTppzI3gDdTDmCC6YgYeibFEuaEXm0cUwlwZr8IyTLJrWJ1Z/y2/7bKQe0KqqtUsKJnTMxI3ZGFno+IUqf5mCrdOMEbLQsSeVlUkE00nOC6skwlOICclcxR1ogJsQvhDX6jPkca415PbHG+puA5YBFhpgNyTNslpRiHthXUhRjkkNilHUYh7brJYkXuH7iun6YDFDo2sOR54VBEMRemPjeAMVRYKbTQfgq6UYW28v4kWCz2N+oTucXgrEtON+z/TiJR0mc+KMgCaIBOoSxIAxGbhS5SeyHQ4BzbTf2hqPIGwG1URJ6UYXeXcp6OWxFtMmb1aQog1WlvBHrvbUY1CbijvjRjsk0VoRnE4m5uhKyaBP9GWtJr0P7fPzhy+R88r1NMqTrk8BZlS8j2I3iFKqKgGi7XrvmaXvB6j/BeFK/tG5QKVmLeS74BVFQECmpVvJUgc15ZkVx6PXR7YN1WUha0Er6Ns4yq0FsaZ4JJmSH3wwrkiHIIVCnEsFPPjdsr0qeVrlNjcP79cfqhdVva6GZl9k8yOPzMTVONskxVxXuCHVG6lGeVTlSR+jH9itz/ei9uamZ3aKTdyhwXSjKnsxn2ApBQa7RpxFN1O/9HPyvu9+6W57rgy8Izou8vXy9jm8MuN4QAvhuuJdz1Pr6fghu/hB+gmQ/0lHrGxnIwDW47p6kW19T3l4MuEm8H+V2tiPj6YKn9+hKmd2rtffjAYpGAATW28adx9v6tlLx7WMKXTfaZFCfuswIqEXIzFQ52SHUT43V70s1I1ew/6sHYt3wuIB9DhvF9mR9Z7252by77fc6sxy8gv7voVbZce3Yq4QxPajiWr1FKReM9PrTg8eS+2icbhhJspfE8La4CNg/8xdx8bph1oQxsXpJGHeLDqPFi8i43SDpGvPHgzQF0FrPWFlD/m4BZFTBFz4lyHwBEDbtWVZg+WuH/seN6avpHz1Qa8sGpL+5t5Yk9a1OIQieN5UwQLvqA4Yrl0PoCEZeHMeRX334Tdpidzj0w/6TNYSeKCL0aBVt6EJ2TZPhGtm36colXj+lkPvOblIlu6DX1j2tDlC3kAbI6jofVs5JHzl1lPA5kOF9SNNX8Q7iHYUdoID1PNTj2tjdqsjVHFrtPaqgw7KuhJZkS7qL1SX2WwWzgsMJFEkv6EF/13w8OLSLO6rlCwxfkJxcv1JnA8qbHliS5B+uFxYQ6NvQdGvrEvpGnkNCDA3Qfh/9gbo7ihH+qA/O29u4GfZgOXbM+XIuVtC2sXVn3nl1DoEuc465aQ5QQeBRmUV42NfN4Qjzem2dMnRgO+g0D1WfdZ/5JWxcKRwGGTHd6UQINsPyM+Gl9aM9ZF1rE6lO6vs1qin2Nt07V4SR1JhspnLHvk3D3cTeNgwAv3OOuwex6RmeC3LXa+wFs9manwtzt6XvBWM0jSpRPxeoUw1PIX0E6bwgM9uK6wD8rE8nDzM35QeDg+NKiye1+Z+0MP8DMCcky7YdTYoFfFLgmD8r01+g21Qp43jsbJyOM7pENHsHm9f2sX56gFKGlYI3VyVjl/RfMj04OXbAfsuNieo4+3VJJMNrYzL3Tj7Vg7ZtHzvw+NBL18ruRPwP
Browser:
Google Chrome 70.0.3538.102
Operating System:
Ubuntu 18.04.1 LTS
![image](https://user-images.githubusercontent.com/16876679/48713074-64f03900-ec4a-11e8-81fe-94fc625a69fe.png)

**Comment by niuzhendong** [comment] 2018-11-20 05:16
![image](https://user-images.githubusercontent.com/16876679/48752881-6a8b6480-ecc6-11e8-973c-563e251c93d1.png)
![image](https://user-images.githubusercontent.com/16876679/48752895-7f67f800-ecc6-11e8-8eb4-bf90f7d7d810.png)

**Comment by niuzhendong** [comment] 2018-11-20 05:20
Hello, I am very glad to receive a reply. This question has troubled me for a long time. Thank you for your attention.

**Comment by hpinkos** [comment] 2018-11-20 14:50
Thanks @niuzhendong.  I didn't see anything obvious that would be causing the issue.  @lilleyse @mramato any ideas?

**Comment by mramato** [comment] 2018-11-20 15:32
`Max Texture Image Units` and `Max Vertex Texture Image Units` are only 16, `Max Combined Texture Image Units` is also only 96.  I think these values are lower than many other cards.  I have 32 and 192 on my Intel for example.

Even if it's a hardware limitation it's still probably something we should better handle on the Cesium side.

That's probably the extent of my usefulness, so I'll let @lilleyse or @likangning93 chime in here.

**Comment by hpinkos** [comment] 2018-11-20 15:38
I have `Max Vertex Texture Image Units: 16` and `Max Combined Texture Image Units: 32` on my computer and the example works fine.  I'm have NVIDIA on Windows though, and @niuzhendong reported AMD on Linux.  The only other big difference I saw was that @niuzhendong doesn't have ANGLE

**Comment by mramato** [comment] 2018-11-20 15:43
There's no ANGLE on Linux (and the example works fine for me on Linux).

So this definitely sounds like a possible AMD-only issue.

**Comment by hpinkos** [comment] 2019-09-19 19:49
Closing since we weren't able to reproduce this.

**Closed by hpinkos** 2019-09-19 19:49 UTC
