### ISSUE TITLE
An error occurred while i init a viewer in electron

### ISSUE THREAD

**Issue by dminor112** [AnalyticalGraphicsInc/cesium#6669] opened 2018-06-08 07:29 UTC
An error occurred while i init a viewer in electron. But i work good in chrome. How can i do to resolve this?
my cesiumjs version 1.46
![image](https://user-images.githubusercontent.com/7435641/41144598-05b87dda-6b30-11e8-902b-3957b576a634.png)

my code:
![image](https://user-images.githubusercontent.com/7435641/41145122-a500d684-6b31-11e8-9f4f-fded40a1e7ca.png)

**Comment by hpinkos** [comment] 2018-06-08 14:30
Hi @dminor112, have you seen this blog post? [An Introduction to Cesium Desktop Apps with Electron](https://cesium.com/blog/2016/04/04/an-introduction-to-cesium-desktop-apps-with-electron/)

**Comment by mramato** [comment] 2018-06-08 14:55
This is a dupe of #6671, we definitely need to fix this for next release.

**Closed by mramato** 2018-06-08 14:55 UTC
