### ISSUE TITLE
Problem with overlapping billboards

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5007] opened 2017-02-15 15:16 UTC
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/3jqWe5Ksi0k

This issue is the result of the transparent billboard fix that came in 1.30 #4886

Before: 

![image](https://cloud.githubusercontent.com/assets/3451886/22980533/d2f7d9f4-f367-11e6-8f47-26b97938a946.png)

After:
![image](https://cloud.githubusercontent.com/assets/3451886/22980541/d70dcd8c-f367-11e6-884b-84f6764c2fe0.png)

Parts of the green billboards are showing through the solid parts of the yellow billboards

**Comment by pjcozzi** [comment] 2017-02-15 17:35
@bagnell is there anything we can do about this other than sorting individual billboards by depth?

**Comment by lucasvw** [comment] 2017-02-23 09:01
+1

**Comment by smills2929** [comment] 2017-02-23 09:22
The way the issue is effecting me is the exact same as lucasvw. The edges of our circular icons show through each other.

**Comment by mramato** [comment] 2017-02-23 14:27
Marking this as next release so that we look at it for March 1st, but if the fix is non-trivial for some reason, it will probably have to wait for April 1st.

**Comment by pjcozzi** [comment] 2017-02-23 22:09
I agree this should be looked at soon.  @bagnell can you evaluate after #5021?  If it isn't an easy fix, what is the level of effort?

**Comment by lilleyse** [comment] 2017-02-28 01:34
@bagnell also will this make it in time for 1.31?

**Comment by bagnell** [comment] 2017-02-28 19:06
@lilleyse No, but a workaround to get the old behavior is:
`billboardCollection.blendOption = Cesium.BlendOption.TRANSLUCENT;`

**Comment by smills2929** [comment] 2017-03-02 01:59
@bagnell How does that work for an entity collection?

**Comment by bagnell** [comment] 2017-03-02 19:22
@smills2929 We don't expose the billboard collection for entities but you can access it with a private property.
```javascript
viewer.scene.postRender.addEventListener(function() {
    var clustering = viewer.dataSourceDisplay.defaultDataSource.clustering;
    var billboardCollection = clustering._billboardCollection;
    if (Cesium.defined(billboardCollection)) {
        billboardCollection.blendOption = Cesium.BlendOption.TRANSLUCENT;
    }
});
```
If you won't be removing all billboards, you can remove the event listener after it is called.

**Comment by emackey** [comment] 2017-03-02 21:30
The sample shown in screenshots at the top of this issue is a bad one.  The old versions only look "good" because of the old bug where the front billboard was completely wiping out the rear ones.  The sample code is asking for muddy overlap, and the old bug is what saves it from itself.

A much better example of this bug is shown in @lucasvw screenshots.  This can be seen in the "GeoJSON simplestyle" sandcastle demo, by zooming out.  For example, compare [GeoJSON in 1.27](http://cesiumjs.org/releases/1.27/Apps/Sandcastle/index.html?src=GeoJSON%20simplestyle.html&label=Showcases) to [GeoJSON in 1.30](http://cesiumjs.org/releases/1.30/Apps/Sandcastle/index.html?src=GeoJSON%20simplestyle.html&label=Showcases).  The newer version is on the right:

![badblending1 27_1 30](https://cloud.githubusercontent.com/assets/1235080/23527730/15df6af8-ff65-11e6-8645-599c27bbeaf9.png)

I have some ideas about this.  I'll open a PR soon.

**Closed** 2017-03-16 20:14 UTC
Labels: bug, next release
