### ISSUE TITLE
Polygon entity with callback property hierarchy crashes

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#8225] opened 2019-09-27 18:31 UTC
This works in 1.59 but not in 1.60
Likely related to this PR: https://github.com/AnalyticalGraphicsInc/cesium/pull/7991

Marking this 'next release' since it is a regression, but I don't expect it to be fixed for the October release.

```js
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.entities.add({
    polygon : {
        hierarchy : new Cesium.CallbackProperty(function() { 
            return Cesium.Cartesian3.fromDegreesArray([-115.0, 37.0,
                                                        -115.0, 32.0,
                                                        -107.0, 33.0,
                                                        -102.0, 31.0,
                                                        -102.0, 35.0]);
        }, false)
    }
});
```

**Comment by hpinkos** [comment] 2019-09-27 18:31
@shunter do you have time to look into this?

**Comment by shunter** [comment] 2019-09-27 22:24
Returning a position array instead of a PolygonHierarchy was always undocumented behavior.  You can fix your code snippet by calling the PolygonHierarchy constructor.

**Comment by OmarShehata** [comment] 2019-09-28 16:29
Closing since this is intentional, and also it's a duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/8135.

**Closed by OmarShehata** 2019-09-28 16:29 UTC
Labels: category - entity, priority - next release, type - bug
