### ISSUE TITLE
glTF uris should allow absolute or relative paths

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2911] opened 2015-07-31 10:13 UTC
Currently, they only support relative paths.  E.g., we need to check `new Uri(uri).isAbsolute()`.

[Forum discussion](https://groups.google.com/forum/#!topic/cesium-dev/YKRI5CJGVsM)

**Comment by shunter** [comment] 2015-08-01 02:17
I tested it out and it seems to be correctly loading images and buffers specified with absolute URLs in the glTF file.  Were you able to reproduce or are you just going off the info from the forum discussion?

To test, I edited the model in Box-Textured-Separate and changed the URLs to point to the hosted copies on cesiumjs.org.  (since we have CORS headers)

**Comment by pjcozzi** [comment] 2015-08-01 12:36
I didn't test; just going from the info on the forum.  The other external resource to check is shaders.

Are you saying this code is OK

  https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L1077

Since `_baseUri` is ignored when `shader.uri` is absolute, this is probably a CORS issue?

**Comment by pjcozzi** [comment] 2015-08-18 22:53
@shunter what do you think?

**Comment by shunter** [comment] 2015-08-19 21:51
Yes, the logic for resolving URLs relative to the baseUri is correct.  An absolute shader.uri (etc) will not be modified by the call to resolve.

**Closed** 2015-08-19 22:06 UTC
Labels: beginner, enhancement
