### ISSUE TITLE
Poor mobile performance introduced between 1.9 and 1.10

### ISSUE THREAD

**Issue by jasonbeverage** [AnalyticalGraphicsInc/cesium#2938] opened 2015-08-13 13:33 UTC
I updated our EarthViewer application from Cesium 1.6 to Cesium 1.12 yesterday and noticed that performance on mobile devices took a giant hit.  I tested on a Nexus 7, and Galaxy S Tab and two iPads and noticed the same thing.   I don't notice a difference on my desktop so I'm not sure if it's a mobile only thing or if my desktop is so fast that the difference is negligible.

The performance hit took place between the 1.9 and 1.10 release (and is still present in the 1.12 release).

I've put an example up that shows the issue.  Try hitting this with a mobile device.  

Example using 1.9, will be fast and responsive:
https://s3.amazonaws.com/jason.beverage.uploads/cesium-performance-test/cesium-1.9.html

Same example but with 1.10, will be very slow to rotate the globe:
https://s3.amazonaws.com/jason.beverage.uploads/cesium-performance-test/cesium-1.10.html

**Comment by pjcozzi** [comment] 2015-08-14 00:29
@bagnell is this because of a fullscreen pass we added?

**Comment by mramato** [comment] 2015-08-14 16:06
While this certainly sounds like a regression, I'll add that it's compounded by the fact that Cesium specifically ignores the `devicePixelRatio` setting suggested by the browser in order to provide native resolution rendering on all platforms (which is usually what people desire).  This can cause performance issues on some mobile devices since we have a fad of high-resolution screens without the GPU power to actually use them.  A good way to improve performance is to actually use this recommendation by setting the [resolutionScale](https://cesiumjs.org/Cesium/Build/Documentation/Viewer.html#resolutionScale) property.  For example: `viewer.resolutionScale = 1.0 / devicePixelRatio;` will cause Cesium to render at the browser/device recommended resolution (in almost all desktop cases, `devicePixelRatio` is 1 so always enabling this is okay.)  The one downside is that some mobile devices may render at a lower resolution than they can handle.  You could address this by add low/high quality options to your app, or use something like the `PerformanceWatchdog` in Cesium to turn on low-quality if the frame rate is less than desired.

**Comment by jasonbeverage** [comment] 2015-08-14 17:17
Thanks for the tip Mathew, setting the resolutionScale to 1.0 /
devicePixelRatio effectively doubles my frame rate in both 1.9 and 1.10!

There is a definite regression though since 1.9 still runs at double the
frame rate of 1.10.  With the resolutionScale set I'm getting 60fps with
1.9 and 30fps with 1.10.

**Comment by jasonbeverage** [comment] 2015-11-05 17:11
I looked through the changes from 1.9 to 1.10 and I'm beginning to suspect that this is something to do with the globe depth texture that was added from the globe-depth branch.  Is Cesium always going to render into a separate depth texture?  Is there a way we can turn that off?

**Comment by pjcozzi** [comment] 2015-11-07 20:47
Thanks for looking into this, @jasonbeverage.  That texture is needed for clamping polygons to terrain so it is possible that it could be turned off for limited use cases, but I want to do more profiling before exposing an option like that and complicating the rendering pipeline.  We'll post an update here; in the meantime, let us know if you discover anything else.

**Comment by rezn8d** [comment] 2017-06-05 21:20
Any updates on this? I am running 1,30 on [climateviewer.org](http://climateviewer.org/)  and the default settings give a framerate hit on iPad 2 that is tremendous.  I'll try viewer.resolutionScale = 1.0 / devicePixelRatio; until something is resolved in the repo.

**Comment by rezn8d** [comment] 2017-06-05 21:25
Jumping topics to Patrick's response here: [Re: cesium-dev Re: Performance of geometries on iOS](https://groups.google.com/d/msg/cesium-dev/4R0_Axdbicw/tfFa_R5pioMJ)

**Comment by mramato** [comment] 2017-06-05 21:27
Is this the original iPad 2 running at 1024x768?  What version of iOS is it running?  If it's the original iPad 2, the device is simply underpowered.

The workaround I posted above may or may not still be valid.  I'm actually surprised to still see this issue open.  The primary source of the slowdown was definitely fxaa, if you want, you can set `viewer.scene.fxaa = false` to get a boost in framerate.  Imagery will look better too.  The downside is that geometry and lines will appear more jagged.

I'm closing this because I don't think there's anything actionable here and 1.10 is 14 months old.

**Closed by mramato** 2017-06-05 21:27 UTC
Labels: bug, onramping, priority
