### ISSUE TITLE
Tracking in the GeoJSON simplestyle Sandcastle example is broken

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#4396] opened 2016-09-30 20:54 UTC
Load the GeoJSON simplestyle Sandcastle example and double click one of the pins.

**Comment by mramato** [comment] 2016-10-19 21:34
This is really weird, it only seems to happen in this example and only because that example is in 2D.  It seems to have been introduced in 1.23.  Perhaps clamping related?

**Comment by mramato** [comment] 2016-10-19 21:42
OK, I tracked it down.  There are 2 problems.

1. GeoJsonDataSource is not honoring clampToGround for billbaords, so they are being clamped by default.
2. `BillboardVisualizer.getBoundingSphere` is using `billboard._clampedPosition` for the boundingSphere location and that appears to be incorrect, either because of bugs in our clamping or perhaps it doesn't mean the same thing in 2D that we think it does? `getBoundingSphere` always expects to return world coordinates.

@bagnell thoughts?

**Comment by mramato** [comment] 2016-10-20 18:29
You now need to specify `clampToGround:true` when loading the GeoJSON to reproduce this (since we no longer clamp bu default).

**Comment by pjcozzi** [comment] 2016-10-21 20:08
Fixed in #4493

**Closed** 2016-10-24 20:44 UTC
Labels: bug, bug bash
