### ISSUE TITLE
PolygonGraphics render incorrectly when zoomed out and clamped to terrain

### ISSUE THREAD

**Issue by adunham1962** [AnalyticalGraphicsInc/cesium#4670] opened 2016-11-21 21:06 UTC
I'm seeing an issue where chunks of polygons are disappearing as I zoom farther away from them when they are clamped to terrain.

Cesium Sandcastle can be found [here](http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=776d1cb43372e7c66099b9b5b8d1d9bf).

Notice that as you zoom out, chunks of the polygon disappear.  I've seen some issues like #4661  and #4161 mention that this kind of behavior may be related to polygon triangles not behaving properly with more terrain-y locations, but in the sandcastle above the chunks that are disappearing are not quite as triangular in nature.  Maybe I'm reading into the "triangles" bit too literally and it is the same issue?

![rendering_bug](https://cloud.githubusercontent.com/assets/6944149/20500538/c4ab851e-b003-11e6-81ce-18083b6f682e.gif)

It's also worth mentioning that I have checked this across each version of Cesium since 1.22.1, which is the last version in which this wasn't an issue, but also the last version before Entity Clamp to Ground was added.

**Comment by hpinkos** [comment] 2016-11-21 21:09
Thanks @adunham1962 
This is a duplicate of #4161, see that issue for details

**Closed by hpinkos** 2016-11-21 21:09 UTC
