### ISSUE TITLE
[Bug] Broken label display

### ISSUE THREAD

**Issue by benjaminmur** [AnalyticalGraphicsInc/cesium#5294] opened 2017-05-09 08:29 UTC
Hi ! 

I run into an issue, when i display labels, for about 500 entities.
The display issue seems to not appear when the amount of entities is lower.

The labels display correctly, but after some time, labels start to disapear, but "partly".

I mean the background (black with opacity 0.5) is still at the right position, but all the text, or even just part of the text, is moved at a random position on the map.

Then, when i zoom in and out, the label text starts to flicker.

We display the same "moving thing" with three levels of zoom, with three different entities.
All the parts of those entities are display with displayDistanceCondition.

This is how it should look for medium zoom:

![singletrack](https://cloud.githubusercontent.com/assets/28558669/25841714/873546de-34a1-11e7-8b63-6ef189279a94.png)

This is how it should look for hight zoom:

![singletrackclose](https://cloud.githubusercontent.com/assets/28558669/25841885/2e5986c8-34a2-11e7-9f6e-263df64423c7.png)

This is how it should look for low zoom:

![singletrack2](https://cloud.githubusercontent.com/assets/28558669/25841881/2596b7fe-34a2-11e7-824a-0019d3bfe47f.png)

Her's the bug:

![bug](https://cloud.githubusercontent.com/assets/28558669/25841717/8ab29686-34a1-11e7-8972-c46bbb45862a.png)

The things to know is that i use displayDistanceCondition for those labels.
And, the entitie contains a polyline too.
BUT, if i use displaydistancecondition with the polyline, the polyline doesn't display well. it flickers.

So i managed to do the same as displayDistanceCondition, with my own algorythm
ONLY for the polyline, in a mouseMove handler, and it works well. But still, does it mess up with the label display ? as it's part of the same entity ?

I can't show you my code. But i'll try to make a sandcastle example.
Don't hesitate to ask questions if you want some details.

Thanks for your answers.

**Comment by hpinkos** [comment] 2017-05-09 12:48
Thanks @benjaminmur!  I haven't seen this problem before.  It would be really helpful if you could put together a minimal Sandcastle example to reproduce this.

**Comment by benjaminmur** [comment] 2017-05-09 15:35
Thanks for the reply !

I've try all day to reproduce this in sandcastle but I couldn't...

Basically the thing I do is to create entities and change the show properties of the label included into. The frequency of the change is the mouse_move event.

Be tried to find the minimal code portion that makes the label glitch.

I'll try more tomorrow. 
I'll keep you updated.

Thanks again.

**Comment by benjaminmur** [comment] 2017-05-09 15:37
One more thing. 

What makes me think this is a bug in cesiumjs, is that the label, Wich is composed by the background and the text, should not be separated in any way.

Seeing the background at the right place but not the text makes me think of a rendering stack error.

That.s my 2 cents, even if it must be obvious for you guys XD

**Comment by hpinkos** [comment] 2017-05-09 15:43
@benjaminmur yeah, thanks for looking into it!  I do agree it's probably a bug on our end, it's just hard for us to figure out what the cause is without being able to reproduce it locally

**Comment by emackey** [comment] 2017-05-09 20:08
This reminds me a lot of #5154, could this be a duplicate of that?

**Comment by pjcozzi** [comment] 2017-05-09 23:35
> This reminds me a lot of #5154, could this be a duplicate of that?

I suspect so. @benjaminmur what do you think?

**Comment by benjaminmur** [comment] 2017-05-11 09:14
Sorry for the late update.

I've done some more work.

I've figure out that if i remove the display distance condition properties, all works fine.

I'll try to put this property back on some entities, to see on what "graphics" of the entity the conditiion break the display.

Does that help?

I'm sorry for the lack of sandcastle exemple, i've try to reproduce the same behavior but couldn't.
I think we do many things in our code that i didn't reproduce in sandcastle.

**Comment by pjcozzi** [comment] 2017-05-11 16:40
> I've figure out that if i remove the display distance condition properties, all works fine.

Hmm, this might mean that this issue is not related, so let's keep this open.

If you do end up coming up with a Sandcastle example, it will be much appreciated.

**Comment by hpinkos** [comment] 2019-09-19 17:53
Closing this since we weren't able to reproduce this and never got a sandcastle example

**Closed by hpinkos** 2019-09-19 17:53 UTC
Labels: category - labels, type - bug

**Comment by Nadav42** [comment] 2021-04-25 19:34
this happens because atlas._textureCoordinates saves the billboard's coordinates as floating points, this is completely fine at start but as the atlas grows it loses accuracy and starts taking the wrong coordinates.

In order to reproduce this issue you should use an example where there are a lot of different textures in the atlas which caused it to reach a very large size.

I'm pretty sure this can be fixed by using a larger `borderWidthInPixels` as the atlas grows to make up for the lost of accuracy
