### ISSUE TITLE
some partial earth image disapear

### ISSUE THREAD

**Issue by LHZ593123** [AnalyticalGraphicsInc/cesium#8467] opened 2019-12-17 06:47 UTC
I downloaded the Cesium1.64, installed the npm and run “node ./server.js” to start the server, run “localhost:8080/index.html” to start HelloWorld.html step by step.
I found some partial earth image disapear when Cesium initialize earth image(As show in above). It does not happen every time,it more likely to happen when the google browser cache cleanup.
It gives us not a very good experience, I want to know how to solve this problem.

If anyone has the same experience or knowledge about this problem,I would like to discuss this very much.
Thank you.
My Email is: 609232410@qq.com.
![图片1](https://user-images.githubusercontent.com/32538544/70971485-0fe85600-20dc-11ea-846c-0f4d4d9c5b3e.png)

**Comment by OmarShehata** [comment] 2019-12-17 15:34
Are you able to reproduce this in the hosted CesiumJS hello world example?

https://cesium.com/downloads/cesiumjs/releases/1.64/Apps/HelloWorld.html

I'm not able to reproduce this with a clear cache and trying to refresh multiple times. Are you using the default Bing maps imagery and all default settings?

When this happens does that gap last or does it get filled after a few seconds? Are you able to share a video of this?

Closing for now since there isn't enough information in this issue to investigate or resolve. You can always use the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) for general questions or when you're still gathering information.

**Closed by OmarShehata** 2019-12-17 15:34 UTC
