### ISSUE TITLE
InfoBox without description In Google Chrome 

### ISSUE THREAD

**Issue by AndreyOrlov** [AnalyticalGraphicsInc/cesium#6118] opened 2018-01-15 12:43 UTC
Hello, 
In this Sandcastle example https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=KML.html&label=Showcases
If you open it and click to some feature in Firefox you can see window with description. 
![2018-01-15_15h38_51](https://user-images.githubusercontent.com/2196469/34942859-37651c9a-fa0a-11e7-9e0c-7b84650e2cb2.png)

But if you do the same in Google Chrome you can see only Title
![2018-01-15_15h39_30](https://user-images.githubusercontent.com/2196469/34942878-4c1ea354-fa0a-11e7-8d68-8f4fcc81c088.png)

Windows 10 x64
Google Chrome 63.0.3239.132(64)

**Comment by hpinkos** [comment] 2018-01-16 15:08
@AndreyOrlov I couldn't reproduce this either.  Make sure your version of Chrome is up to date, and try clearing your cache and cookies to see if that fixes the problem.

Thanks for reporting this though!  I'm going to close this issue for now.

**Closed by hpinkos** 2018-01-16 15:08 UTC
