### ISSUE TITLE
pickPosition only works on 3D tiles if depthTestAgainstTerrain = true

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5676] opened 2017-07-25 14:04 UTC
This picking example only works if you uncomment the third line

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;
//scene.globe.depthTestAgainstTerrain = true;

var labelEntity = viewer.entities.add({
    label : {
        text: 'X',
        fillColor: Cesium.Color.RED,
        show: false,
        horizontalOrigin: Cesium.HorizontalOrigin.CENTER,
        verticalOrigin: Cesium.VerticalOrigin.BOTTOM
    }
});

// Mouse over the globe to see the cartographic position
var handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);
handler.setInputAction(function(click) {
    var foundPosition = false;
    if (scene.mode !== Cesium.SceneMode.MORPHING) {
        var pickedObject = scene.pick(click.position);
        if (scene.pickPositionSupported && Cesium.defined(pickedObject)) {
            var cartesian = viewer.scene.pickPosition(click.position);

            if (Cesium.defined(cartesian)) {
                labelEntity.position = cartesian;
                foundPosition = true;
            }
        }
    }

    labelEntity.label.show = foundPosition;
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);

var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
    url : '../../../Specs/Data/Cesium3DTiles/Tilesets/Tileset'
}));

tileset.readyPromise.then(function() {
    var boundingSphere = tileset.boundingSphere;
    viewer.camera.viewBoundingSphere(boundingSphere, new Cesium.HeadingPitchRange(0.0, -0.5, boundingSphere.radius * 2));
    viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
});
```

**Comment by SunBlack** [comment] 2017-07-26 13:21
I have same issue. But one information is missing here in this ticket: `pickPosition` works not Ellipsoid, but on STK Terrain.
![cesium](https://user-images.githubusercontent.com/483922/28623354-043e795a-7216-11e7-98ac-92da03942d2e.gif)

My test code:
```
var viewer = new Cesium.Viewer('cesiumContainer');

var handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
var positions = [];
var lineStrip;
var floorSpacePolygon;

handler.setInputAction(function(movement) {
    if (!viewer.scene.pickPositionSupported) {
        console.warn("pickPosition not supported!");
        return;
    }

    var pickedPosition = viewer.scene.pickPosition(movement.position);

    if (pickedPosition !== undefined) {
        positions.push(pickedPosition);				

        if (positions.length > 1) {
            viewer.entities.remove(lineStrip);

            lineStrip = viewer.entities.add({
                polyline: {
                    positions: positions,
                    width: 5,
                    material: Cesium.Color.ROYALBLUE,
                    followSurface: true
                }
            });
        }
        
        if  (positions.length > 2) {
            viewer.entities.remove(floorSpacePolygon);
            floorSpacePolygon = viewer.entities.add({
                polygon: {
                    hierarchy: new Cesium.PolygonHierarchy(positions),
                    material : Cesium.Color.ORANGE.withAlpha(0.4)
                }
            });
		}
    }
}, Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);

handler.setInputAction(function(movement) {
    positions = [];
    viewer.entities.remove(lineStrip);
    viewer.entities.remove(floorSpacePolygon);
}, Cesium.ScreenSpaceEventType.RIGHT_CLICK);
```

**Comment by hpinkos** [comment] 2017-07-26 14:36
@SunBlack thanks for the example!  Yes, this looks like the same root problem.  If you add this line to your example it works: `viewer.scene.globe.depthTestAgainstTerrain = true;`

It works when you select the STK terrain because the `BaseLayerPicker` enables `depthTestAgainstTerrain` when you select that option.

**Comment by hpinkos** [comment] 2017-07-31 19:35
This bug makes the [3D Tiles Interactivity](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Interactivity.html&label=All) Sandcastle example completely broken in Firefox.  `pickPosition` looks like it's mostly working correctly in Chrome, but it never returns the right position in Firefox

**Comment by hpinkos** [comment] 2017-07-31 19:40
@pjcozzi Actually, it looks like this works fine in 1.35 but is broken in master right now.  Do you think that's a significant enough problem to hold up the 1.36 release, or should we just shoot to fix this for 1.37?

**Comment by lilleyse** [comment] 2017-07-31 23:32
I think the problem is with the new render ordering for classification primitives. The order used to be:

Globe
Ground Primitives
Clear Depth
3D Tiles

but is now:

Globe
3D Tiles
Ground Primitives
Clear Depth

So by gaining ground primitives on 3D Tiles we lost `pickPosition` on 3D Tiles.

@bagnell do you know if there is a quick enough fix for the release tomorrow?

**Comment by bagnell** [comment] 2017-08-01 00:06
There isn't a quick fix for this. I would say have users set `depthTestAgainstTerrain` to `true` until we figure out the best solution. We could have a fullscreen pass to copy the globe + 3D Tiles depth for each frustum every frame or have a depth only pass for 3D Tiles after the depth is cleared. Neither solution is ideal.

**Comment by pjcozzi** [comment] 2017-08-02 00:33
@bagnell @lilleyse let's discuss to see if we are able to fix this for 1.37.

May also be able to solve #5683 at the same time.

**Comment by lilleyse** [comment] 2017-08-05 16:56
Added a temporary fix for the 3D Tiles Interactivity demo #5724. That code can be reverted when this issue is solved.

**Comment by pjcozzi** [comment] 2017-08-21 23:35
Discussed with @bagnell offline and we will fix this in 1.37 by rendering classification primitives up to 2x with a enum that is `3D Tiles`, `Terrain`, or `Both` (default).

Longer term, #2160 will fix this since there will be no clear depth step after terrain / 3D Tiles.

**Closed** 2017-08-29 19:17 UTC
Labels: category - 3d tiles, category - picking, priority - next release, type - bug

**Comment by JoshuaKahn** [comment] 2021-05-12 02:42
I'm having this bug now - setting `viewer.scene.globe.depthTestAgainstTerrain = false` makes `pickPosition` on the ellipsoid fail.

I want to disable `depthTestAgainstTerrain` to stop KMLs from digging into the terrain but in doing so I can't pick on the ellipsoid anymore.

**Comment by UgniusFE** [comment] 2021-07-27 11:10
I am having the same issue as @JoshuaKahn

**Comment by UgniusFE** [comment] 2021-09-22 10:06
I believe the bug is here https://github.com/CesiumGS/cesium/blob/a02065697660f2ee1960548a5630578a8a11e3d0/Source/Scene/Picking.js#L396-L402

**Comment by michalbie** [comment] 2024-05-31 18:37
Have you found a way to solve this issue? Still encountering it in 2024, Cesium 1.102
