### ISSUE TITLE
can not move the viewer when you mouse on the label.

### ISSUE THREAD

**Issue by hemincan** [AnalyticalGraphicsInc/cesium#8326] opened 2019-10-28 02:11 UTC
when the label entity set showBackground=true, and  heightReference=Cesium.HeightReference.CLAMP_TO_GROUND，can not move the viewer when you mouse on the label.

viewer.entities.add({
        position : Cesium.Cartesian3.fromDegrees(86.925145, 27.9822222),
        label : {
             showBackground: true,
             text : '565656',
             heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
             disableDepthTestDistance: Number.POSITIVE_INFINITY,
        }
});

[sandcastle example](https://sandcastle.cesium.com/index.html#c=fVNrb9owFP0rFl9Ipczk/WC0WgvdhlSgalmrSUiVSS5g4djMdqDt1P8+hwArbdWbD0nu45xz77XXRKKNkCwfg5SEcnSKuqBoWeBMAtFw/ypm/Z1wZEzCnxKUvjdhOSBq2UZalmAfBe9AangcClkQpuqECX85+TrhE742nGsKG5CGjcNmz3i39VnNbPvbFVwbUpBNG+2Ida3jWoo1zUG2j5Qf4GclzzQVHDEhlud6oC/XII0k62SPUwnQRM5BHwvoEiNaUcJ9y3ecOHZw6CSx5yepnwQ2CiM/SF0Pu77rp0GYhDby0jhxQw97SRSGQei6UaVhzyFmM/UJh4ELcBoHTppEcRJGno2+xKmP/cBN4zRxEjcOXMMRpClOjZIkcuLIdyPvwLEdGM5IAZLgul2rbszekX+WOpaEq5lZkbXTNiBa0scA93uXw3F//LsqfqlG+m6S9RIZmQIz7R3ggWuqKShM8nx/WipbCUW3K2m/HwOeSVH0YC4BlJVEOPVCN6hGG+M08So7sfdI/xFr6jZ6RbI1tRCbC5It51KUPD86mXsz51KbymYYVU/zTRQtgM4X+gZmplWewUHxz2M/7l6dD64fxqOHHzejX8PeW5icKjJl0IOVXozNzHpUabLFG5bF1MzqenTbH/fvLh/6w+/9oZn2K4SX+tMc6Ibd6Cj9xOCsdn2jxUpIjUrJLIxbGooVM/dQtaZltgSNM6WqrXVa+6JOTteI5qeTxptrNWmgjBGlTGRWMnZLn2HSOOu0TP5RGRMkp3w+Mqtn5KlKWbhnV7UTY9xpmd/3VVoINiWG5NhbX9UB8PJDrmchiotSa8HVh3FFTLvwQcbu/Q8)

**Comment by mramato** [comment] 2019-10-28 13:30
Thanks for the sample code and bug report @hemincan.  @hpinkos is this the same root cause as #6840.  If so we should close this and link to it from there.

The issue is `disableDepthTestDistance: Number.POSITIVE_INFINITY`.  You can get the same behavior by setting `viewer.scene.globe.depthTestAgainstTerrain = false;` and removing `disableDepthTestDistance` altogether.  Of course that means you won't be depth testing _anything_ against terrain, so it depends on your use case.

**Comment by hpinkos** [comment] 2019-10-28 14:42
yep, this is the same as #6840

**Closed by hpinkos** 2019-10-28 14:42 UTC
